### PR TITLE
imhex: Fixed `pre_uninstall`, `checkver`, and `autoupdate.url`.

### PR DESCRIPTION
**Pull request by Zliced13**
Fixed it so that it only removes the context menu when the user passes the **uninstall** parameter.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by niheaven** [comment]
Have you test it locally by `checkver` before creating the PR? Too many `/verify`s here.

BTW, why `reg delete` instead of `Remove-Item`?

**Comment by Zliced13** [comment]
`reg delete` is much faster than `Remove-Item`. And yes, I have tested the manifest locally on my machine.

**Review by niheaven — APPROVED** [review]

**Pull request merged**
