### PR TITLE
vencord-installer: Add version 1.4.0

### PR DESCRIPTION
**Pull request by he3als**
Adds the GUI variant of [Vencord/Installer](https://github.com/Vencord/Installer) (CLI is #13201).
Relates to https://github.com/ScoopInstaller/Extras/issues/13200

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by he3als** [comment]
VirusTotal report: https://www.virustotal.com/gui/file/dc0826657a005009f43bdc3a0933d08352f8b22b2b9b961697a2db6e9913e871/detection

There was only one false positive. The community score is low because people mistakenly blame Vencord when their Discord account gets compromised due to external scams.

**Review by sitiom — APPROVED** [review]
Thanks!

**Pull request merged**
