### PR TITLE
ddu: Update to version 18.0.6.9

### PR DESCRIPTION
**Pull request by brian6932**
moved `checkver` to the official AssemblyInfo file
moved `url` to a mirror due to Cloudflare cookie and js requirements
changed `homepage` due to checkver errors

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by b4imetu** [comment]
Display Driver Uninstaller (DDU) V18.0.6.9 Released.

`checkver` seemed to fail

**Review by HUMORCE — APPROVED** [review]

**Pull request merged**
