### PR TITLE
airdroid: Add version 3.7.1.1

### LINKED ISSUE #7135: (Request) add simpletransfer
PackageIdentifier: simpletransfer
PackageVersion: 2.2
PackageLocale: en-US
Publisher: rambax
PackageName: simpletransfer
License: proprietary
ShortDescription: photo sharing app
Installers:

Architecture: x64
InstallerType: exe
InstallerUrl: https://rambax.com/simpletransfer/desktop/SimpleTransfer%20Desktop%20Setup%202.2.0.exe
ManifestType: singleton
ManifestVersion: 1.0.0

### LINKED ISSUE #7142: (Request) add Airdroid
PackageIdentifier: Airdroid
PackageVersion: 3.6.9.1
PackageLocale: en-US
Publisher: sand studio
PackageName: Airdroid
License: Proprietary
ShortDescription: app for integrate between Windows and Android
Installers:

Architecture: x64
InstallerType: exe
InstallerUrl: https://dl.airdroid.com/AirDroid_Desktop_Client_3.6.9.1.exe
ManifestType: singleton
ManifestVersion: 1.0.0

### PR DESCRIPTION
**Pull request by Zliced13**
Closes #7142

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by rasa — APPROVED** [review]

**Comment by HUMORCE** [comment]
alter `checkver`

```
$url = 'https://srv3.airdroid.com/p20/web/getbinaryredirect?type=exe&channel=&version='
$resp = Invoke-WebRequest $url -MaximumRedirection 0 -ErrorAction Ignore
$result = $resp.Headers.Location    # https://dl-qn.airdroid.cn/AirDroid_Desktop_Client_3.7.1.1.exe
```

**Pull request merged**
