### PR TITLE
010 Editor: Add version 12.0.1 (Closes #4290)

### LINKED ISSUE #4290: [Request] Add 010 Editor
Hello, please add 010 Editor to scoop.

010 Editor is a professional text editor and a hex editor.
https://www.sweetscape.com/010editor/

It is a 30 day free trial, and it has a portable version - https://www.sweetscape.com/download/010editor/

The installer is an InnoSetup installer.

Thanks!

### PR DESCRIPTION
**Pull request by Vedabahu**
Added 010 Editor.
This is paid software so you get a 30 day trial. After that we must buy a copy on the website.
This can be done [here](https://www.sweetscape.com/store/?010editor). More information for it can be found on their [website](https://www.sweetscape.com/store/?010editor).
 
This is a normal editor as well as a Hex editor. It is made by the [Sweetscape Software](https://www.sweetscape.com/) company.
Version 12.0.1 was released on October 7, 2021. Check [release notes](https://www.sweetscape.com/010editor/release_notes.html) for more info.

Feature list can be found on their [Features Page](https://www.sweetscape.com/010editor/features.html).

Closes #4290

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Vedabahu** [comment]
Added the suggested changes.

**Comment by issaclin32** [comment]
I am okay with adding this package, but I want to ask opinions from other maintainers.

**Comment by Vedabahu** [comment]
> I am okay with adding this package, but I want to ask opinions from other maintainers.

Ok. That's fine.

**Review by rashil2000 — APPROVED** [review]
This is similar to typora (in Extras), so I'm also fine with this.

**Review by HUMORCE — APPROVED** [review]

**Pull request merged**
