### PR TITLE
xdman: Update manifest

### PR DESCRIPTION
**Pull request by HUMORCE**
- Add notes
- Update suggest
- Add scirpt url/hash

Relates to https://github.com/ScoopInstaller/Extras/pull/7869#issuecomment-1025071550

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by issaclin32 — APPROVED** [review]

**Comment by issaclin32** [comment]
The script works fine under Powershell 7, but not on Powershell 5. Therefore [I modified the script](https://github.com/ScoopInstaller/Extras/commit/796f28ab6e01026e38cba83f4fbb49ac3d9279b2).

**Comment by candrapersada** [comment]
why is bat file missing like `xdman.bat` and `Xtreme Download Manager.bat`?

**Comment by candrapersada** [comment]
why is the `Xtreme Download Manager.bat` file missing from Scoop Apps?

**Comment by HUMORCE** [comment]
> why is the `Xtreme Download Manager.bat` file missing from Scoop Apps?

this package no longer contains any 3rd-party tools.

**Pull request merged**
