### PR TITLE
Update KDE Kate to version 22.08.1

### LINKED ISSUE #9289: KDE Kate out of date
## Bug Report

scoop.kate 

### Current Behaviour

scoop.kate version is [22.04.01](https://scoop.sh/#/apps?q=kate)

### Expected Behaviour

latest version is [22.08.1](https://github.com/KDE/kate/tags)

### PR DESCRIPTION
**Pull request by KrisSchneider**
Closes #9289 

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tech189** [comment]
I'm not sure we should do this in Extras, at the moment this app is only updated when a stable version is released. If this PR is merged, then the app will be updated daily regardless of whether any changes have been made - it's a daily build. There have been [no changes](https://binary-factory.kde.org/job/Kate_Release_win64/changes) in the last 10 builds. Maybe instead we could add this PR's manifest as a `stable-nightly` version to the Versions bucket. What do you think @rashil2000?

**Comment by rashil2000** [comment]
> Maybe instead we could add this PR's manifest as a `stable-nightly` version to the Versions bucket. What do you think @rashil2000?

We used to do this before I switched them to update only on stable releases. There's no point in updating when there's been no commits. 


We should just update the download URL and regex to match the website.

**Comment by rashil2000** [comment]
**Edit:**

Merged in #9298 

We also need to do this for `okular`, `kdeconnect`, and `filelight`.

**Comment by rashil2000** [comment]
Merged in #9298

**Pull request closed without merging**
