### PR TITLE
sumatrapdf: Fix download urls

### PR DESCRIPTION
**Pull request by Outis9**
It seems sumatrapdf's download urls cannot be accessed, so change the  urls.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by c0bw3b** [comment]
Merging this would allow picking up recent updates to 3.5.x :)

**Review by YDX-2147483647 — APPROVED** [review]

**Comment by YDX-2147483647** [comment]
Ops I find this reverts #8679…

> It seems sumatrapdf's original download urls have some redirection error, so use target urls.

**Comment by wu0lss4j** [comment]
Thanks everyone, I was trying to do my part updating this for the excellent lightweight pdf reader. I'll be more diligent next time and sorry for the multiple pulls/commits/etc...

**Comment by CaselIT** [comment]
this PR also seems to fix the update of sumatrapdf. version 3.5.2 is the last one in the website, but the manifest still lists version 3.4.6

**Comment by wu0lss4j** [comment]
> his PR:

Hi, sorry for the newb question, what does PR mean?

**Comment by CaselIT** [comment]
it an abbreviation of pull request

**Comment by kfot** [comment]
Can somebody approve it already? Sumatra installation has been broken for two weeks now

**Comment by wu0lss4j** [comment]
> Can somebody approve it already? Sumatra installation has been broken for two weeks now

I wish I could do it, I just modified my json file locally and scoop updated sumatrapdf for me

**Review by HUMORCE — APPROVED** [review]

**Comment by HUMORCE** [comment]
I had to choose the latest PR to merge due to the fact that it had been unmaintained for a long time.

go #12251

**Pull request closed without merging**
