### PR TITLE
wechat: Update to Version 3.9.6.33 and `checkver`

### PR DESCRIPTION
**Pull request by b4imetu**
Closes #XXXX

Relates to #XXXX

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by b4imetu** [comment]
https://github.com/ScoopInstaller/Extras/commit/71bd55e1a25c9b681808dcfc0e92d854a42e9a48
https://github.com/ScoopInstaller/Extras/commit/196e05973d0a84fd5b0c9c20f12329cf244c346d
https://github.com/ScoopInstaller/Extras/commit/ed2e3915801b7b37e723bb4f09c3562e5e235f3b
As we can see, the naming of the `wechat` installer always changes between `WeChatSetup_`$version and `WeChat`$version.
Is there any way to fix this?

**Comment by b4imetu** [comment]
https://github.com/ScoopInstaller/Extras/commit/71bd55e1a25c9b681808dcfc0e92d854a42e9a48
https://github.com/ScoopInstaller/Extras/commit/196e05973d0a84fd5b0c9c20f12329cf244c346d
https://github.com/ScoopInstaller/Extras/commit/ed2e3915801b7b37e723bb4f09c3562e5e235f3b
As we can see, the naming of the `wechat` installer always changes between `WeChatSetup_`$version and `WeChat`$version.
Is there any way to fix this?

**Comment by b4imetu** [comment]
@Ryanjiena Thank you

**Review by HUMORCE — APPROVED** [review]

**Pull request merged**
