### PR TITLE
 blender-benchmark-cli: Add version 3.1.0

### PR DESCRIPTION
**Pull request by ipcjs**
- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aliesbelik** [comment]
@ipcjs, I guess, it would be better to rename the manifest to something like `blender-benchmark-cli`.

**Comment by ipcjs** [comment]
Okay, I've renamed the file.

**Pull request merged**
