### PR TITLE
Add Password Tech

### PR DESCRIPTION
**Pull request by kzshantonu**
Need help with extraction and autoupdate

### CODE REVIEW

**Comment by rashil2000** [comment]
Fixed manifest:

```json
{
    "version": "3.4.1",
    "description": "Professional password generator and manager, formerly known as PWGen",
    "homepage": "https://pwgen-win.sourceforge.io",
    "license": "GPL-2.0-only",
    "architecture": {
        "64bit": {
            "url": "https://downloads.sourceforge.net/project/pwgen-win/Password%20Tech/3.4.1/PwTech-3.4.1-64bit.zip",
            "hash": "6fb08c527b9574611af5baa64115fc40fcc835a0fca8220999ddbe88b4b0b87a"
        },
        "32bit": {
            "url": "https://downloads.sourceforge.net/project/pwgen-win/Password%20Tech/3.4.1/PwTech-3.4.1-32bit.zip",
            "hash": "c1ac202f869583511aecb60915fe0bb04e3a7e22f5128e6c73dab7e5dcf56d2c"
        }
    },
    "pre_install": "if (!(Test-Path \"$persist_dir\\PwTech.ini\")) { New-Item \"$dir\\PwTech.ini\" -ItemType File | Out-Null }",
    "bin": "PwTech.com",
    "shortcuts": [
        [
            "PwTech.exe",
            "Password Tech"
        ]
    ],
    "persist": "PwTech.ini",
    "checkver": {
        "url": "https://pwgen-win.sourceforge.io/download",
        "regex": "Download PwTech ([\\d.]+)"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://downloads.sourceforge.net/project/pwgen-win/Password%20Tech/$version/PwTech-$version-64bit.zip"
            },
            "32bit": {
                "url": "https://downloads.sourceforge.net/project/pwgen-win/Password%20Tech/$version/PwTech-$version-32bit.zip"
            }
        }
    }
}
```

**Comment by kzshantonu** [comment]
Thanks. Please add hash checking for auto updates since it's a security software. Hashes are at https://sourceforge.net/projects/pwgen-win/files/Password%20Tech/$version/ 

I really need to learn regex :'(

**Comment by rashil2000** [comment]
```json
{
    "version": "3.4.1",
    "description": "Professional password generator and manager, formerly known as PWGen",
    "homepage": "https://pwgen-win.sourceforge.io",
    "license": "GPL-2.0-only",
    "architecture": {
        "64bit": {
            "url": "https://downloads.sourceforge.net/project/pwgen-win/Password%20Tech/3.4.1/PwTech-3.4.1-64bit.zip",
            "hash": "6fb08c527b9574611af5baa64115fc40fcc835a0fca8220999ddbe88b4b0b87a"
        },
        "32bit": {
            "url": "https://downloads.sourceforge.net/project/pwgen-win/Password%20Tech/3.4.1/PwTech-3.4.1-32bit.zip",
            "hash": "c1ac202f869583511aecb60915fe0bb04e3a7e22f5128e6c73dab7e5dcf56d2c"
        }
    },
    "pre_install": "if (!(Test-Path \"$persist_dir\\PwTech.ini\")) { New-Item \"$dir\\PwTech.ini\" -ItemType File | Out-Null }",
    "bin": "PwTech.com",
    "shortcuts": [
        [
            "PwTech.exe",
            "Password Tech"
        ]
    ],
    "persist": "PwTech.ini",
    "checkver": {
        "url": "https://pwgen-win.sourceforge.io/download",
        "regex": "Download PwTech ([\\d.]+)"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://downloads.sourceforge.net/project/pwgen-win/Password%20Tech/$version/PwTech-$version-64bit.zip",
                "hash": {
                    "url": "https://downloads.sourceforge.net/project/pwgen-win/Password%20Tech/$version/readme.txt",
                    "regex": "$sha256\\s*\\*64bit\\.zip"
                }
            },
            "32bit": {
                "url": "https://downloads.sourceforge.net/project/pwgen-win/Password%20Tech/$version/PwTech-$version-32bit.zip",
                "hash": {
                    "url": "https://downloads.sourceforge.net/project/pwgen-win/Password%20Tech/$version/readme.txt",
                    "regex": "$sha256\\s*\\*32bit\\.zip"
                }
            }
        }
    }
}
```

**Pull request merged**
