### PR TITLE
Update msiafterburner.json: Corrects version in the manifest

### PR DESCRIPTION
**Pull request by RavenMacDaddy**
- Updates version described in the manifest to the current which is 4.6.4.16255

### CODE REVIEW

**Comment by rashil2000** [comment]
Checkver is failing. See the Actions log.

**Comment by RavenMacDaddy** [comment]
Where's the GIF when I need it...

I should've expected it when it didn't catch it on its own.

I was assuming since it already had the checkver and everything that it was just the versioning getting muddled up, let's see...

**Comment by RavenMacDaddy** [comment]
Well, the URL is the same, and what regex is based on seems unchanged, including the versioning; went from 4.6.3 to 4.6.4.

From what I saw, what was missing was one of the parentheses at the end, so that's what I changed.

See if you notice anything else wrong with the regex.

**Comment by rashil2000** [comment]
The closing parenthesis needs to be escaped as well

**Comment by RavenMacDaddy** [comment]
Like that?

**Comment by rashil2000** [comment]
Before the parenthesis, not after

**Comment by RavenMacDaddy** [comment]
How about now? Anything else that makes it fail?

**Comment by rashil2000** [comment]
The issue is that this regex matches only the 4.6.4 part, and not the 16255 part. The 16255 part cannot be found anywhere on the webpage. 

We can change the version to "4.6.4" only and remove the 16255 part.

**Comment by RavenMacDaddy** [comment]
You're right, hang on.

**Comment by RavenMacDaddy** [comment]
There

**Comment by rashil2000** [comment]
We can add the full version later when we find a good source

**Pull request merged**
