### PR TITLE
git-tower: Add version 4.0.410

### LINKED ISSUE #9432: [Request] git-tower
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [x] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [x] the latest stable version of the program

### Information

**Name:** git-tower

**Description:** Tower is the perfect level of abstraction away from command-line Git usage. A simple and powerful UI, but without hiding what makes Git powerful. 

**Homepage:** https://www.git-tower.com/windows

**Download link(s):** https://www.git-tower.com/download/windows

**Some indication of popularity/repute:** [GitHub stars/software reviews etc.]

### PR DESCRIPTION
**Pull request by Zliced13**
Closes #9432

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Zliced13** [comment]
Does anyone know why the **autoupdate hash extraction** does not work?

**Comment by Zliced13** [comment]
@rashil2000 I need help please.

**Comment by niheaven** [comment]
You sould use F12 to check if the version number has been popped instead of using `checkver.script`... The latter is provided as a fallback option 😄

**Review by niheaven — APPROVED** [review]

**Pull request merged**
