### PR TITLE
Waterfox: repair checkver and autoupdate

### LINKED ISSUE #14449: [Bug]: Waterfox autoupdate is not working
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

Waterfox

### Expected/Current Behaviour

Latest release is 6.5.1, but version here is still 6.0.20

### Steps to Reproduce

```console
compare version on their webpage with version in manifest
```

### Possible Solution

repair autoupdate

### Scoop and Buckets Version

```console
Current Scoop version:
859d1db5 (HEAD -> master, tag: v0.5.2, origin/master, origin/HEAD) chore(release): Bump to version 0.5.2 (#6080)

'main' bucket:
a28586c70 (HEAD -> master, origin/master, origin/HEAD) questdb: Update to version 8.2.0

'extras' bucket:
5a6a3405b (HEAD -> master, origin/master, origin/HEAD) netbird: Update to version 0.33.0

'java' bucket:
9df6fed3 (HEAD -> master, origin/master, origin/HEAD) temurin8-nightly-jre: Update to version 8.0.442-3.0.202411150650

'games' bucket:
2c1081ca7 (HEAD -> master, origin/master, origin/HEAD) rpcs3: Update to version 0.0.34-17141

'filip2cz_scoop-retro' bucket:
1d1a83e (HEAD -> master, origin/master, origin/HEAD) EDIT: Super Mario Land platform

'henshouse' bucket:
c2aa466 (HEAD -> master, origin/master, origin/HEAD) gurk: Update to version 0.5.2
```

### Scoop Config

```console
22.11.2024 20:55:45  True https://github.com/ScoopInstaller/Scoop master
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Additional Softwares

_No response_

### PR DESCRIPTION
**Pull request by filip2cz**
They removed G from new versions, so checkver and autoupdate was not working

Closes #14449 

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by filip2cz** [comment]
I believe that checkver is okay, based on output of github action: https://github.com/ScoopInstaller/Extras/actions/runs/11979739107/job/33402545169?pr=14450

**Comment by aliesbelik** [comment]
> I believe that checkver is okay, based on output of github action: https://github.com/ScoopInstaller/Extras/actions/runs/11979739107/job/33402545169?pr=14450

Guess this means that manifest could be updated first to the latest version.

Github link could be updated to the actual one - https://github.com/BrowserWorks/Waterfox - but this is not critical.

**Comment by filip2cz** [comment]
> Guess this means that manifest could be updated to the latest version first.

Sounds like I have to manualy update that manifest :(

**Comment by filip2cz** [comment]
> Github link could be updated to the actual one - https://github.com/BrowserWorks/Waterfox - but this is not critical.

looks like this was actually the issue at the end

**Pull request merged**
