### PR TITLE
teamspeak3: Update to Version 3.6.2

### PR DESCRIPTION
**Pull request by b4imetu**
Closes #XXXX

Relates to #XXXX

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by b4imetu** [comment]
/verify
teamspeak has now prioritized 5.00-beta on the Downloads Page and teamspeak3 on Archives. so I've removed Checkver and Autoupdate for now. If anyone would like to help me fix Checkver and Autoupdate I would appreciate it!

**Comment by b4imetu** [comment]
/verify
@chriba Thank you

**Comment by b4imetu** [comment]
> Hmm, apparently teamspeak doesn't like it when I access their file structure directly. As of today, only direct access to the files is allowed and not to the folder structure. However, the archive page still only offers an outdated version...

[pre_releases File Directory](https://files.teamspeak-services.com/pre_releases/client) is also no longer available. It was still available a few hours ago.
It seems that TeamSpeak wants everyone to go to the [Microsoft Store](https://apps.microsoft.com/detail/TeamSpeak/XPDCJ80KGNRVSS) and download their `teamspeak5-beta` version.

😓Or maybe they will fix the link to the file structure?

> Therefore my solution no longer works, I currently see no viable solution to fix this.

Thank you anyway😄

**Review by HUMORCE — APPROVED** [review]

**Pull request merged**
