### PR TITLE
vso-convertx-to-dvd: Add version 7.0.0.69

### PR DESCRIPTION
**Pull request by digrouz**

### CODE REVIEW

**Comment by Ash258** [comment]
I am not really fan of all these trials beign added to official bucket.

@r15ch13, @rasa Any idea how this could be handled. Easiest solution is just `trial` boolean property.

**Comment by digrouz** [comment]
I'm having my own complete license of thoses softwares, I'm just trying to have my full set of software available from scoop. I you say that thoses are not fitting the official repo, what I completely understand, I should create my own repo then.

I was mistaken by the LGPL file left in the folder after installation.

**Comment by digrouz** [comment]
is there a variable to manage the "7" in the autoupdate url ?

**Comment by Ash258** [comment]
See fixed manifest.

**Comment by digrouz** [comment]
sorry I did not saw because it was collapse.

**Comment by digrouz** [comment]
@Ash258 Do you want me to stop sending pr for softwares that requires a license to unlock full capabilities ?

**Comment by digrouz** [comment]
Hello, is there still any issue preventing the merge of this pull request?

**Comment by pratikpc** [comment]
Closing as branch has been deleted.

**Pull request closed without merging**
