### PR TITLE
office-tool-plus: Update to version 10.1.7.0 and add more architecture

### PR DESCRIPTION
**Pull request by StarsbySea**
- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by HUMORCE** [comment]
Use the zips that without runtime and suggests `windowsdesktop-runtime-lts`

**Comment by StarsbySea** [comment]
I think it would be better to provide a version that includes the runtime. Firstly, users may install the wrong runtime and the software will not work, and secondly, it is not a good idea to use administrator rights to install a runtime on the system in order to use a (non-administrative) tool.

**Comment by HUMORCE** [comment]
You are right, all program distributors want to integrate runtimes.

**Comment by HUMORCE** [comment]
The arm64 package does not exist in gh releases, currently.

**Review by HUMORCE — CHANGES_REQUESTED** [review]
10.1.7.1

**Review by HUMORCE — APPROVED** [review]

**Pull request merged**
