### PR TITLE
Fix thunderbird

### LINKED ISSUE #14123: [Bug]: "Unsupported version of Thunderbird", monthly release instead of ESR
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

thunderbird

### Expected/Current Behaviour

I have updated thunderbird to the latest scoop version (131.0) and thunderbird is showing this warning 

Everything seems to work fine but I wanted to report that.

### Steps to Reproduce

```console
PS> scoop update thunderbird
thunderbird: 128.2.3esr -> 131.0
Updating one outdated app:
Updating 'thunderbird' (128.2.3esr -> 131.0)
Downloading new version
Thunderbird%20Setup%20131.0.exe (64,1 MB) [===================================================================] 100%
Checking hash of Thunderbird%20Setup%20131.0.exe ... ok.
Uninstalling 'thunderbird' (128.2.3esr)
Removing shim 'thunderbird.shim'.
Removing shim 'thunderbird.exe'.
Unlinking ~\scoop\apps\thunderbird\current
Installing 'thunderbird' (131.0) [64bit] from 'extras' bucket
Loading Thunderbird%20Setup%20131.0.exe from cache
Extracting Thunderbird%20Setup%20131.0.exe ... done.
Linking ~\scoop\apps\thunderbird\current => ~\scoop\apps\thunderbird\131.0
Creating shim for 'thunderbird'.
Making C:\Users\XXX\scoop\shims\thunderbird.exe a GUI binary.
Creating shortcut for Thunderbird (thunderbird.exe)
Creating shortcut for Thunderbird Profile Manager (thunderbird.exe)
Persisting distribution
Persisting profile
Running post_install script...done.
'thunderbird' (131.0) was installed successfully!
Notes
-----
To set profile 'Scoop' as *DEFAULT*, or profiles/settings was lost after update:
- Run 'Thunderbird Profile Manager', choose 'Scoop' then click 'Start Thunderbird'.
- Visit 'about:profiles' page in Thunderbird to check *DEFAULT* profile.
For details: https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-thunderbird-profiles
```

### Possible Solution

N/A

### Scoop and Buckets Version

```console
Current Scoop version:
859d1db5 (HEAD -> master, tag: v0.5.2, origin/master, origin/HEAD) chore(release): Bump to version 0.5.2 (#6080)

'main' bucket:
14315f722 (HEAD -> master, origin/master, origin/HEAD) trivy: Update to version 0.56.0

'extras' bucket:
c4994f2c2 (HEAD -> master, origin/master, origin/HEAD) github@3.4.6: Fix hash (Closes #14122)

'versions' bucket:
479f81841 (HEAD -> master, origin/master, origin/HEAD) rstudio-daily: Update to version 2024.11.0-daily-261

'nirsoft' bucket:
c880857 (HEAD -> master, origin/master, origin/HEAD) Update url list [ci skip]

'sysinternals' bucket:
6b2b695 (HEAD -> main, origin/main, origin/HEAD) sysmon: Update to version 15.15

'nonportable' bucket:
0915334 (HEAD -> master, origin/master, origin/HEAD) grammarly-np: Update to version 1.2.103.1485

'java' bucket:
df0876ff (HEAD -> master, origin/master, origin/HEAD) intellij-jbr21: Update to version 21.0.4-b613.2
```

### Scoop Config

```console
last_update         scoop_branch scoop_repo
-----------         ------------ ----------
03/10/2024 14:02:23 master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.4.5
PSEdition                      Core
GitCommitId                    7.4.5
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Additional Softwares

_No response_

### PR DESCRIPTION
**Pull request by desk7**
Update thunderbird to the latest ESR version.
Maybe a new manifest thunderbird-esr could be created.

Closes #14123

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Vishal-h-s** [comment]
im a beginner in my UG. we might need a script for this to fetch version and hash and replace in the url https://archive.mozilla.org/pub/thunderbird/releases/$version/win64/en-US/Thunderbird%20Setup%20$version.exe#/dl.7z  and and yes the checkver needs to be updated too but scoop dosent seem to run it before installing the app. maybe ill wait for this to be solved until then use a website

**Comment by Vishal-h-s** [comment]
one last mistake didnt add esr before /win64/en-US/Thunderbird%20Setup%20128.3.1esr.exe#/dl.7z  and it works for me thank you. so upon running update checkver will be used right.

**Comment by aliesbelik** [comment]
I guess it makes sense the same schema for firefox manifests (as already pointed in https://github.com/ScoopInstaller/Extras/issues/13633#issuecomment-2231706692):
 - create separate `thunderbird-esr` manifest here in Extras (pointing to the [latest ESR version (`THUNDERBIRD_ESR`)](https://product-details.mozilla.org/1.0/thunderbird_versions.json) - 128.3.1esr at the moment);
 - leave `thunderbird` manifest pointing to the [latest stable version (`LATEST_THUNDERBIRD_VERSION`)](https://product-details.mozilla.org/1.0/thunderbird_versions.json) - 131.0.1 at the moment).

**Comment by aliesbelik** [comment]
Closing in favor of #14233.

**Pull request closed without merging**
