### PR TITLE
responsively: Update to version 1.1.0

### PR DESCRIPTION
**Pull request by StarsbySea**
and fix autoupdate ...

- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by jasongodev — CHANGES_REQUESTED** [review]
Add a checkver routine. Check this documentation: https://scoop-docs.vercel.app/docs/concepts/App-Manifest-Autoupdate.html#adding-checkver-to-a-manifest

**Comment by StarsbySea** [comment]
> Add a checkver routine. Check this documentation: https://scoop-docs.vercel.app/docs/concepts/App-Manifest-Autoupdate.html#adding-checkver-to-a-manifest

Why? Is it good enough to use the GitHub repository tag/release number extraction feature that comes with scoop?

**Comment by jasongodev** [comment]
> > Add a checkver routine. Check this documentation: https://scoop-docs.vercel.app/docs/concepts/App-Manifest-Autoupdate.html#adding-checkver-to-a-manifest
> 
> Why? Is it good enough to use the GitHub repository tag/release number extraction feature that comes with scoop?

Does responsively follow semver without using non-numerics like 1.0.0-rc3? If so then the native github detection is enough.

**Comment by StarsbySea** [comment]
> > > Add a checkver routine. Check this documentation: https://scoop-docs.vercel.app/docs/concepts/App-Manifest-Autoupdate.html#adding-checkver-to-a-manifest
> > 
> > 
> > Why? Is it good enough to use the GitHub repository tag/release number extraction feature that comes with scoop?
> 
> Does responsively follow semver without using non-numerics like 1.0.0-rc3? If so then the native github detection is enough.

Judging from the recent tag, the version number of the app should be in line with the rules.

**Review by jasongodev — APPROVED** [review]
This installed correctly. Merge can be done safely.

**Pull request merged**
