### PR TITLE
powertoys@0.64.0: Fix DLL hardlinks

### LINKED ISSUE #9643: PowerToys 0.64.0 doesn't work properly
## Bug Report

**Package Name:** powertoys

### Current Behaviour

A couple modules won't run properly.

### Expected Behaviour

All modules should run.

### Additional context/output

DLL files are now hardlinked into subfolders after this commit: https://github.com/microsoft/PowerToys/commit/db191b8b75ad456d5eb94eaa0aa0c7b59ecec900 .

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 7.2.7

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
{
  "last_update": "2022-11-03T12:56:10.2105809+08:00",
  "scoop_repo": "https://github.com/ScoopInstaller/Scoop",
  "scoop_branch": "master"
}
```

### PR DESCRIPTION
**Pull request by raycheung**
Closes #9643 

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by niheaven — APPROVED** [review]

**Comment by jaimecbernardo** [comment]
Hi @raycheung ,
Are you the one maintaining this package?
As a heads-up, PowerToys 0.66 will come with new hardlink files, due to .net now being self-contained, so we're shipping the dlls as well.
https://github.com/microsoft/PowerToys/commit/6ac508fb933d0a30e1176baae34981f91e0984cf

These are defined in DotnetRuntimeWPFFiles and DotnetRuntimeFiles in the wxs.
Is there a way to stop scoop from updating to 0.66 until these are changed?

**Comment by raycheung** [comment]
Hi @jaimecbernardo,
I'm not the maintainer but I love using the PowerToys and having it installed via scoop.
Let me check how to make it compatible with 0.66 as well, thanks for the heads-up.

**Comment by jaimecbernardo** [comment]
I've opened an issue to remove auto-updating from the PowerToys manifest for the time being, since it can't be updated automatically: https://github.com/ScoopInstaller/Extras/pull/10177

**Comment by jaimecbernardo** [comment]
@raycheung , Thanks for keeping this up to date. Regarding 0.66:
https://github.com/microsoft/PowerToys/commit/6ac508fb933d0a30e1176baae34981f91e0984cf#diff-c502a81cdf8afa7a38f0f462709abcdbdfcc44beaa6227a1e64a26566c7e8876

It might be enough to add FileExplorerPreview to the files copied for interop:
image

And then also copy from dll\\dotnet to the modules that are using the dotnet dependencies:
image

I assume that will include the WPF files as well. It's a little more than needed for non-WPF apps, but I guess it'll do little harm, since both Dotnet and dotnetwpf are coming from dll\dotnet.

I still think it's best to remove auto-update for PowerToys in Scoop, though, since this likely has to be tested before released in Scoop.

Hope this is helpful.

**Pull request merged**
