### PR TITLE
opera-gx: update to v106.0.4998.49

### LINKED ISSUE #12628: [Bug]: Opera(-GX) stopped updating
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

opera & opera-gx

### Expected/Current Behaviour

Version 99.0.4788 has been the last available version for both Opera and Opera GX on Scoop, which is 8 months or 7 major releases old.

Is this possibly caused by the version list on https://get.opera.com/ftp/pub/opera/desktop/ being sorted alphabetically, i.e. version 99.x is at the bottom of the list, while version numbers > 100 are at the top?

### Steps to Reproduce

```console
Go to https://scoop.sh/#/apps?q=opera and see that v.99.0.4788 are the latest version for both Opera and Opera GX.
Go to https://get.opera.com/ftp/pub/opera/desktop/ and see many newer versions are available.
```

### Possible Solution

Maybe fix the update checker?

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
05d72446b (HEAD -> master, origin/master, origin/HEAD) ALIEN: Add version 4.4.1 (#12240)

'java' bucket:
659193d1 (HEAD -> master, origin/master, origin/HEAD) temurin17-nightly-jre: Update to version 17.0.10-6.0.202401141608

'KnotUntied_scoop-fonts' bucket:
3afd358 (HEAD -> master, origin/master, origin/HEAD) sudo: Update to version 0.81

'main' bucket:
b339555f8 (HEAD -> master, origin/master, origin/HEAD) vale: Update to version 3.0.5

'nerd-fonts' bucket:
1cde6b3 (HEAD -> master, origin/master, origin/HEAD) GlowSansSC-Normal: Update to version 0.92

'versions' bucket:
923bdacc4 (HEAD -> master, origin/master, origin/HEAD) vscode-insiders: Update to version 1.86.0-insider+1705381544416
```

### Scoop Config

```console
last_update         scoop_branch scoop_repo
-----------         ------------ ----------
16/01/2024 12:00:14 master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Additional Softwares

_No response_

### PR DESCRIPTION
**Pull request by amreus**
* updated checkver regex to only match versions starting with 3-digits.
* update manifest to latest version

Closes #12628

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by amreus** [comment]
Oops, 37 minutes late to the party. @danielpauldd just made a request.

**Comment by danielpauldd** [comment]
Hello @amreus, the PR #12206 only fixes the opera manifest (tbh I wasn't aware of opera-gx before). 
I think you should reopen your PR and also link it to issue https://github.com/ScoopInstaller/Extras/issues/12628

**Comment by amreus** [comment]
Yeah it was a little confusing.  I am going to copy your manifest and adopt it to opera-gx since it has the same problem with the order of the version list. Thank you.

**Comment by amreus** [comment]
* Use a script for checking version due to download page sorting alphebetically instead of by version.
* Updated the manifest based on @danielpauldd's version

**Comment by danielpauldd** [comment]
Just to have everything right, the PR and the code changes including the checkver part is from @gigabotan
I only reviewed the manifest and linked it to the current issue.

**Pull request merged**
