### PR TITLE
novelwriter: Add version 2.5.3

### LINKED ISSUE #11168: [Request]: Add novelWriter
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

novelWriter

### Description

A markdown-like text editor designed for writing novels and larger projects of many smaller plain text documents.  It is designed to be a simple text editor that allows for easy organisation of text files and notes, with a meta data syntax for comments, synopsis, and cross-referencing between files, and built on plain text files for robustness.

### Homepage

https://novelwriter.io/

### Download Link(s)

https://github.com/vkbo/novelWriter/releases

### Some Indication of Popularity/Repute

Over 1.5k stars on GitHub.

### PR DESCRIPTION
**Pull request by teppos**
Add novelwriter version 2.5.2

Closes #11168

- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aliesbelik** [comment]
```
λ strings .\novelwriter-2.5.2-amd64-setup.exe | grep Inno
InnoSetupLdrWindow
Inno Setup Setup Data (6.3.0)
```

Please replace custom installer steps with innosetup (`"innosetup": true`).
See e.g. [scoop-lemon/novelwriter](https://github.com/hoilc/scoop-lemon/blob/master/bucket/novelwriter.json) for reference.

**Comment by teppos** [comment]
Changed to innosetup-based installer.

**Pull request merged**
