### PR TITLE
selene-light: Add version 0.19.1

### PR DESCRIPTION
**Pull request by sitiom**
Selene without Roblox-tailored lints.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
Is there any significant advantage of the light version? There isn't too much difference in size and I'd prefer to keep just one package (which has all features/lints).

**Comment by sitiom** [comment]
> Is there any significant advantage of the light version? There isn't too much difference in size and I'd prefer to keep just one package (which has all features/lints).

Other than no Roblox lints, it's just the same. The light version is built with `--no-default-features`, and is almost half the full version's size. Maybe we can just provide `selene-light` as an option?

**Comment by rashil2000** [comment]
> The light version is built with `--no-default-features`, and is almost half the full version's size. 

Yeah, but they're both less than 3 MB so size is not a factor here.

> Maybe we can just provide `selene-light` as an option?

I didn't get you?

**Comment by sitiom** [comment]
Makes sense, they are almost identical and both are small in size. The developer plans to expand selene with more features only available in the full version, but that's for a future time. We could add it here at a later time when it makes sense.

**Pull request closed without merging**
