### PR TITLE
pragtical: Add version 3.4.2

### LINKED ISSUE #13764: [Request]: Pragtical
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

Pragtical

### Description

The practical and pragmatic code editor, a fork of lite-xl.

### Homepage

https://pragtical.dev/

### Download Link(s)

https://github.com/pragtical/pragtical/releases

### Some Indication of Popularity/Repute

This is a fork of `lite-xl`which itself is a fork of the text editor `lite`. Lite-xl has ~4.6k stars currently. Pragtical aims to add new features and improve performance of lite-xl.

lite-xl -> https://github.com/lite-xl/lite-xl
lite -> https://github.com/rxi/lite

### PR DESCRIPTION
**Pull request by AmerM137**
pragtical: Add version 3.4.1

Closes #13764

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aliesbelik** [comment]
No data/configuration to [persist](https://github.com/ScoopInstaller/Scoop/wiki/Persistent-data)?

**Comment by AmerM137** [comment]
No data/configuration to persist needed. AFAIK, whatever is needed for persistence across installs is under ~/.config/pragtical.

**Comment by AmerM137** [comment]
Friendly bump, is there anything blocking this currently?

**Pull request merged**
