### PR TITLE
miniconda3: rename to miniconda and update to 23.11.0-2

### PR DESCRIPTION
**Pull request by b4imetu**
Closes #XXXX

Relates to #XXXX

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by b4imetu** [comment]
@niheaven 
please review and merge #12666 and #12817 
thankyou!

**Comment by niheaven** [comment]
The renaming is not needed imo, and #12817 was merged.

This should be closed now.

**Pull request closed without merging**
