### PR TITLE
userbenchmark: Add version 3.5.5.0

### LINKED ISSUE #9708: [Request] Add UserBenchmark
## Package Request

I have a PR for this package, I will submit it shortly.  If there is a better bucket to host this package, please let me know.

### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [x] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [x] the latest stable version of the program

### Information

**Name:** UserBenchmark

**Description:** Speed test your PC in less than a minute.

**Homepage:** https://www.userbenchmark.com/

**Download link(s):** https://www.userbenchmark.com/resources/download/UserBenchmarkInstaller.exe

**Some indication of popularity/repute:** Over 250 million benchmark runs have been uploaded to UserBenchmark.  See: https://www.userbenchmark.com/page/about

### PR DESCRIPTION
**Pull request by TonyApuzzo**
Closes #9708

I don't have a good way of figuring out what the version number is so it is hard to set up the auto-update. I'm happy to get advice on how to implement version checking.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Zliced13** [comment]
You can use these websites for your checkver:

https://userbenchmark.en.uptodown.com/windows/versions
https://www.majorgeeks.com/files/details/userbenchmark.html

And if you need help with creating a regular expression check out these links below:
https://wikiless.org/wiki/Regular_expression?lang=en#Character_classes
https://regex-generator.olafneumann.org

**Comment by Zliced13** [comment]
The Scoop wiki also has examples of how you would create a checkver for a manifest, please see: 
https://github.com/ScoopInstaller/Scoop/wiki/App-Manifest-Autoupdate#adding-checkver-to-a-manifest

**Comment by Zliced13** [comment]
Hey do you still need help, or are you doing alright with the manifest?

**Comment by TonyApuzzo** [comment]
Unfortunately, I can't find the version# or a hash on the UserBenchmark site itself. 

I followed your advice and updated the checkver and autoupdate based on the uptodown site -- but I am using the original site for the actual download, which could cause a hash mismatch when the main site updates while the uptodown hasn't been updated yet.  If we want to completely trust uptodown, then we could just use their downloads completely and would probably avoid some temporary errors.

**Comment by Zliced13** [comment]
Do what you think will create fewer errors in the future for the manifest.

**Comment by Zliced13** [comment]
www.FileHorse.com seems to be the only reliable checkver I could find that keeps up-to-date with the latest version.

**Review by HUMORCE — APPROVED** [review]

**Pull request merged**
