### PR TITLE
speccy: Update to version 1.32.803 and add autoupdate

### PR DESCRIPTION
**Pull request by brian6932**
- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by jasongodev — APPROVED** [review]
The autoupdate routine works. Merge can be done safely.

In this powershell session, I simulated an old version number BUT used the proposed autoupdate code. The checkver.ps1 recognized the old and the new version then auto updates the manifest file accordingly. The `scoop cat speccy` of old and new manifest is shown here.

```powershell
PS C:\Users\jason\scoop\apps\scoop\current> scoop cat speccy
{
    "version": "1.32.700",
    "description": "Fast, lightweight, advanced system information tool for your PC.",
    "homepage": "https://www.ccleaner.com/speccy",
    "license": "Freeware",
    "url": "https://download.ccleaner.com/spsetup132.exe#/dl.7z",
    "hash": "0a9e739910578192e2ad3f8f805a863d5cbcacbc38cde6488d7bbef5395dba87",
    "architecture": {
        "64bit": {
            "bin": [
                [
                    "Speccy64.exe",
                    "Speccy"
                ]
            ],
            "shortcuts": [
                [
                    "Speccy64.exe",
                    "Speccy"
                ]
            ]
        },
        "32bit": {
            "bin": "Speccy.exe",
            "shortcuts": [
                [
                    "Speccy.exe",
                    "speccy"
                ]
            ]
        }
    },
    "pre_install": [
        "Set-Content \"$dir\\portable.dat\" '#PORTABLE#' -Encoding ASCII",
        "'$*', 'uninst.exe', \"Speccy$(if ($architecture -eq '32bit') { '64' }).exe\" | ForEach-Object { Remove-Item -Recurse -Force \"$dir\\$_\" }",
        "if(!(Test-Path \"$persist_dir\\Speccy.ini\")) {",
        "   Set-Content \"$dir\\Speccy.ini\" (@('[Software\\Piriform\\Speccy]', 'NeedUpdate=0') -join \"`r`n\") -Encoding ASCII",
        "}"
    ],
    "persist": "Speccy.ini",
    "checkver": {
        "url": "https://www.ccleaner.com/speccy/version-history",
        "regex": ">v([\\d.]+)<"
    },
    "autoupdate": {
        "url": "https://download.ccleaner.com/spsetup$majorVersion$minorVersion.exe#/dl.7z"
    }
}
PS C:\Users\jason\scoop\apps\scoop\current> ./bin/checkver.ps1 speccy -Update -Dir "C:\Users\jason\scoop\buckets\extras\bucket\"
speccy: 1.32.803 (scoop version is 1.32.700) autoupdate available
Autoupdating speccy
Downloading spsetup132.exe to compute hashes!
Loading spsetup132.exe from cache
Computed hash: 0a9e739910578192e2ad3f8f805a863d5cbcacbc38cde6488d7bbef5395dba87
Writing updated speccy manifest
PS C:\Users\jason\scoop\apps\scoop\current> scoop cat speccy
{
    "version": "1.32.803",
    "description": "Fast, lightweight, advanced system information tool for your PC.",
    "homepage": "https://www.ccleaner.com/speccy",
    "license": "Freeware",
    "url": "https://download.ccleaner.com/spsetup132.exe#/dl.7z",
    "hash": "0a9e739910578192e2ad3f8f805a863d5cbcacbc38cde6488d7bbef5395dba87",
    "architecture": {
        "64bit": {
            "bin": [
                [
                    "Speccy64.exe",
                    "Speccy"
                ]
            ],
            "shortcuts": [
                [
                    "Speccy64.exe",
                    "Speccy"
                ]
            ]
        },
        "32bit": {
            "bin": "Speccy.exe",
            "shortcuts": [
                [
                    "Speccy.exe",
                    "speccy"
                ]
            ]
        }
    },
    "pre_install": [
        "Set-Content \"$dir\\portable.dat\" '#PORTABLE#' -Encoding ASCII",
        "'$*', 'uninst.exe', \"Speccy$(if ($architecture -eq '32bit') { '64' }).exe\" | ForEach-Object { Remove-Item -Recurse -Force \"$dir\\$_\" }",
        "if(!(Test-Path \"$persist_dir\\Speccy.ini\")) {",
        "   Set-Content \"$dir\\Speccy.ini\" (@('[Software\\Piriform\\Speccy]', 'NeedUpdate=0') -join \"`r`n\") -Encoding ASCII",
        "}"
    ],
    "persist": "Speccy.ini",
    "checkver": {
        "url": "https://www.ccleaner.com/speccy/version-history",
        "regex": ">v([\\d.]+)<"
    },
    "autoupdate": {
        "url": "https://download.ccleaner.com/spsetup$majorVersion$minorVersion.exe#/dl.7z"
    }
}
```

**Comment by niheaven** [comment]
I'm not sure why autoupdate is removed, so wait for someone known.

**Comment by brian6932** [comment]
Well it was updated enough to where the ver info was out of date. So imo, it should have it.

**Review by StarsbySea — APPROVED** [review]

**Pull request merged**
