### PR TITLE
ubports-installer: Add version 0.9.1-beta

### PR DESCRIPTION
**Pull request by issaclin32**
Supersedes #5199. (see old PR for more details)

upstream discussion: https://github.com/ubports/ubports-installer/issues/1592

### CODE REVIEW

**Review by rashil2000 — APPROVED** [review]

**Comment by niheaven** [comment]
There're some CR/LF error...

**Comment by rashil2000** [comment]
Yeah, I ran into it too, not sure how the CI missed it

**Comment by issaclin32** [comment]
> Yeah, I ran into it too, not sure how the CI missed it

Can you show me where the error is? Sorry I am a noob :sweat:

**Comment by rashil2000** [comment]
When you do `git pull`, it shows bucket/ubports-installer.json as modified. But you can't restore it or change it. `git diff` also doesn't show anything. 
Then we have to run `git rm gitattributes; git add -A; git reset --hard` to solve the error.

**Comment by issaclin32** [comment]
Fixed in https://github.com/ScoopInstaller/Extras/commit/11c4a1a1d63e4cdaad837d551bbc578bcb8f9263 and https://github.com/ScoopInstaller/Extras/commit/15d23a535f1a0f380cdffd73fde45aad230ff4b1

**Pull request merged**
