### PR TITLE
wezterm-nightly: Add manifest

### PR DESCRIPTION
**Pull request by rashil2000**
Daily builds of Wezterm emulator.

Manifest inspired by https://github.com/ScoopInstaller/Extras/blob/master/bucket/rust-nightly.json

### CODE REVIEW

**Comment by pratikpc** [comment]
@rashil2000 I personally think we should not add more nightlies to extras.

Not till excavator issues are fixed at least.

**Comment by rashil2000** [comment]
Nightlies are not affected by Excavator, Excavator skips these manifests. So no issues there.

**Comment by pratikpc** [comment]
@rashil2000 so how are these updated then?

This for example cannot update

**Comment by pratikpc** [comment]
@rashil2000 I do believe we should add new nightlies to https://github.com/ScoopInstaller/Nightlies only.

**Comment by rashil2000** [comment]
They don't update. Manifests like rust-nightly do not update - they just download the latest nightly available at the time of installation. Because we can't keep track of non-versioned hashes daily.

**Comment by rashil2000** [comment]
The Nightlies bucket has been deprecated :)

**Comment by pratikpc** [comment]
> They don't update. Manifests like rust-nightly do not update - they just download the latest nightly available at the time of installation.

That does not sound like something I can agree with.

This would mean a Scoop user would have to manually perform re-installs whenever new nightlies come out and would have to manually update.

@rashil2000 if this is the case, as far as I can see, with excavator not running on nightlies bucket, we should move this PR there.

**Comment by pratikpc** [comment]
@rashil2000 in that case we should bring it back to supported state right?

It's not like it would involve much effort to maintain or support.

Nightlies is till present in bucket.json so am not sure how deprecated it is.

https://github.com/ScoopInstaller/Scoop/blob/master/buckets.json#L5

**Comment by rashil2000** [comment]
> This would mean a Scoop user would have to manually perform re-installs whenever new nightlies come out and would have to manually update.

If a user is downloading a nightly build, it's a fair assumption that they are aware of this.

Regarding the nightlies bucket, you can refer to the discussion here - https://github.com/ScoopInstaller/Extras/issues/2821

If we are to revive it, we will need to transfer 8 manifests from the Main bucket and 3 (+1 this one) manifests from the Extras bucket there

**Comment by pratikpc** [comment]
> If we are to revive it, we will need to transfer 8 manifests from the Main bucket and 3 (+1 this one) manifests from the Extras bucket there

Or we could just add new PRs there while letting the old PRs remain here on account of age.

> If a user is downloading a nightly build, it's a fair assumption that they are aware of this.

I don't think that would be the case.

**Comment by pratikpc** [comment]
But if we add it to a nightlies bucket and make it clear how nightlies work currently in Scoop, that would be a lot more clearer.

**Comment by rashil2000** [comment]
> But if we add it to a nightlies bucket and make it clear how nightlies work currently in Scoop, that would be a lot more clearer.

Yeah that will be better

**Comment by niheaven** [comment]
Maybe consider add it to https://github.com/ScoopInstaller/Versions if there is a `wezterm` already in `extras`?

**Comment by rashil2000** [comment]
Isn't the Versions bucket for older and frozen packages?

I don't feel a nightly would fit there.

**Comment by niheaven** [comment]
📦 A Scoop bucket for alternative versions of apps.

**Comment by rashil2000** [comment]
I think we can aim for a more granular approach to buckets:

Versions - frozen versions, older versions, previews, derived apps

Nightlies - apps that update daily

**Pull request closed without merging**
