### PR TITLE
Add bloop 0.3.3

### PR DESCRIPTION
**Pull request by Slach**
Bloop - fast code search engine written in Rust.

### CODE REVIEW

**Review by jasongodev — APPROVED** [review]

**Comment by Slach** [comment]
@jasongodev if everything looks good why it not merged?

**Comment by jasongodev** [comment]
> @jasongodev if everything looks good why it not merged?

I only volunteer to review. It's up to the maintainers to merge or not.

**Comment by Slach** [comment]
@jasongodev 
ooh, sorry, didn't know

**Review by HUMORCE — APPROVED** [review]
Tested

**Comment by redactedscribe** [comment]
@Slach The manifest appears to be broken. I just installed Bloop and even though Scoop reports v0.3.4, what's downloaded is v0.3.2 ...not even v0.3.3.

```
Installing 'bloop' (0.3.4) [64bit] from extras bucket
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 52b125|OK  |   4.9MiB/s|D:/Scoop/cache/bloop#0.3.4#https_github.com_BloopAI_bloop_releases_download_v0.3.2_bloop_0.3.2_x64_en-US.msi
Download: Status Legend:
Download: (OK):download completed.
Checking hash of bloop_0.3.2_x64_en-US.msi ... ok.
Extracting bloop_0.3.2_x64_en-US.msi ... done.
Linking D:\Scoop\apps\bloop\current => D:\Scoop\apps\bloop\0.3.4
Creating shim for 'bloop'.
Creating shortcut for bloop (bloop.exe)
'bloop' (0.3.4) was installed successfully!
```

Perhaps this bug something to do with [v0.3.4 not having a Windows build yet](https://github.com/BloopAI/bloop/releases/tag/v0.3.4)?

**Pull request merged**
