### PR TITLE
clash-nyanpasu: Add Version 1.5.1

### LINKED ISSUE #12901: [Request]: clash-nyanpasu
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [x] Full version (i.e. not a trial version)
- [x] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

clash-nyanpasu

### Description

A Clash GUI based on Tauri

### Homepage

https://nyanpasu.elaina.moe/

### Download Link(s)

https://github.com/LibNyanpasu/clash-nyanpasu/releases

### Some Indication of Popularity/Repute

4.8k Stars

### PR DESCRIPTION
**Pull request by b4imetu**
Closes #12901

Relates to #XXXX

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by b4imetu** [comment]
@aliesbelik @HUMORCE @StudentWeis 
please review ^^

**Comment by b4imetu** [comment]
please review ^^ thanks @aliesbelik @StudentWeis @HUMORCE

**Review by HUMORCE — APPROVED** [review]

**Pull request merged**
