### PR TITLE
imo: Update to version 1.4.2.1

### PR DESCRIPTION
**Pull request by SonaliBendre**
Closes #XXXX

Relates to #XXXX

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SonaliBendre** [comment]
@issaclin32 I fixed checkver

**Comment by SonaliBendre** [comment]
```Installing 'imo-messenger' (1.4.2.1) [64bit] from extras bucket
Loading ImoSetup_1.4.2.1_Release.exe from cache.
Checking hash of ImoSetup_1.4.2.1_Release.exe ... ok.
Running pre_install script...
ERROR Exit code was 5!
ERROR Exit code was 1622!
Failed to extract files from ~\scoop\apps\imo-messenger\1.4.2.1\extract\AttachedContainer\ImoInstaller.msi.
Log file:
  ~\scoop\apps\imo-messenger\1.4.2.1\extract\AttachedContainer\msi.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=imo-messenger%401.4.2.1%3a+decompress+error
```

**Comment by tech189** [comment]
I get the same error and the extract folder is empty so I can't read that log file...

**Comment by issaclin32** [comment]
There are 2 problems being fixed in that `fix extraction` commit:
* A recent change in Scoop core (https://github.com/ScoopInstaller/Scoop/pull/5065) breaks the compatibility, so we need to remove literal quotes from the arguments.
* *imo* is currently at version **1.4.2.1**, but the file contained in the MSI installer is `imo\1.4.2.0` (I think there is a mistake when they packed the installer). Therefore we need to use wildcards (`*`) as a workaround.

**Comment by issaclin32** [comment]
Our bots have problem accessing the checkver page `https://imo.im/win/Version.txt`

**Comment by SonaliBendre** [comment]
@issaclin32 digitatrend js doesn't work. can you find a workaround for https://imo.im/win/Version.txt like proxy, etc.?

**Comment by SonaliBendre** [comment]
@issaclin32 https://womginx.arph.org/main/https://imo.im/win/Version.txt

**Comment by SonaliBendre** [comment]
@issaclin32 can bot access this url?

**Comment by issaclin32** [comment]
> @issaclin32 digitatrend js doesn't work.

The page have JS generated content, but the version is in the non-JS part, so it will work for *checkver*. At least the test results proved it.

> can you find a workaround for https://imo.im/win/Version.txt like proxy, etc.?

It is possible to implement something like that in **checkver script**, but I don't think it is necessary for now.


> @issaclin32 https://womginx.arph.org/main/https://imo.im/win/Version.txt
@issaclin32 can bot access this url?

Sadly not. The content literally shows up as `<script>location.href="/womginxaddcookie/"+Date.now()+"/"+location.href</script>`

**Comment by rihaq** [comment]
@issaclin32 it'll sure work https://womginx-proxy.herokuapp.com/main/https://imo.im/win/Version.txt

**Pull request merged**
