### PR TITLE
weasel: Add version 0.14.3

### LINKED ISSUE #3665: [Request] Add Rime Input Method Engine
Could you please add Rime Input Method Engine to the bucket? You could find more information on https://rime.im/ and https://github.com/rime/weasel

### PR DESCRIPTION
**Pull request by igaryhe**
Closes #3665

### CODE REVIEW

**Comment by rashil2000** [comment]
Link to English docs?

**Comment by igaryhe** [comment]
I'm afraid there isn't an English doc for weasel. The only English resource I could find is the [librime](https://github.com/rime/librime) repo, and weasel is just a Windwos front-end of it. It's a input method engine made by Chinese and mainly targeting Chinese speakers.

**Comment by rashil2000** [comment]
Then this faces the same problem as https://github.com/ScoopInstaller/Main/pull/2938#issuecomment-966830432

**Comment by igaryhe** [comment]
this looks fairly reasonable to me, feel free to close it

**Comment by issaclin32** [comment]
**Weasel** is a fairly wide-used Chinese IME tool. It's a pity that we cannot add it.
However, I still think we should keep the rules. Otherwise we would have to accept softwares in **Japanese, Vietnamese, Hindi, Russian,** etc.

You can use [my version of the manifest](https://github.com/issaclin32/scoop-bucket/blob/master/bucket/weasel.json) by:
```
scoop bucket add issaclin32 https://github.com/issaclin32/scoop-bucket
scoop install weasel
```

Or simply [start your own bucket](https://github.com/rasa/GenericBucket).

**Pull request closed without merging**
