### PR TITLE
syncthingtray: fix config persist

### PR DESCRIPTION
**Pull request by qianlongzt**
fix config file syncthingtray.ini persist
- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Higramx** [comment]
I think what's preferable is making the symlink:
```
"if (!(Test-Path \"$persist_dir\\$config\")) { New-Item \"$persist_dir\\$config\" -ItemType File | Out-Null }",
"New-Item -Type SymbolicLink -Value $persist_dir\\$config -Path $dir\\$config | Out-Null"
```
and removing the "move-item" parts.
I also assume the "ensure" things aren't necessary (in that case).

**Comment by qianlongzt** [comment]
Yes, I tested the symlink, and it works correctly. It does not delete the symlink; it deletes the target file and recreates it in the target location. `ensure` is still necessary, or an error might occur.

But symlink need administrator privilege

image

**Comment by Higramx** [comment]
Does persist not require admin privilege? I have not tested without.

**Comment by qianlongzt** [comment]
hard link and junction: normal user
symlink: admin or enable developer mode

https://github.com/ScoopInstaller/Scoop/blob/859d1db51bcc840903d5280567846ae2f7207ca2/lib/diagnostic.ps1#L59

**Comment by Higramx** [comment]
ok thanks

**Pull request merged**
