### PR TITLE
tinymediamanager add autoupdate

### PR DESCRIPTION
**Pull request by kkzzhizhou**
Closes #XXXX

Relates to #XXXX

### CODE REVIEW

**Comment by rashil2000** [comment]
You accidentally made a commit here. Please revert it.

**Comment by rashil2000** [comment]
Update the manifest to latest version, and add architecture block.

**Comment by issaclin32** [comment]
I appreciate your effort, but you should delete `lockhunter.json` from your PR, and send another PR for that. 

Otherwise it will be really messy when we  check manifest history in the future.

**Comment by rashil2000** [comment]
They opened another PR already https://github.com/ScoopInstaller/Extras/pull/7524

**Comment by issaclin32** [comment]
> They opened another PR already #7524

I see.

**Pull request closed without merging**
