### PR TITLE
spotube: Fix `autoupdate.url` and `autoupdate.hash.regex`

### LINKED ISSUE #9539: The app manifest of Spotube doesn't implement auto-update correctly
## Bug Report

**Package Name:** Spotube

### Current Behaviour

The current app manifest of the package [https://github.com/ScoopInstaller/Extras/blob/master/bucket/spotube.json] doesn't implement auto-update correctly because of the following reasons:
1) The URL in autoupdate is referencing a static version: v2.3.0, which makes auto-update malfunction and always set the download version in the URL to v2.3.0.
2) The Hash Regex in autoupdate references a static hash (Which I believe is the hash of v2.3.0) which makes the regex not work in newer versions. I tried to make a regex that would work for all versions but I'm not too good at regex so I couldn't do it.

### Expected Behaviour

Auto-update should work.

### Additional context/output

None

### Possible Solution

1) The URL in autoupdate should be replaced with the following: ``https://github.com/KRTirtho/spotube/releases/download/v$version/Spotube-windows-x86_64-setup.exe``.
2) The Hash Regex in autoupdate shouldn't reference a static hash since the hash changes in every update.

### System details

System details are not relevant to the bug.

### PR DESCRIPTION
**Pull request by Zliced13**
Closes #9539

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by M6HqVBcddw2qaN4s** [comment]
@Zliced13 Correct me if I'm wrong, but the hash regex still references a static hash which wouldn't work with newer versions?

**Comment by Zliced13** [comment]
No it will work just, fine. Did you look at the feedback the bot gave above?

**Comment by M6HqVBcddw2qaN4s** [comment]
@Zliced13 Just tested if it would be able to get the hash from v2.5.0's SHA256sum and it doesn't.
https://user-images.githubusercontent.com/61710729/197376113-45349f94-90e1-452d-85b8-338a5656944a.png

**Comment by Zliced13** [comment]
@M6HqVBcddw2qaN4s you were right, I looked at the manifest again and fixed the `autoupdate.hash.regex`

**Review by HUMORCE — APPROVED** [review]

**Pull request merged**
