### PR TITLE
mp3tag: Update the manifest

### PR DESCRIPTION
**Pull request by FlawlessCasual17**
- Changed the context menu option to use registry files.
- Changed the `pre_install` and `pre_uninstall` process so the explorer will no longer restart after either process.
- Added a `post_install` process.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rasa** [comment]
@FlawlessCasual17 The conflict is the entire file. Is one LF and one CRLF formatted?

**Comment by FlawlessCasual17** [comment]
@rasa I'm going to close this pull request and open a new one. Can you approve the new PR and pull that one please?

**Comment by FlawlessCasual17** [comment]
The new PR is here: #14654

**Pull request closed without merging**
