### PR TITLE
zoom: Fix checkver block and update to version 5.12.2.9281

### LINKED ISSUE #9458: Zoom is out of date
Current version: 5.11.4.7185
Available version: 5.12.0.8964
Download link: https://cdn.zoom.us/prod/5.12.0.8964/x64/ZoomInstallerFull.msi

### PR DESCRIPTION
**Pull request by Zliced13**
Closes #9458

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Zliced13** [comment]
@niheaven why did you close my PR?

**Comment by niheaven** [comment]
The commit has fixed the issue.

**Comment by Zliced13** [comment]
Oh ok. Good to know.

**Pull request closed without merging**
