### PR TITLE
emule-community: update to 0.60d; add x64 architecture

### LINKED ISSUE #4992: Is it OK to add a x64 version for eMule?
https://github.com/lukesampson/scoop-extras/blob/cf5c24e5f2fc6a294e1fc3e7784ba4697d4ceefc/bucket/emule-community.json#L18

The eMule github page is here:
https://github.com/irwir/eMule/releases/

But the x64 version download URL doesn't appear on [the eMule download page](https://www.emule-project.net/home/perl/general.cgi?l=42&rm=download).

Is it OK to add a x64 version download URL https://github.com/irwir/eMule/releases/download/eMule_v0.60a-community/eMule0.60a_x64.zip?

### PR DESCRIPTION
**Pull request by Lutra-Fs**
Closes #4992

### CODE REVIEW

**Comment by Lutra-Fs** [comment]
The PR is marked as a draft because auto-update needs a fix

**Comment by rashil2000** [comment]
Please don't remove the trailing newlines from the other files.

**Comment by Lutra-Fs** [comment]
> Please don't remove the trailing newlines from the other files.

Hi, @rashil2000 sorry for the change. The other changes are not shown on my machine.

**Pull request merged**
