### PR TITLE
sunshine: Fix installation

### PR DESCRIPTION
**Pull request by sitiom**
- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sitiom** [comment]
Bump @niheaven @HUMORCE @tech189

**Comment by tech189** [comment]
Have you tested the persist works? E.g. uninstall with `-p` flag and reinstall to make sure all files are created correctly. I tried to test it but I ran out of memory just opening the program!

**Comment by sitiom** [comment]
> Have you tested the persist works? E.g. uninstall with `-p` flag and reinstall to make sure all files are created correctly. I tried to test it but I ran out of memory just opening the program!

Yes, it works just fine. What error are you specifically getting?

**Comment by sitiom** [comment]
I'm sure this works. I'll just open another PR when it doesn't.

**Pull request merged**
