### PR TITLE
GUI.for.Clash: Add version 1.6.7

### LINKED ISSUE #13243: [Request]: GUI.for.Clash
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [x] Full version (i.e. not a trial version)
- [x] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

GUI.for.Clash

### Description

A GUI program developed by vue3 + wails.

### Homepage

https://github.com/GUI-for-Cores/GUI.for.Clash

### Download Link(s)

https://github.com/GUI-for-Cores/GUI.for.Clash/releases

### Some Indication of Popularity/Repute

https://github.com/GUI-for-Cores/GUI.for.Clash?tab=readme-ov-file#stargazers-over-time

### PR DESCRIPTION
**Pull request by Zacama**
Closes #13243

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by niheaven** [comment]
Change the manifest to `gui-for-clash`, give it a more meaningful description, and add arm64 build.

**Comment by Zacama** [comment]
@tiramission Thank you very much！

**Pull request merged**
