### PR TITLE
Improvement

### PR DESCRIPTION
**Pull request by xmha97**
1. All scoop packages installing without admin permission.
I changed "LOCAL_MACHINE" to "CURRENT_USER" because standard users can't open the .reg file.

2. Added *-associations.reg for LosslessCut

3. Fix torbrowser@12.5.6 #12074

### CODE REVIEW

**Comment by HUMORCE** [comment]
To support both local and global installation, use scripts in the manifests to replace it.

**Comment by rashil2000** [comment]
Please make separate PRs for each application

**Comment by xmha97** [comment]
> Please make separate PRs for each application

OK, please merge my PRs:

1. https://github.com/ScoopInstaller/Extras/pull/12087

2. https://github.com/ScoopInstaller/Extras/pull/12088

3. https://github.com/ScoopInstaller/Extras/pull/12089

cc: @rashil2000

**Pull request closed without merging**
