### PR TITLE
vscode: Update to version 1.84.0

### PR DESCRIPTION
**Pull request by mikisama**
Remove the 32-bit version as it no longer provides

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by octaviordz — APPROVED** [review]

**Comment by Roemer** [comment]
This PR seems a bit broken. Can you fix it so this can be merged?

**Comment by rami3l** [comment]
I guess that's because you have accidentally enabled workflows on your fork?

**Comment by mikisama** [comment]
> I guess that's because you have accidentally enabled workflows on your fork?

I just fork this repository and push to my fork repository, and magic happens.
Embarrassed 😂.

**Comment by AchimGaedkeLynker** [comment]
@mikisama I know how that feels... I had some problems with forks and pull requests as well.
Do you need a hand?

**Comment by mikisama** [comment]
> @mikisama I know how that feels... I had some problems with forks and pull requests as well. Do you need a hand?

Yes. I would be grateful if you would help me.
Should I close this issue and let you push your commit?

**Comment by AchimGaedkeLynker** [comment]
> Should I close this issue and let you push your commit?

Yep, close it, I'll create a new pull request and then ask the reviewer to move over.

**Pull request closed without merging**
