### PR TITLE
windows-terminal: Fix install-context script

### PR DESCRIPTION
**Pull request by wumo**
Closes #9333

- [ ] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by StarsbySea — COMMENTED** [review]
Can you please explain what the behaviour was like before and after the changes, and what was fixed by these changes?

**Review by jasongodev — COMMENTED** [review]
Reminding myself to test this soon.

**Comment by jasongodev** [comment]
Is this related to #8690 ?

**Comment by HUMORCE** [comment]
#8690

**Review by HUMORCE — APPROVED** [review]

**Pull request merged**
