### PR TITLE
 mp3tag: Update the manifest

### PR DESCRIPTION
**Pull request by FlawlessCasual17**
- Changed the context menu option to use registry files.
- Changed the `pre_install` and `pre_uninstall` scripts, so the explorer will no longer restart after either.
- Added a `post_install` script.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

**NOTE:** This PR also updates some `reg` files for VS Code because someone forgot to end them with a blank new line, as seen here in this GitHub Actions [log](https://github.com/ScoopInstaller/Extras/actions/runs/12538586773/job/34963890879#step:4:29).

### CODE REVIEW

**Comment by FlawlessCasual17** [comment]
@rasa

**Review by rasa — APPROVED** [review]

**Comment by glektarssza** [comment]
Did anyone actually test this? The changes for `mp3tag` do not work and are clearly wrong. [L51 of `bucket/mp3tag.json`](https://github.com/ScoopInstaller/Extras/pull/14654/files#diff-9d40af3c87e6bf0df539df02272db332306d9a70a869f93fce0beac4b6ebf017R51) has a reference to `*MyScoop*` which is not a known replacement pattern of any kind.

image

Additionally, running `uninstall` spits out a bunch of errors from the `reg` commands if the `install-mp3tag-content` commands have not been run yet which is definitely not good behavior.

image

**Comment by rasa** [comment]
@glektarssza Thank you for your detailed report. I did not test the changes, but I did review them, and they looked good. My apologies for any pain caused. I have reverted these changes, and will be more vigilant in the future.

**Comment by FlawlessCasual17** [comment]
I have made a new PR, #14834

**Comment by glektarssza** [comment]
Thank you both (@rasa and @FlawlessCasual17) for the quick response and turn around on getting this resolved. Kudos to both of you on that. This is honestly why I love `scoop` and will continue to use it over other package management systems for Windows.

**Pull request merged**
