### PR TITLE
winmerge: Update to version 2.16.18

### PR DESCRIPTION
**Pull request by c0bw3b**
Upstream has moved from Sourceforge to Github

---

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
Can you please add hash to autoupdate? It is available here https://winmerge.org/downloads/?lang=en

image

**Comment by c0bw3b** [comment]
I'm not sure how. Could you point to me another package definition that does this? That I could use as an example.

**Comment by rashil2000** [comment]
@c0bw3b see my commit

**Pull request merged**
