### PR TITLE
librewolf: Add version 91.0-1

### LINKED ISSUE #6333: [Request] Add Librewolf
>LibreWolf
>A fork of Firefox, focused on privacy, security and freedom.

https://librewolf-community.gitlab.io/

Windows release repository https://gitlab.com/librewolf-community/browser/windows

### PR DESCRIPTION
**Pull request by prg318**
This adds the latest version of librewolf for windows, a firefox fork focused on privacy and security

Edit: this is an updated version of a closed PR that was never fixed https://github.com/lukesampson/scoop-extras/pull/5785

Closes #6333

### CODE REVIEW

**Comment by rashil2000** [comment]
Hey @prg318 :)

Any updates?

**Comment by prg318** [comment]
I haven't updated the thread, so nope - no new updates. I've had pressing life priorities that have taken priority over this github issue.  This is a trivial task and anyone else can feel free to address if they have the privilege of having more free time available to them. Thanks for checking in.

**Comment by prg318** [comment]
Closing.  I don't want to be nagged about this; anyone else can feel free update the 91 to 95 if they care enough

**Comment by rashil2000** [comment]
You didn't have to reply right away, you could have replied when you had proper time _and_ did have anything useful to say.

Do not expect anyone else to spend time on your own PRs with that attitude. Thanks for closing this, saves us both time.

**Comment by prg318** [comment]
Yikes

**Comment by rashil2000** [comment]
Why are you replying again to this now, a 'Yikes' isn't any constructive information.

**Comment by prg318** [comment]
Could ask you the same - the personal attacks we're exactly constructive either.  This is about the first time I've unsubscribed, so i'm not sure if you are re-subscribing me or what, but please stop wasting my time.  Thanks!

**Comment by rashil2000** [comment]
Look at the tone of your own comments before telling me about attacks.

No one is re-subscribing you again (nobody's got the time to do that). I have a feeling you don't know how to unsubscribe from GitHub threads.

**Pull request closed without merging**
