### PR TITLE
uget@2.2.3: Fix checkver, autoupdate

### PR DESCRIPTION
**Pull request by ClassicDarkChocolate**
uget is currently 2.2.3 https://sourceforge.net/projects/urlget/files/uget%20%28stable%29/

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ClassicDarkChocolate** [comment]
Did it fail because I have to update version to latest manually first?

**Comment by rashil2000** [comment]
Yes

**Pull request merged**
