### PR TITLE
typora: Update description and note

### PR DESCRIPTION
**Pull request by b4imetu**
Typora:
Update description see https://appmakes.io/

Update note (delete `free version`) due to https://github.com/ScoopInstaller/Extras/commit/bbaafc2ea220e8f26dacb8b104268cbcbef6a1ee#commitcomment-77092710

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by StarsbySea — APPROVED** [review]

**Comment by Lutra-Fs** [comment]
In [typora.io](https://typora.io) it still shows  A TRULY MINIMAL MARKDOWN EDITOR.

**Comment by niheaven** [comment]
> In [typora.io](https://typora.io) it still shows A TRULY MINIMAL MARKDOWN EDITOR.

It's slogon...

`["a truly **minimal** markdown editor.", "new way to read &#38; write markdown.", "I think this is the one, <span style='color:#d14836'>❤</span>IT."]`

*A minimal Markdown editor and reader* sounds good to me.

**Review by StarsbySea — APPROVED** [review]

**Review by Lutra-Fs — APPROVED** [review]

**Review by niheaven — APPROVED** [review]

**Pull request merged**
