### PR TITLE
powertoys: Update to version 0.70.0 and add hardlinks

### PR DESCRIPTION
**Pull request by jaimecbernardo**
Updates PowerToys to 0.70.0 and adds missing hardlinks instructions for the new utilities.

Disclaimer: I'm the dev lead on PowerToys.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jaimecbernardo** [comment]
Hi @niheaven @HUMORCE , trying to get this in so that people don't get errors trying the new utilities.

**Review by HUMORCE — APPROVED** [review]

**Comment by jaimecbernardo** [comment]
Hi @HUMORCE , thanks for approving :) Can we merge this in soon? (trying to beat automatic update, which will cause people to have faulty installations due to missing hardlinks)
Thank you!

**Comment by bendem** [comment]
Installed this today, screen full of errors then says it's installed successfully. What's up? 
image

**Comment by jaimecbernardo** [comment]
Hi, Just gave it a try locally.
Some of the hardlinks the script is trying to create already exist in the target directory. The utilities seem to be working fine, though.

**Pull request merged**
