### PR TITLE
ungoogled-chromium-portable: Fix manifest and update

### PR DESCRIPTION
**Pull request by lunarwhite**
- [x] Fix checkver and autoupdate
- [x] Update version to 95.0.4638.69-r920003-1

Relates to #5975

### CODE REVIEW

**Review by rashil2000 — APPROVED** [review]

**Comment by pratikpc** [comment]
@lunarwhite works offline right?

**Comment by lunarwhite** [comment]
@pratikpc Tested offline again. It works well on my computer with the `checkver.ps1` ForceUpdate.

**Comment by pratikpc** [comment]
@lunarwhite no no I meant does it install properly?

For both 32 and 64 bit

**Comment by lunarwhite** [comment]
@pratikpc Both are OK.

**Pull request merged**
