### PR TITLE
shotcut: update to v21.10.31

### LINKED ISSUE #7428: shotcut@21.09.20: download via aria2 failed
ERROR Download failed! (Error 3) Resource was not found
ERROR https://github.com/mltframework/shotcut/releases/download/v21.09.20/shotcut-win64-210920.zip
    referer=https://github.com/mltframework/shotcut/releases/download/v21.09.20/
    dir=C:\Users\grisha\scoop\cache
    out=shotcut#21.09.20#https_github.com_mltframework_shotcut_releases_download_v21.09.20_shotcut-win64-210920.zip

ERROR & 'C:\Users\grisha\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\grisha\scoop\cache\shotcut.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=6600 --continue --summary-interval=0 --auto-save-interval=1

### PR DESCRIPTION
**Pull request by Lutra-Fs**
closes #7428

### CODE REVIEW

**Comment by DoveBoy** [comment]
@rashil2000 install failure

image

**Comment by rashil2000** [comment]
Looks like they changed their file structure. Can you make a PR for the fix?

**Comment by DoveBoy** [comment]
@rashil2000 
Fix install [shotcut](https://github.com/ScoopInstaller/Extras/pull/7434)

**Pull request merged**
