### PR TITLE
clash-verge-rev: Update to Version 2.0.2

### LINKED ISSUE #14464: [Update] the latest version of clash-verge-rev is 2.0.1 now.
The latest version of clash-verge-rev is 2.0.1 now.

### PR DESCRIPTION
**Pull request by b4imetu**
clash-verge-rev: Update to Version 2.0.1
Because the portable version has many problems, releases no longer provides a portable version
replace `portable` version with setup.exe

Relates to #13429 #13397 
Closes #14464

- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by b4imetu** [comment]
Major Update after 3 months of development, please review @aliesbelik

**Comment by Hughsean** [comment]
@b4imetu There is an extra blank line on line 39 of the json file.

**Comment by Hughsean** [comment]
@b4imetu Line 36 trailing whitespace.

**Pull request merged**
