### PR TITLE
sleek: Add version 1.2.1

### LINKED ISSUE #8766: [Request] Sleek Todo App
### Information

**Name:** Sleek

**Description:** todo.txt manager for Linux, Windows and MacOS, free and open-source (FOSS)

**Homepage:** [https://github.com/ransome1/sleek](https://github.com/ransome1/sleek)

**Download link(s):** [https://github.com/ransome1/sleek/releases](https://github.com/ransome1/sleek/releases)

**Some indication of popularity/repute:** 584 Github Stars

### PR DESCRIPTION
**Pull request by tech189**
- Closes #8766
- Uses Setup.exe rather than zip due to larger download and lack of automatic hash extraction
- Preferences stored in `user-preferences.json`

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by issaclin32** [comment]
They provide [portable ZIP version](https://github.com/ransome1/sleek/releases/download/v1.2.1/sleek-1.2.1-win.zip), is there any specific reason to use the installer?

**Comment by issaclin32** [comment]
The app supports **command-line args**. 
[wiki/Hidden preferences, custom variables and command line parameters](https://github.com/ransome1/sleek/wiki/Hidden-preferences,-custom-variables-and-command-line-parameters)

**Comment by tech189** [comment]
> They provide [portable ZIP version](https://github.com/ransome1/sleek/releases/download/v1.2.1/sleek-1.2.1-win.zip), is there any specific reason to use the installer?

The zip is a larger download and there is no automatic hash extraction available in `latest.yml` for the zip. I thought it might be better for saving bandwidth, what do you think?


> The app supports **command-line args**. [wiki/Hidden preferences, custom variables and command line parameters](https://github.com/ransome1/sleek/wiki/Hidden-preferences,-custom-variables-and-command-line-parameters)

Oops looks like we did it at the same time! I'll copy the `bin` section from your manifest

**Comment by issaclin32** [comment]
> The zip is a larger download and there is no automatic hash extraction available in `latest.yml` for the zip. I thought it might be better for saving bandwidth, what do you think?

I am fine with that.

**Review by issaclin32 — APPROVED** [review]

**Pull request merged**
