### PR TITLE
mpc-hc-fork: Update to version 2.3.2.1

### PR DESCRIPTION
**Pull request by kborowinski**
Updates the MPC-HC to latest version (v2.3.2)

- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aliesbelik** [comment]
Looks like automatic update failed since versions for 64bit/32bit packages in the same [2.3.2 release](https://github.com/clsid2/mpc-hc/releases/tag/2.3.2) are different:

> MPC-HC.2.3.2.1.x64.zip vs MPC-HC.2.3.2.x86.zip.

```
 mpc-hc-fork: 2.3.2.1 (scoop version is 2.3.1) autoupdate available
Autoupdating mpc-hc-fork
Downloading MPC-HC.2.3.2.1.x86.zip to compute hashes!
VERBOSE: GET https://api.github.com/repos/clsid2/mpc-hc with 0-byte payload
VERBOSE: received 15217-byte response of content type application/json; charset=utf-8
The remote server returned an error: (404) Not Found.
URL https://github.com/clsid2/mpc-hc/releases/download/2.3.2/MPC-HC.2.3.2.1.x86.zip is not valid
ERROR Could not update mpc-hc-fork, hash for MPC-HC.2.3.2.1.x86.zip failed!
```

**Comment by kborowinski** [comment]
@aliesbelik Yes, you're right. Let's close this PR and wait for the next release to see if that is a new naming scheme for the packages, or if it was just a one-off change.

**Comment by aliesbelik** [comment]
@kborowinski PR is ok, my only point was that the url for x64 version requires correction (looks like binaries for 64bit version were re-uploaded after release with changed revision) and autoupdate/check scripts cannot handle it properly.

**Pull request merged**
