### PR TITLE
mongodb-compass: Add version 1.29.6

### PR DESCRIPTION
**Pull request by wenmin92**
MongoDB Compass is already [available for free](https://www.mongodb.com/blog/post/compass-now-free-for-all), so we don't need to use the community version which is no longer maintained.

Relates to https://github.com/ScoopInstaller/Extras/pull/1208

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wenmin92** [comment]
The AppVeyor build failed, but I don't know why, it seems the url(http://scoop.sh/draft/schema#/definitions/license) was broken?
```
[-] mongodb-compass.json 9ms
        JSchemaReaderException: Could not resolve schema reference 'http://scoop.sh/draft/schema#/definitions/license'. Path 'definitions.autoupdateArch.properties.license', line 224, position 28.
        MethodInvocationException: Exception calling "Validate" with "1" argument(s): "Could not resolve schema reference 'http://scoop.sh/draft/schema#/definitions/license'. Path 'definitions.autoupdateArch.properties.license', line 224, position 28."
        at <ScriptBlock>, C:\projects\scoop\test\Scoop-Manifest.Tests.ps1: line 73
```

**Comment by rashil2000** [comment]
`"license": "SSPL-1.0"`

Update (and rename) the existing mongodb-compass-community.json manifest itself.

**Comment by rashil2000** [comment]
Any commandline parameters?

**Comment by wenmin92** [comment]
> Any commandline parameters?

Not found.

**Pull request merged**
