### PR TITLE
zebar: Add version 2.2.2

### LINKED ISSUE #14041: [Request]: Zebar
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

zebar

### Description

A taskbar for glazewm and komorebic

### Homepage

https://github.com/glzr-io/zebar

### Download Link(s)

https://github.com/glzr-io/zebar/releases

### Some Indication of Popularity/Repute

zebar has over 300 stars on github and integrates with glaze-wm and komorebi. Both are available on the scoop bucket.

@melMass created an recipe for scoop and it would be good to have it in the extras bucket.

https://github.com/glzr-io/zebar/issues/37#issuecomment-2350822250

Moreover, it is available with winget.

https://github.com/glzr-io/zebar/issues/37#issuecomment-2356148550

### PR DESCRIPTION
**Pull request by melMass**
This adds an auto-updating recipe for [zebar](https://github.com/glzr-io/zebar)

Closes #14041 

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by melMass** [comment]
Would also close https://github.com/glzr-io/zebar/issues/37

**Comment by aliesbelik** [comment]
Please follow the standard order of fields in the json file, as per [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md#for-scoop-buckets).

**Comment by melMass** [comment]
done and rebased on main

**Comment by melMass** [comment]
That action should probably check the field order if it's something you are so strict about. We would have saved one back and forth...

**Comment by aliesbelik** [comment]
> That action should probably check the field order if it's something you are so strict about. We would have saved one back and forth...

ScoopInstaller/Scoop#5292
ScoopInstaller/GithubActions#47

**Pull request merged**
