### PR TITLE
Delete deprecated wingetui.json

### PR DESCRIPTION
**Pull request by marticliment**
The extras/wingetui package is being replaced by nonportable/unigetui-np.

See https://github.com/ScoopInstaller/Nonportable/pull/362 for the addition of UniGetUI-NP

### CODE REVIEW

**Comment by aliesbelik** [comment]
Fixed by #14311.

**Comment by marticliment** [comment]
I am afraid the issue does not get fixed by the renaming, I attempted to move the package to nonportable since the extras package with innoextract is broken (some installation steps are required for UniGetUI to work proprtly). See the PR on nonportable: https://github.com/ScoopInstaller/Nonportable/pull/362

**Comment by marticliment** [comment]
image

**Comment by aliesbelik** [comment]
> image

https://github.com/ScoopInstaller/Extras/issues/13709#issuecomment-2448562806

**Comment by marticliment** [comment]
Oh, ok then

**Pull request closed without merging**
