### PR TITLE
teraterm@5.0: Switch to github release

### PR DESCRIPTION
**Pull request by topstone**
OSDN is currently unstable, so [current redistribution is via GitHub](https://github.com/TeraTermProject/osdn-download/releases).

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by topstone** [comment]
Which is the better way?

1.  To modify autoupdate-related fields and remake PR.
2.  To leave them as-is.

**Comment by CryoRenegade** [comment]
> Which is the better way?
> 
>     1. To modify autoupdate-related fields and remake PR.
> 
>     2. To leave them as-is.

Changing them over to github will be the better option, you can keep adding to this PR via your branch. If you need help let us know!

**Review by HUMORCE — APPROVED** [review]

**Pull request merged**
