### PR TITLE
godot-manager: Add version 0.2.1

### PR DESCRIPTION
**Pull request by sitiom**
A project, version, and addons/plugins manager for Godot.

Config and engines stored in `AppData\Roaming\Godot-Manager`.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by tech189 — APPROVED** [review]
Tested installation and autoupdate.

**Comment by sitiom** [comment]
Bump

**Comment by niheaven** [comment]
Suggest `godot` or `godot-mono`?

**Comment by sitiom** [comment]
> Suggest `godot` or `godot-mono`?

It downloads instances of Godot itself, so no.

**Pull request merged**
