### PR TITLE
Bruno: Add version 1.1.0

### PR DESCRIPTION
**Pull request by val1984**
Opensource IDE For Exploring and Testing APIs

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aliesbelik** [comment]
Duplicates #11970, relates to #11969.

**Comment by val1984** [comment]
Thank you for your review @aliesbelik, I'll check thoroughly next time 🙂
Do you know why the other PR is stuck?

**Comment by aliesbelik** [comment]
> Thank you for your review @aliesbelik, I'll check thoroughly next time 🙂 Do you know why the other PR is stuck?

No worries.

...As from my experience PRs into `extras` are not very quickly processed.
Maybe explicit mention of someone of maintainers (I'm not one) could help.
🤷

**Comment by tech189** [comment]
I'm working on the other PR so it should be merged soon 🙂

**Pull request closed without merging**
