### PR TITLE
cpu-z: Update to 1.97

### PR DESCRIPTION
**Pull request by 404NetworkError**

### CODE REVIEW

**Comment by wasi-master** [comment]
Why isn't this merged?

**Comment by pratikpc** [comment]
@wasi-master no checkver
@404NetworkError you still around?

Could you add checkver?

**Comment by rashil2000** [comment]
The latest version is 1.98 - https://github.com/ScoopInstaller/Extras/pull/7195

**Comment by 404NetworkError** [comment]
Closing in favor of #7195

**Pull request closed without merging**
