### PR TITLE
tachidesk-jui: Add version 1.2.0

### PR DESCRIPTION
**Pull request by Witchilich**
https://github.com/ScoopInstaller/Java/pull/299#issuecomment-899494876

### CODE REVIEW

**Comment by Witchilich** [comment]
Seems to work fine on my end.

**Comment by rashil2000** [comment]
Please use the architecture block, for URL, hash, and autoupdate

**Comment by Witchilich** [comment]
There is no 32-bit version to use the architecture block.

**Comment by rashil2000** [comment]
I was talking about the 64bit version. Even if there's just 64bit version, you need to use architecture block.

**Review by rashil2000 — APPROVED** [review]

**Review by issaclin32 — APPROVED** [review]

**Pull request merged**
