### PR TITLE
qq: Update to version 9.9.0.14569 & add architecture and persist

### PR DESCRIPTION
**Pull request by StarsbySea**
Relates to #11328 #11329 

- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Yakkhini** [comment]
Why not to rename this manifest as qq-nt.json? Then the conflict will disappear.

**Comment by aliesbelik** [comment]
Added as separate manifest - `extras\qq-nt`.

**Pull request closed without merging**
