### PR TITLE
vidcoder: Add version 7.10

### PR DESCRIPTION
**Pull request by KaranKad**
Updated VidCoder to version 7.10

Removed notes part.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
Why remove the note?

**Comment by KaranKad** [comment]
Because its common for apps to store config in %appdata% folder.

**Comment by rashil2000** [comment]
The information is required here, since the manifest downloads the portable version but still stores the data in AppData folder.

**Comment by KaranKad** [comment]
Ok i'll add it back

**Comment by KaranKad** [comment]
The bot updated it so i'll close mine https://github.com/ScoopInstaller/Extras/commit/bcb85150f0f3ee89e25d17ce5b38cdc3e3eecaa9

**Pull request closed without merging**
