### PR TITLE
Update blender.json

### PR DESCRIPTION
**Pull request by beyond9thousand**
Due to the latest set of DDoS attacks on blender.org, they have had to undergo changes for their urls.

Relates to #12307

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by beyond9thousand** [comment]
Nevermind, their original url is back up again

**Comment by Samson7** [comment]
> Nevermind, their original url is back up again

Yes now it's working but with very slow speed and in the end it failed:
`blender: 4.0.0 -> 4.0.1
Updating one outdated app:
Updating 'blender' (4.0.0 -> 4.0.1)
Downloading new version
blender-4.0.1-windows-x64.zip (382.1 MB) [=========>                                                          ]  15%
Checking hash of blender-4.0.1-windows-x64.zip ... ERROR Hash check failed!
App:         extras/blender
URL:         https://download.blender.org/release/Blender4.0/blender-4.0.1-windows-x64.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    6845ceeafd957328729099450b27eb8188843a6f5eace723a4bea11964f6d7bc
Actual:      5256e75e7c7ce685fba785f329df48fcb1e1615fed9dc5611286a4ee5a3cc449

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=blender%404.0.1%3a+hash+check+failed`

**Comment by Samson7** [comment]
Never mind, after second attempt it has been installed successfully

**Pull request closed without merging**
