### PR TITLE
TreeSheets: Add version 11693219263

### LINKED ISSUE #14356: [Request]: TreeSheets
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

TreeSheets

### Description

TreeSheets is a free form data organizer and a replacement for spreadsheets, mind mappers, outliners, PIMs, text editors and small databases.

### Homepage

https://strlen.com/treesheets

### Download Link(s)

https://github.com/aardappel/treesheets/releases/

### Some Indication of Popularity/Repute

Github stars: 2.6k
Forks: 192

### PR DESCRIPTION
**Pull request by simonsan**
Closes #14356

- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by simonsan** [comment]
Not sure, what is wrong with the hash check, I can install it locally and the hashes match. 🤔

**Comment by aliesbelik** [comment]
> Not sure, what is wrong with the hash check, I can install it locally and the hashes match. 🤔

[Autoupdate](https://github.com/ScoopInstaller/Scoop/wiki/App-Manifest-Autoupdate) section should contain template to generate url (and, optionally, hash) for new version (detected by `checkver` condition) but not the concrete values.
Please look into e.g. this [treesheets](https://github.com/Jadeiin/scoop/blob/master/bucket/treesheets.json) manifest to correct your own.

**Comment by simonsan** [comment]
Thank you, that was helpful! Fixed the problems. :)

**Pull request merged**
