### PR TITLE
houdoku: Fix arch

### PR DESCRIPTION
**Pull request by sitiom**
Fixes https://github.com/ScoopInstaller/Extras/pull/8887#discussion_r1034279768

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by niheaven** [comment]
Where's the config files for `zip` edition? If it is still in $APPDATA, using exe and given hash is better.

**Comment by sitiom** [comment]
> Where's the config files for `zip` edition? If it is still in $APPDATA, using exe and given hash is better.

It's still in `%appdata%`, and with the actual zip version, we do not need the `pre_install` field and the manifest is much simpler.

**Comment by niheaven** [comment]
Given hash and smaller download size are preferred than simpler manifest. So just nest the arch in this PR.

**Pull request merged**
