### PR TITLE
caret: Add version 3.4.6

### PR DESCRIPTION
**Pull request by b4imetu**
Snipaste_2022-07-16_20-08-34
[Typora beta](https://github.com/ScoopInstaller/Versions/blob/master/bucket/typora0.11.18.json) IS DEAD.

Looking for an alternative.

caret-beta: [caret.io](https://caret.io/)

code modified from [naderi](https://github.com/naderi/scoop-bucket/blob/master/bucket/caret-beta.json)

- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by b4imetu** [comment]
@issaclin32 I accidentally closed this unmerged pull request ;<
Can you please reopen it? and /verify, thank you very much ^^

**Comment by issaclin32** [comment]
Thanks for the PR, but we only accept **stable versions** in *Main* and *Extras*.

You can add the [stable version](https://github.com/careteditor/releases) here,
and add beta version to [Versions bucket](https://github.com/ScoopInstaller/Versions) as `caret-beta`.

**Comment by issaclin32** [comment]
* App built in **32-bit**
* config location: `$Env:AppData\caret`

(This is a reminder. No need to modify anything regard to this.)

**Review by issaclin32 — APPROVED** [review]

**Pull request merged**
