### PR TITLE
git-tower@6.0.474: Fix extraction

### LINKED ISSUE #12945: git-tower@6.0.474: decompress error
```
#> s add extras/git-tower

Installing 'git-tower' (6.0.474) [64bit] from extras bucket
Loading Tower-6.0.474.exe from cache
Checking hash of Tower-6.0.474.exe ... ok.
Extracting dl.7z ... done.
Running pre_install script...

Confirm
The item at C:\Scoop\apps\git-tower\6.0.474\_rels has children and the Recurse parameter was not specified. If you
continue, all children will be removed with the item. Are you sure you want to continue?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): y

Confirm
The item at C:\Scoop\apps\git-tower\6.0.474\lib has children and the Recurse parameter was not specified. If you
continue, all children will be removed with the item. Are you sure you want to continue?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): a
ERROR Exit code was 7!
Failed to extract files from C:\Scoop\apps\git-tower\6.0.474\Tower-*-full.nupkg.
Log file:
  C:\Scoop\apps\git-tower\6.0.474\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=git-tower%406.0.474%3a+decompress+error
```

### PR DESCRIPTION
**Pull request by suabahasa**
The latest Git-Tower have different folder/file structure.

Closes #12945

- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aliesbelik** [comment]
1. Please fix hash autoupdate;
2. looks like nupkg still available as well:
https://www.git-tower.com/apps/tower3-win/474-510807f7/Tower-6.0.474.nupkg

**Comment by suabahasa** [comment]
I have no idea how to fix the hash autoupdate.

**Pull request merged**
