### PR TITLE
VencordInstallerCli: Add version `1.4.0`

### LINKED ISSUE #13200: [Request]: Vencord Installer
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

Vencord Installer

### Description

A cross platform gui/cli app for installing Vencord

### Homepage

https://github.com/Vencord/Installer

### Download Link(s)

https://github.com/Vencord/Installer/releases/download/v1.4.0/VencordInstallerCli.exe

### Some Indication of Popularity/Repute

image

### PR DESCRIPTION
**Pull request by Ravencentric**
Add https://github.com/Vencord/Installer (only the CLI variant, there's also a GUI one).
I'm not certain if the GUI version should be it's own manifest or part of this one.

Hope I've not messed up anything but do lemme know if something's wrong, thanks!

Relates to #13200

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aliesbelik** [comment]
Virustotal report:
https://www.virustotal.com/gui/file/466d2a0be1f380ddffed052df3cc132125fa34dc1af29312e14f13f358c8d2a2

Even if false positive (Vencord/Installer#127), may cause installation errors when binaries blocked/quarantined by antivirus.

**Comment by Ravencentric** [comment]
Is that a big blocker? If so, isthere anything I can do here or do I just close this?

**Comment by sitiom** [comment]
The CLI version should belong to https://github.com/ScoopInstaller/Main; maybe you can create your PR there instead

**Pull request closed without merging**
