### PR TITLE
Add SolveSpace version 3.0

### LINKED ISSUE #7456: [Request] solvespace
### Information

**Name:** solvespace

**Description:** SOLVESPACE is a free (GPLv3) parametric 3d CAD tool.

**Homepage:** <https://solvespace.com/>

**Download link(s):** <https://github.com/solvespace/solvespace/releases>

**Some indication of popularity/repute:** 

GitHub 1.9k stars.

It releases single executable binary so it can be packed easily.

### PR DESCRIPTION
**Pull request by tech189**
Closes #7456

No architecture section because app is 32-bit.

### CODE REVIEW

**Comment by rashil2000** [comment]
- Anything to persist?
- Does the binary take any commandline arguments? If no, then we can remove the bin field and keep only the shortcuts field.

**Comment by tech189** [comment]
- Nothing to persist because the app saves config in the registry on Windows, there's an issue discussing using JSON here: https://github.com/solvespace/solvespace/issues/1136
- I think it does have a cli (see https://github.com/solvespace/solvespace/blob/0e0b0252e23dd5bd4ae82ababcc54c44aee036d6/src/platform/entrycli.cpp), but I couldn't get it to work, it only seems to expect a filename to open, maybe @demolg knows better

**Review by rashil2000 — APPROVED** [review]

**Review by issaclin32 — APPROVED** [review]

**Pull request merged**
