### PR TITLE
reduce-memory: add version 1.6

### PR DESCRIPTION
**Pull request by ppvnf**
Closes https://github.com/ScoopInstaller/Extras/issues/9660

Relates to https://github.com/ScoopInstaller/Extras/pull/9701

- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by niheaven** [comment]
You should run `checkver.ps1` to ensure the format.

**Comment by ppvnf** [comment]
> You should run `checkver.ps1` to ensure the format.
I thought /verify would take care of it

**Comment by niheaven** [comment]
Sadly not... `/verify` could only check elements but not format, which is done by other GHAs.

**Review by niheaven — APPROVED** [review]

**Pull request merged**
