### PR TITLE
archwsl: Prevents installation outside Scoop management

### PR DESCRIPTION
**Pull request by yuk7**
Prevents users from accidentally performing an installation outside of Scoop's management.
If the installation is performed outside Scoop's management, the data will be created in a location other than the persist directory.
In that case, the installation will be destroyed when the update is performed.

### CODE REVIEW

**Review by rashil2000 — APPROVED** [review]

**Comment by ohk2kt3t4** [comment]
https://github.com/ScoopInstaller/Extras/blob/4bf117f999ed80707607a3387039a55d2d7d6223/bucket/archwsl.json#L30

^ @yuk7  Is this meant to be Manjaro.exe?

```
PS C:\Users\ohk2kt3t4> scoop install archwsl
Installing 'archwsl' (21.8.28.0) [64bit]
Arch.zip (189.0 MB) [=========================================================================================] 100%
Checking hash of Arch.zip ... ok.
Extracting Arch.zip ... done.
Linking ~\scoop\apps\archwsl\current => ~\scoop\apps\archwsl\21.8.28.0
Creating shim for 'Arch'.
Creating shortcut for Arch Linux (Arch.exe)
Persisting data
Running post-install script...
ERROR Exception calling "Start" with "0" argument(s): "An error occurred trying to start process 'C:\Users\ohk2kt3t4\scoop\apps\archwsl\current\Manjaro.exe' with working directory 'C:\Users\ohk2kt3t4'. The system cannot find the file specified."
WARN  DO NOT KILL THE PROCESS. Installation is still running!
'archwsl' (21.8.28.0) was installed successfully!
Notes
-----
Even when you are logging in as 'root', some operations (like service command) require Windows administrator privileges
```

**Comment by ohk2kt3t4** [comment]
@rashil2000 Actually I think you made a mistake in your finalizing commit

**Comment by sitiom** [comment]
Surely is, fixed in #7449.

**Comment by rashil2000** [comment]
Extremely sorry, I made a commit - b0822cafe5742e2fdba844e3f0d85940b254e068

**Pull request merged**
