### PR TITLE
Fix up forgotten delete oprations in #7173

### PR DESCRIPTION
**Pull request by escape0707**
https://github.com/ScoopInstaller/Extras/pull/7173#issuecomment-962463851

Sorry for the additional confusion. Orz. @issaclin32

### CODE REVIEW

**Review by issaclin32 — APPROVED** [review]

**Comment by issaclin32** [comment]
No Worries. It was also part of my problem, I didn't check carefully enough.

**Comment by pratikpc** [comment]
Hey it looks like data from qBittorrent portable is not being moved to qBittorrent.

This would break it for qBitTorrent-portable users as not only have they lost a manifest but they might have to manually copy paste their persisted data from one persist directory to another.

Could we please restore qBitTorrent-portable till the data move from qBitTorrent-portable persist to qBitTorrent's persist is completed?

**Comment by escape0707** [comment]
I'll test it now.

**Comment by escape0707** [comment]
@pratikpc Thanks for mentioning this overlooked point. I'll submit a fix now.

**Pull request merged**
