### PR TITLE
mcomix@3.0: Remove trailing commas

### LINKED ISSUE #12215: [Bug]: mcomix 3.0 Error parsing JSON
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

mcomix

### Expected/Current Behaviour

Updating/Installing mcomix to 3.0 fails to parse the json manifest.

### Steps to Reproduce

```console
scoop install mcomix
```

### Possible Solution

Remove trailing commas.

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
0b0bd5e90 (HEAD -> master, origin/master, origin/HEAD) sidekick-browser: Update to version 114.52.2.36023-3b20c98

'games' bucket:
f05ba74de (HEAD -> master, origin/master, origin/HEAD) yuzu-pineapple: Update to version EA-3971

'java' bucket:
9afed324 (HEAD -> master, origin/master, origin/HEAD) temurin8-nightly-jre: Update to version 8.0.402-1.0.202311101855

'main' bucket:
2e3e3c31b (HEAD -> master, origin/master, origin/HEAD) numbat: Update to version 1.8.0
```

### Scoop Config

```console
root_path     : D:\Scoop
last_update   : 2023-11-11T23:31:11.8182314+01:00
aria2-enabled : False
scoop_branch  : master
scoop_repo    : https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.22621.2506
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.2506
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Additional Softwares

_No response_

### PR DESCRIPTION
**Pull request by ItsBasi**
Closes #12215

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ItsBasi** [comment]
I looks like the /verify run in #11890 did not catch that.

**Comment by AMDmi3** [comment]
Please merge this asap. Repository parsing is broken for more than a week.

**Comment by ipcjs** [comment]
@sitiom, I have made a [PR](https://github.com/ScoopInstaller/GithubActions/pull/38) to check manifest format by ScoopInstaller/GithubActions.
Could you please help me review it?

**Comment by sitiom** [comment]
Hi. Unfortunately, I'm only a collaborator on the Extras bucket (this repo).

**Pull request merged**
