### PR TITLE
youtube-dl-gui@1.8.2: Fix decompress error

### PR DESCRIPTION
**Pull request by HUMORCE**
close https://github.com/ScoopInstaller/Extras/issues/7494

```powershell
PS C:\Users\HUMOR> scoop config MSIEXTRACT_USE_LESSMSI false
'MSIEXTRACT_USE_LESSMSI' has been set to 'false'
PS C:\Users\HUMOR> scoop install youtube-dl-gui
Installing 'youtube-dl-gui' (1.8.2) [64bit]
Loading yt-dlg.msi from cache
Checking hash of yt-dlg.msi ... ok.
Running pre-install script...
Linking ~\scoop\apps\youtube-dl-gui\current => ~\scoop\apps\youtube-dl-gui\1.8.2
Creating shortcut for yt-dlg (yt-dlg.exe)
'youtube-dl-gui' (1.8.2) was installed successfully!
PS C:\Users\HUMOR> scoop config MSIEXTRACT_USE_LESSMSI true
'MSIEXTRACT_USE_LESSMSI' has been set to 'true'
PS C:\Users\HUMOR> scoop uninstall youtube-dl-gui
Uninstalling 'youtube-dl-gui' (1.8.2).
Removing shortcut ~\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps\yt-dlg.lnk
Unlinking ~\scoop\apps\youtube-dl-gui\current
'youtube-dl-gui' was uninstalled.
PS C:\Users\HUMOR> scoop install youtube-dl-gui
Installing 'youtube-dl-gui' (1.8.2) [64bit]
Loading yt-dlg.msi from cache
Checking hash of yt-dlg.msi ... ok.
Running pre-install script...
Linking ~\scoop\apps\youtube-dl-gui\current => ~\scoop\apps\youtube-dl-gui\1.8.2
Creating shortcut for yt-dlg (yt-dlg.exe)
'youtube-dl-gui' (1.8.2) was installed successfully!
```

### CODE REVIEW

**Comment by niheaven** [comment]
Is it a common case that msi installer has `APPDIR`?

**Comment by HUMORCE** [comment]
no, but `msiexec` can handle this case.

**Comment by niheaven** [comment]
It's a wrong setting IMO. I'll try to handle such case in `Expand-MsiArchive` Ref: https://www.advancedinstaller.com/user-guide/setappdir.html

**Comment by rashil2000** [comment]
I'm merging this for now, otherwise the youtube-dl-gui package will be broken.

When `Expand-MsiArchive` is updated upstream, we can remove this workaround.

**Pull request merged**
