### PR TITLE
tailscale: Add note and scripts for adding to startup programs

### LINKED ISSUE #10329: tailscale: No option to add to startup folder
We should display a note to users with instructions on how to add Tailscale to their startup folder. Also, we should be able to provide a script for adding and removing the shortcut from the startup folder.

### PR DESCRIPTION
**Pull request by shayne**
Make it easier for users to add Tailscale to the startup programs folder by providing a note with scripts to add/remove from the startup folder.

Changes:
 - add `"notes"` with instructions for adding to to startup programs 
 - `pre_install` move is_admin check to fail early
 - `pre_install` generates `tailscale-{add,remove}-startup` scripts
 - `uninstaller` also removes the startup shortcut

Closes #10329

- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by shayne** [comment]
@tech189, any objections to merging this in?

**Comment by tech189** [comment]
Not sure if it's necessary to create a script to add the program to start up within Scoop's installation, it would probably be better to do this within the application itself. For example, QuickLook's menu:
image

However, getting Scoop to manage this is a [popular feature request](https://github.com/ScoopInstaller/scoop/issues/2276) and since that's not currently possible, we could add this if no one else objects. We would just need to put the script into the `scripts` folder rather than into the program's folder.

**Comment by shayne** [comment]
Thanks! I would prefer to include the script (and am happy to move it to a `scripts` folder) if that's OK. Short of having it automatically added to start-up programs, showing users the note with an actionable command is ideal since, for Tailscale, it's almost always what's wanted.

**Comment by shayne** [comment]
Updated to use `scripts`

**Comment by HUMORCE** [comment]
Use `notes` instead of script.

```
Add to startup:
New-ItemProperty -Path HKCU:\Software\Microsoft\Windows\CurrentVersion\Run -Name Tailscale -PropertyType String -Value "$dir\\tailscale-ipn.exe"

Remove from startup:
Remove-ItemProperty -Path HKCU:\Software\Microsoft\Windows\CurrentVersion\Run -Name Tailscale
```

**Review by StarsbySea — APPROVED** [review]
LGTM. Thanks!

**Comment by shayne** [comment]
LMK if we want to use notes instead of what is currently posted

**Comment by StarsbySea** [comment]
> LMK if we want to use notes instead of what is currently posted

Maybe you should take HUMORCE's advice, after all he is a member of ScoopInstaller and has a lot more experience than me 😂

**Comment by jasongodev** [comment]
What's the progress of this PR? Is this ready for review?

**Comment by shayne** [comment]
@jasongodev, it's ready if folks are OK with the script approach. The notes approach is OK, but the line length causes line breaks in PowerShell, making it fail to copy and paste, which is a real bummer.

image

**Review by jasongodev — CHANGES_REQUESTED** [review]
@shayne Please run a checkver update of this manifest to update the version and hash. This will pass the verifier bot test.

**Comment by shayne** [comment]
Thanks, done!

**Comment by shayne** [comment]
Whoops! Didn't amend the commit properly. 😅

**Review by StarsbySea — APPROVED** [review]

**Review by jasongodev — APPROVED** [review]

**Comment by shayne** [comment]
It looks like we're approved. Any chance we could land this PR? 🙏

**Review by tech189 — APPROVED** [review]
Tested startup scripts and checked Tailscale started at login 👍

**Pull request merged**
