### PR TITLE
tenacity: Add version 1.3.3

### LINKED ISSUE #10885: [Request]: Tenacity
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [ ] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

Tenacity

### Description

Tenacity is an easy-to-use, privacy-friendly, FLOSS, cross-platform multi-track audio editor for Windows, macOS, Linux, and other operating systems

### Homepage

https://codeberg.org/tenacityteam/tenacity

### Download Link(s)

https://codeberg.org/tenacityteam/tenacity/releases

### Some Indication of Popularity/Repute

image

image

### PR DESCRIPTION
**Pull request by FlawlessCasual17**
Relates to #10885 

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by HUMORCE** [comment]
Use stable version rather than beta.

**Comment by Zliced13** [comment]
There is no stable version. Should I put it in the Versions bucket instead?

**Comment by HUMORCE** [comment]
screenshot_230415_111933

**Comment by Zliced13** [comment]
@HUMORCE I'm going to make another PR but in the versions bucket instead of this bucket.

**Comment by FlawlessCasual17** [comment]
@HUMORCE and I updated this PR

**Comment by FlawlessCasual17** [comment]
@simonsan Sorry for not being able to do this earlier, here is your early Christmas present 🎊

**Pull request closed without merging**
