### PR TITLE
opentrack: Update to version 2022.1.0

### PR DESCRIPTION
**Pull request by Lutra-Fs**
Closes #XXXX

Relates to #XXXX

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
An unrelated question: where are the settings/config stored for the portable version?

**Comment by Lutra-Fs** [comment]
it is in Documents/opentrack-v2.3

**Comment by Lutra-Fs** [comment]
if u create this file the settings will be stored in `installation path/ini` folder.

**Comment by Lutra-Fs** [comment]
I will make an issue about the config store path in this repo.

**Comment by rashil2000** [comment]
Issue is already present https://github.com/ScoopInstaller/Extras/issues/3548

We just need a PR to handle migration :)

**Comment by Lutra-Fs** [comment]
Yes just found that. But if we change the config location, there will be some impact on the users who already installed it. I can do this later if we need it.

**Comment by rashil2000** [comment]
Yes, that's what I mean by migration. See https://github.com/ScoopInstaller/Extras/blob/master/bucket/vscode.json#L44-L51 for example.

**Pull request merged**
