### PR TITLE
divoom-cli, divoom-gateway: Add version 0.1.25

### PR DESCRIPTION
**Pull request by r12f**
2 command line tools for controlling the [divoom device](https://www.divoom.com/products/pixoo-64).

Repo and more README could be found here: https://github.com/r12f/divoom.
- divoom-cli: https://github.com/r12f/divoom/tree/main/divoom_cli
- divoom-gateway: https://github.com/r12f/divoom/tree/main/divoom_gateway

- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r12f** [comment]
validated on private bucket:

```
> scoop install divoom-cli
Installing 'divoom-cli' (0.1.25) [64bit]
divoom-cli.0.1.25.windows.x64.zip (1.2 MB) [==================================================================] 100%
Checking hash of divoom-cli.0.1.25.windows.x64.zip ... ok.
Extracting divoom-cli.0.1.25.windows.x64.zip ... done.
Linking ~\scoop\apps\divoom-cli\current => ~\scoop\apps\divoom-cli\0.1.25
Creating shim for 'divoom-cli'.
'divoom-cli' (0.1.25) was installed successfully!

> scoop install divoom-gateway
Installing 'divoom-gateway' (0.1.25) [64bit]
Loading divoom-gateway.0.1.25.windows.x64.zip from cache
Checking hash of divoom-gateway.0.1.25.windows.x64.zip ... ok.
Extracting divoom-gateway.0.1.25.windows.x64.zip ... done.
Linking ~\scoop\apps\divoom-gateway\current => ~\scoop\apps\divoom-gateway\0.1.25
Creating shim for 'divoom-gateway'.
'divoom-gateway' (0.1.25) was installed successfully!
```

**Comment by issaclin32** [comment]
https://github.com/ScoopInstaller/Extras/pull/8966#issuecomment-1201820067

**Comment by tech189** [comment]
Seems reasonable to me 👍

**Review by issaclin32 — APPROVED** [review]

**Pull request merged**
