### PR TITLE
silex-desktop: add version 2.7.27

### LINKED ISSUE #7762: [Request] add silex-desktop
### Information

**Name: silex-desktop** [name of new package]

**Description: Silex, is a free and open source website builder in the cloud. Create websites directly in the browser without writing code. And it is suitable for professional designers to produce great websites without constraints. Silex is also known as the HTML5 editor.** [clear and concise details of what it is]

**Homepage: https://github.com/silexlabs/silex-desktop/** [a URL/link]

**Download link(s): https://github.com/silexlabs/silex-desktop/releases/download/v2.7.27/silex-desktop-Setup-2.7.27.exe** [URL(s)/link(s)]

**Some indication of popularity/repute: Github 31 stars** [GitHub stars/software reviews etc.]

### PR DESCRIPTION
**Pull request by tech189**
- Closes #7762
- Nothing to persist, settings stored in `AppData\Roaming\silex-desktop`
- Parent project has 1.2k stars so probably worth adding

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
autoupdate hash extraction https://github.com/silexlabs/silex-desktop/releases/download/v2.7.27/latest.yml

**Comment by tech189** [comment]
I couldn't get it to work, the sha512 value seems to be encoded in base64 but decoding it gives garbage characters: D.NÒáYËNöº³íqaÍÐñ"L°Ý¯íN¡Ò>9¶3ß]ögñiÂ!Jã0¶WÖ:7¢

**Comment by rashil2000** [comment]
That's strange...

**Pull request merged**
