### PR TITLE
bitwarden: Changed `pre_install`, added `architecture`, and added `autoupdate` hash extraction

### PR DESCRIPTION
**Pull request by FlawlessCasual17**
This was done, because the Bitwarden electron app was NOT made to be portable. This change was made so the portable config folder's contents will be copied over to the `Appdata\Roaming` directory.

See #10651 if you want to know more of what I am talking about.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by jasongodev — APPROVED** [review]
I agree with this change and the way it should be done with other Electron apps if possible.

This installed correctly. Merge can be done safely.

**Comment by o-l-a-v** [comment]
Why was this closed? @jasongodev @FlawlessCasual17 

One more observation: One can add `--user-data-dir=\"$dir\\data\"` to the shortcut to have it store user data inside Scoop, rather than it using the default path of `$env:APPDATA\Bitwarden`. Tested with following manifest:

<details><summary>Click to expand</summary>

```json
{
    "version": "2025.2.1",
    "description": "Password management solutions for individuals, teams, and business organizations",
    "homepage": "https://bitwarden.com",
    "license": "GPL-3.0-or-later",
    "architecture": {
        "32bit": {
            "url": "https://github.com/bitwarden/clients/releases/download/desktop-v2025.2.1/bitwarden-2025.2.1-ia32.nsis.7z",
            "hash": "2f9959351c62ba020704f03d600593b8e59fbc161f2db3d3170e10b4a46f8589"
        },
        "64bit": {
            "url": "https://github.com/bitwarden/clients/releases/download/desktop-v2025.2.1/bitwarden-2025.2.1-x64.nsis.7z",
            "hash": "ccadc00b8e40ef3e7184bce4d3b4b94cb7b5d1ae8c529f6f52cc9c24a05aa502"
        },
        "arm64": {
            "url": "https://github.com/bitwarden/clients/releases/download/desktop-v2025.2.1/bitwarden-2025.2.1-arm64.nsis.7z",
            "hash": "215abd822d52b9a9509c857e18105aca3ad72767f68e1a4cb694e6b04986a936"
        }
    },
    "pre_install": [
        "# Remove built in update info",
        "$null = Remove-Item -Force -Path \"$dir\\resources\\app-update.yml\""
    ],
    "bin": "Bitwarden.exe",
    "shortcuts": [
        [
            "Bitwarden.exe",
            "Bitwarden",
            "--user-data-dir=\"$dir\\data\""
        ]
    ],
    "persist": "data",
    "checkver": {
        "url": "https://api.github.com/repositories/53538899/releases",
        "regex": "tag/desktop-v([\\d.]+)"
    },
    "autoupdate": {
        "architecture": {
            "32bit": {
                "url": "https://github.com/bitwarden/clients/releases/download/desktop-v$version/bitwarden-$version-ia32.nsis.7z"
            },
            "64bit": {
                "url": "https://github.com/bitwarden/clients/releases/download/desktop-v$version/bitwarden-$version-x64.nsis.7z"
            },
            "arm64": {
                "url": "https://github.com/bitwarden/clients/releases/download/desktop-v$version/bitwarden-$version-arm64.nsis.7z"
            }
        },
        "hash": {
            "url": "$baseurl/sha256-checksums.txt",
            "regex": "$sha256\\s+$basename"
        }
    }
}
```

</details>

Related, which this PR could've fixed:

* <https://github.com/bitwarden/clients/issues/12879>

**Comment by FlawlessCasual17** [comment]
Oh, this was closed because I accidentally deleted the branch.

**Comment by o-l-a-v** [comment]
I created a new PR #15053 and gave you credit @FlawlessCasual17, hope that's OK?

**Pull request closed without merging**
