### PR TITLE
zoom: register/unregister zoommtg:// protocol handler

### PR DESCRIPTION
**Pull request by brechtm**
- add registry keys post-install
- remove these during uninstallation

Fixes: #4573
Related: lukesampson/scoop#3944, lukesampson/scoop#3412

### CODE REVIEW

**Review by Ash258 — DISMISSED** [review]
- Do not use `Echo`
- Global installation is not respected
- Lots of code repetition

**Comment by brechtm** [comment]
Thanks for the quick review!

>     * Do not use `Echo`

Is there an alternative, or shouldn't it print anything?
 
>     * Global installation is not respected

Are you referring to writing to HKCU? That's user-specific, and Zoom is basically broken without setting up the URL protocol handler.

>     * Lots of code repetition

Partly addressed in second commit. Is it possible to avoid repeating the registry path in the uninstaller?

**Comment by brechtm** [comment]
@Ash258 Friendly reminder to answer my questions. Thanks 🙏

**Comment by brechtm** [comment]
Or perhaps @r15ch13?

**Comment by altro3** [comment]
Hi! Want to ask about this pull request. Are you planning to merge it (or answer to questions)? Can't use zoom from scoop now without this fix.

**Comment by issaclin32** [comment]
I think writing to *HCKU* is totally fine. This does not require admin rights, so it is unlikely to cause trouble during install/uninstall.

**Review by issaclin32 — APPROVED** [review]

**Pull request merged**
