### PR TITLE
beaver-notes: Add version 3.5.0

### LINKED ISSUE #13660: [Request]: Beaver Notes
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

Beaver Notes

### Description

A privacy-focused note-taking application for Mac OS, Windows and GNU/Linux

### Homepage

https://beavernotes.com/

### Download Link(s)

https://github.com/Beaver-Notes/Beaver-Notes/releases

### Some Indication of Popularity/Repute

468 stars on its GitHub repo

### PR DESCRIPTION
**Pull request by o-l-a-v**
Closes #13660

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aliesbelik** [comment]
Please follow the standard order of fields in the json file, as per [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md#for-scoop-buckets).

**Comment by o-l-a-v** [comment]
Fixed indent size and JSON ordering. But the second point is blocked by:

* <https://github.com/Beaver-Notes/Beaver-Notes/issues/223>

**Comment by o-l-a-v** [comment]
I had an instance were install failed beacuse it could not run `Remove-Item -Path "$dir\`$*\", \"$dir\Uninstall*\" -Force -Recurse` due to CrowdStrike Falcon Sensor placing handles on content inside `$PLUGINSDIR`, ref:

* <https://github.com/ScoopInstaller/Scoop/issues/6097>

So I added a retry on that step to the manifest.

**Pull request merged**
