### PR TITLE
ida-free@8.1: Fix (un)install scripts

### LINKED ISSUE #9421: ida-free 8.1 install failed
## Bug Report

**Package Name:** ida-free

### Current Behaviour

```
$ sudo scoop install ida-free
```

Installation aborted

屏幕截图 2022-10-08 143106

### Expected Behaviour

install success

### Additional context/output

```
Installing 'ida-free' (8.1) [64bit] from extras bucket
Loading idafree81_windows.exe from cache
Checking hash of idafree81_windows.exe ... ok.
Running pre_install script...
Running installer... error.
ERROR Exit code was 1!
Installation aborted. You might need to run 'scoop uninstall ida-free' before trying again.
```

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:**7.2.6

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
//# Your configuration here
```

### PR DESCRIPTION
**Pull request by HUMORCE**
Closes #9421 #9436

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by HUMORCE** [comment]
the manifest is currently working, but I think it is affected by bug, reported here: https://github.com/ScoopInstaller/Scoop/issues/5231

**Comment by Zliced13** [comment]
@HUMORCE there was a reason I changed, the `installer.script` property.  The `"args"` variable of the property does not work properly, which is why I used `"script"` instead.

**Comment by HUMORCE** [comment]
I made this PR because you used `sleep` in script, which also caused the installation fail.

**Comment by Zliced13** [comment]
Oh, so that's why, carry on with your day then, my bad.

**Pull request merged**
