### PR TITLE
trilium: Add persistent data

### LINKED ISSUE #4822: trilium: add Persistent data
Locations in scoop-extras: https://github.com/lukesampson/scoop-extras/blob/master/bucket/trilium.json

Project page: https://github.com/zadam/trilium

Wiki: https://github.com/zadam/trilium/wiki/Data-directory#changing-the-location-of-data-directory

### PR DESCRIPTION
**Pull request by shelmor**
- Closes #4822 

1. Update to the latest version (not sure why it wasn't already..)
2. Add persistent data as per [their wiki](https://github.com/zadam/trilium/wiki/Data-directory#changing-the-location-of-data-directory) and attempt to migrate existing configuration from AppData\Roaming to $persist_dir

Also I feel like renaming the existing `trilium-data` folder in AppData\Roaming to `trilium-data.old` or something like that to prevent possible confusion. It's not a big deal though. Thoughts?

### CODE REVIEW

**Comment by rashil2000** [comment]
> Also I feel like renaming the existing trilium-data folder in AppData\Roaming to trilium-data.old or something like that to prevent possible confusion. It's not a big deal though. Thoughts?

If both \<package folder\>/trilium-data and %AppData%/trilium-data exist, which one will trilium prefer?

**Comment by shelmor** [comment]
> If both <package folder>/trilium-data and %AppData%/trilium-data exist, which one will trilium prefer?

That will depend on the `TRILIUM_DATA_DIR` environment variable, hence I added `env_set` to the manifest.

**Comment by rashil2000** [comment]
Okay, thanks for the info. Then I think no need to rename %AppData%/trilium-data.

**Pull request merged**
