### PR TITLE
ipfilter-updater: Fix homepage

### PR DESCRIPTION
**Pull request by brian6932**
- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by brian6932** [comment]
While I'm at it, I may as well improve the checkver

**Comment by brian6932** [comment]
@rasa Can you merge this when you get the chance? pretty small PR

**Comment by brian6932** [comment]
@niheaven The reason \S was used was so the -beta flags would count, as they did previously when the checkver was \w

**Comment by niheaven** [comment]
The tag itself contains `beta`, and the regex extracts everything.

**Comment by niheaven** [comment]
CleanShot 2022-11-13 at 03 02 10@2x

**Comment by brian6932** [comment]
Oh I wasn't aware, ok np

**Pull request merged**
