### PR TITLE
session@1.11.4: url fix (#11848)

### LINKED ISSUE #11848: [Bug]: session 1.11.1 changed naming convetion, files are not found
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

session

### Expected/Current Behaviour

Session gets installed properly or if not, bot does not close the issue; maybe a bug in the bot itself.

### Steps to Reproduce

```console
please see #11847
```

### Possible Solution

please see #11847

### Scoop and Buckets Version

```console
N/A
```

### Scoop Config

```console
N/A
```

### PowerShell Version

```console
N/A
```

### Additional Softwares

_No response_

### PR DESCRIPTION
**Pull request by Elkiwa**
Closes #11848
Relates to #11847

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by redactedscribe** [comment]
Still a problem for v1.11.4.

Hope to see this simple four character fix get merged soon.

**Review by HUMORCE — APPROVED** [review]

**Pull request merged**
