### PR TITLE
foxit-reader: Copied from 'foxit-pdf-reader'

### LINKED ISSUE #9629: foxit has duplicate packages?
## Bug Report

extras/foxit-pdf-reader and extras/foxit-reader

### Current Behaviour

It seems that [extras/foxit-pdf-reader](https://github.com/ScoopInstaller/Extras/blob/master/bucket/foxit-pdf-reader.json) has a newer version (12.0.1.12430) than [foxit-reader](https://github.com/ScoopInstaller/Extras/blob/master/bucket/foxit-reader.json) (10.0.0.35798).  Are both needed?

### Possible Solution

Remove/deprecate the older package?

### PR DESCRIPTION
**Pull request by niheaven**
- Closes #9629

Will be removed after scoop supports manifest alias feature.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by HUMORCE** [comment]
out of date

**Comment by niheaven** [comment]
@HUMORCE Why 'out of date'?

**Comment by niheaven** [comment]
The foxit-pdf-reader could not be updated, nor this copied one.

**Pull request merged**
