### PR TITLE
foxmail@7.2.25.245: Update pre_install script

### PR DESCRIPTION
**Pull request by b4imetu**
Closes #XXXX

Relates to #XXXX

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by b4imetu** [comment]
@aliesbelik Checkver and Autoupdate failed, help plz

**Comment by aliesbelik** [comment]
> @aliesbelik Checkver and Autoupdate failed, help plz

Fixed in fdbb1c8.

My fault: checked locally only with PS 7.x, using `-SkipHttpErrorCheck` seems to cause failure with PS 5.x (?) during scheduled update action execution:

```
Invoke-WebRequest : A parameter cannot be found that matches parameter name 'SkipHttpErrorCheck'.
At line:2 char:88
+ ... aximumRedirection 0 -ErrorAction SilentlyContinue -SkipHttpErrorCheck
+                                                       ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
 
foxmail: couldn't match 'FoxmailSetup_([\d.]+)\.exe' in https://www.foxmail.com/
```

Successfully updated in master to the latest version:

```
foxmail: 7.2.25.245 (scoop version is 7.2.25.243) autoupdate available
Autoupdating foxmail
Downloading FoxmailSetup_7.2.25.245.exe to compute hashes!
Downloading https://dldir1.qq.com/foxmail/windows/FoxmailSetup_7.2.25.245.exe#/dl.7z (121.1 MB)...
Computed hash: 0d5b46d5d56e4d9f669c1d28a242a5df25a30ef5712eab581cebeee3fcc9cd95
Writing updated foxmail manifest
```

**Comment by b4imetu** [comment]
@aliesbelik Thank you for the fix
I also added the Line 14. Plz merge if you think that is ok

**Comment by aliesbelik** [comment]
Please update the PR with the changes from master first.

**Pull request merged**
