### PR TITLE
Fix hashes for qtemu@2.1

### PR DESCRIPTION
**Pull request by MagicalDrizzle**
It seems reporting hash error using the issues tab only make a lot generate [a](https://github.com/ScoopInstaller/Extras/issues/12552) [new](https://github.com/ScoopInstaller/Extras/issues/12571) [random](https://github.com/ScoopInstaller/Extras/issues/12572) [hash](https://github.com/ScoopInstaller/Extras/issues/12552) instead of actually fixing the error...
I fixed hash for the `qtemu@2.1` package here.

### CODE REVIEW

**Comment by MagicalDrizzle** [comment]
`curl`, `wget` and firefox both report the same file for me.
```
>wget -qO - https://web.archive.org/web/20210417194244/https://carlavilla.es/qtemu/qtemu_portable_x86_64.zip | busybox sha256sum
7999d54cc3b433de5299a5644e4d3f9d073636b243d2a3335af478c7fadd2e0e  -

>curl -Lso - https://web.archive.org/web/20210417194244/https://carlavilla.es/qtemu/qtemu_portable_x86_64.zip | busybox sha256sum
7999d54cc3b433de5299a5644e4d3f9d073636b243d2a3335af478c7fadd2e0e  -
```
It seems the hash check bot generated [*yet*](https://github.com/ScoopInstaller/Extras/pull/12574/conflicts) another different hash again?

**Comment by HUMORCE** [comment]
https://github.com/ScoopInstaller/Extras/pull/12367

Remove hash check instead of fixes. I don't know why its hash keeps changing, wasn't it archived in 2021?

**Comment by MagicalDrizzle** [comment]
> #12367
> 
> Remove hash check instead of fixes. I don't know why its hash keeps changing, wasn't it archived in 2021?

I wonder if it's either a bug with wayback machine, or a bug in the hash check bot.
Because whenever you report the hash being wrong, a bot will just simply "randomize" the hash.
Even the bot is faulty and only downloaded a html file/blank file for example, shouldn't the "wrong" hash stay constant at least?

**Comment by HUMORCE** [comment]
Preventing abusive, CDNs, etc. issues, because both users and bot may have downloaded the wrong file

**Pull request merged**
