### PR TITLE
vcredist2022: Update version info

### PR DESCRIPTION
**Pull request by b4imetu**
Closes #XXXX

Relates to #XXXX

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tech189** [comment]
Is there a way we can automatically get the latest version number rather than manually updating it?

**Comment by b4imetu** [comment]
Sorry, I don't know how to implement it, I'm a rookie in this Scoop project.

But I feel that the Scoop script is very difficult to implement for `vcredist2022`'s auto-update because the usual solution is not feasible.

Because `"autoupdate":` usually requires a static URL and $version information in the package name, but the `vcredist2022` package does not have either of these features.

I just modified it manually according to the previous update method.

**Comment by b4imetu** [comment]
Just a hotfix for #8732 Please merge at your convenience ^^ @issaclin32 @tech189

**Comment by issaclin32** [comment]
I am changing `version` to 14.32.31326 **.0** according to the file version.

vc

**Pull request merged**
