### PR TITLE
Add Microsoft Teams

### LINKED ISSUE #3595: [Request] Add Microsoft Teams
Teams is Microsoft's latest chat app for business.

https://teams.microsoft.com/downloads

### PR DESCRIPTION
**Pull request by rubendibattista**
This basically adds the manifest provided by @FriendlyNeighborhoodShane in #3595 + Autoupdate.

I tested the install and it works on my machine ™

Closes #3595

### CODE REVIEW

**Comment by FriendlyNeighborhoodShane** [comment]
Neat. Also I would like to point to you a suggestion I have about the `post_install` here https://github.com/ScoopInstaller/Extras/issues/7157#issuecomment-957349926, ICYMI

**Comment by rubendibattista** [comment]
Yeah, it's the first time I commit something to scoop. Can you point me to a documentation section documenting how to use a script within the repo instead of the inlined scripts in the manifest? Or even just an example with another manifest.

**Comment by rashil2000** [comment]
I think the post_install script is short enough, it's fine here.

**Review by rashil2000 — APPROVED** [review]

**Comment by rashil2000** [comment]
Rename microsoft-teams.json -> teams.json

**Comment by HUMORCE** [comment]
@rashil2000  i think the original name of the product should be retained.(micrsoft-teams)

see:
https://www.microsoft.com/en-us/microsoft-teams/download-app

**Comment by rashil2000** [comment]
I recommended that because of slack.json manifest

**Review by HUMORCE — APPROVED** [review]

**Pull request merged**
