### PR TITLE
sfss: Add version 1.0.0

### PR DESCRIPTION
**Pull request by jewlexx**
- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by HUMORCE** [comment]
`autoupdate.hash` is missing.

**Comment by jewlexx** [comment]
> autoupdate.hash is missing.

Is that just the same as the current version's hash?

**Comment by HUMORCE** [comment]
oh, you are the owner of the repo. I mention this because the sha256 value is including in the release notes, you created a file for hash checking, it also okay.

screenshot_20221028132001

...but the app does not seem to work on a 32bit OS.

> architecture: If the app has 32- and 64-bit versions, architecture can be used to wrap the differences ([example](https://github.com/ScoopInstaller/Main/blob/master/bucket/7zip.json)).
> 32bit|64bit: contains architecture-specific instructions (bin, checkver, extract_dir, hash, installer, pre_install, post_install, shortcuts, uninstaller, url, and msi [msi is deprecated]).
> 
> https://github.com/ScoopInstaller/Scoop/wiki/App-Manifests#optional-properties

**Comment by niheaven** [comment]
Yes, a 64bit app.

image

**Comment by niheaven** [comment]
image

**Comment by HUMORCE** [comment]
@niheaven you have forgotten to edit `autoupdate` part. while it works, but it does not meet the Standards.

> If the application provides only a 32bit download, the architecture field is not required. In all other cases, architecture field is mandatory.

**Comment by niheaven** [comment]
For autoupdate, non-arch one will update both, and this mechanism is designed. So if there's only 64bit arch, it is no need to use arch in autoupdate.

**Comment by HUMORCE** [comment]
I understand about that, but it does not mean that this meets the standards. this is part of all the other cases in the guide.

**Comment by jewlexx** [comment]
@HUMORCE I have added a 32bit version, and tested the downloads on my machine, and they seem to work fine

**Comment by niheaven** [comment]
> All the properties except autoupdate.note can be set globally for all architectures or for each architecture separately (under architecture.64bit or architecture.32bit). Global properties can be used to update each architectural properties, i.e., if only setted globally, autoupdate.url is used to update either architecture.64bit.url or architecture.32bit.url.

https://github.com/ScoopInstaller/Scoop/wiki/App-Manifest-Autoupdate#properties-of-autoupdate

@HUMORCE I mean this is *designed*, at east for `autoupdate` field. I preferred to use uniform url and hash if there's only one architecture to be updated, and of course, others could use nested from. There're no standards here.

**Comment by HUMORCE** [comment]
emmm, you are right. and I used the designed feature in this manifest when last edit. I simply thought a clear/explicit statement would be easier for more collaborators to read and edit.

**Pull request merged**
