### PR TITLE
alacritty@0.13.2: Add Open with Alacritty context menu

### LINKED ISSUE #12983: [Bug]: missing "Open Alacritty here" context menu entry
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

alacritty

### Expected/Current Behaviour

There is no context menu entry added after installing, unlike Alacritty's own installer[^1] does.

I would expect there to be a bundled registry file the user gets notified about when installing Alacritty, so they can import it afterwards to add the context menu entry.

[^1]: https://github.com/alacritty/alacritty/blob/master/alacritty/windows/wix/alacritty.wxs#L41-L49

### Steps to Reproduce

```console
scoop bucket add extras
scoop install extras/alacritty
```

### Possible Solution

Looking at other manifests, like Windows Terminal[^2], I believe the following is needed:
* `install-context.reg` and `uninstall-context.reg` files
* `post_install` and `pre_uninstall` hooks
* `notes` for informing the user about the `install-context.reg` file

See: https://github.com/ScoopInstaller/Extras/pull/12997

[^2]: https://github.com/ScoopInstaller/Extras/blob/master/bucket/windows-terminal.json

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
9e238aeb8 (HEAD -> master, origin/master, origin/HEAD) springboot: Update to version 3.2.4

'java' bucket:
c11b58e7 (HEAD -> master, origin/master, origin/HEAD) temurin17-nightly-jre: Update to version 17.0.11-7.0.ea

'main' bucket:
3b8aba5d0 (HEAD -> master, origin/master, origin/HEAD) llvm: Update to version 18.1.2

'nerd-fonts' bucket:
3811a43 (HEAD -> master, origin/master, origin/HEAD) SarasaGothic: Update to version 1.0.7
```

### Scoop Config

```console
last_update            scoop_branch scoop_repo
-----------            ------------ ----------
21/03/2024 03:21:00 PM master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Additional Softwares

_No response_

### PR DESCRIPTION
**Pull request by jenbroek**
Adds a bundled registry file to optionally add an "Open Alacritty here" context menu entry just as Alacritty's own installer[^1] does.

Closes #12983

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

[^1]: https://github.com/alacritty/alacritty/blob/master/alacritty/windows/wix/alacritty.wxs#L41-L49

### CODE REVIEW

**Comment by jenbroek** [comment]
@aliesbelik (or an other maintainer) any chance you could take a look at this?

**Comment by rafaeloledo** [comment]
Upvote, i'll be good to add entries on the reg file to open directly on the folder icon.

install.reg
```reg
[HKEY_CURRENT_USER\Software\Classes\Directory\shell\Open with &Alacritty]
@="Open with &Alacritty"
"Icon"="$alacrittyPath"
[HKEY_CURRENT_USER\Software\Classes\Directory\shell\Open with &Alacritty\command]
@="\"$alacritty\" --working-directory \"%v\""
```
uninstall.reg
```reg
[-HKEY_CURRENT_USER\Software\Classes\Directory\shell\Open with &Alacritty]
[-HKEY_CURRENT_USER\Software\Classes\Directory\shell\Open with &Alacritty\command]
```

there's the `diff` from my PR that you can merge if you want
currently the phrase is `Open with Alacritty`

**Review by niheaven — APPROVED** [review]

**Pull request merged**
