### PR TITLE
Fix mp3tag json, issue 10166

### LINKED ISSUE #10166: [Bug]: mp3tag package does not work correctly (PR attached)
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

mp3tag

### Expected/Current Behaviour

(I have written a PR that fixes the issue here, https://github.com/ScoopInstaller/Extras/pull/10167)

There are no issues installing/uninstalling, but the program does not function well (the application can't be used because the left panel is blank).

Installing the package `extras/mp3tag` and running it:

before

Note that the left panel is blank except for a cd icon. The application can't really be used and I didn't see a way in the menus to get the left panel back.

Installing the package `anderlli0053_DEV-tools/mp3tag_fixed` and running it:

after

This is the correct expected view and everything works.

I've opened a PR to copy the fixed version in, https://github.com/ScoopInstaller/Extras/pull/10167

### Steps to Reproduce

```console
scoop install extras/mp3tag
(mp3 tag doesn't work)
scoop uninstall mp3tag
scoop install anderlli0053_DEV-tools/mp3tag_fixed
(mp3 tag does work)
```

### Possible Solution

Yes, I have a PR

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'anderlli0053_DEV-tools' bucket:
8efefe9d9 (HEAD -> master) swift-snapshot: Update to version snapshot-2022-12-19-a

'extras' bucket:
f8704bbd4 (HEAD -> master, origin/master, origin/HEAD) waifu2x-extension-gui: Update to version 3.98.01

'games' bucket:
7848ea79 (HEAD -> master, origin/master, origin/HEAD) yuzu: Update to version 0-1292

'main' bucket:
4a2b884b2 (HEAD -> master, origin/master, origin/HEAD) goreleaser: Update to version 1.14.1

'ocdc' bucket:
caecf1b (HEAD -> main, origin/main, origin/HEAD) Updated apps
```

### Scoop Config

```console
last_update                       scoop_branch scoop_repo
-----------                       ------------ ----------
2023-01-02T11:14:28.6942674-08:00 master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.22621.963
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.963
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Additional Softwares

I've never installed mp3tag before on this machine, and so I don't think there's any interference from other software/other previous versions of it around.

(I have written a PR that fixes the issue here, https://github.com/ScoopInstaller/Extras/pull/10167)

### PR DESCRIPTION
**Pull request by moltenform**
Replace the contents of mp3tag.json with the corrected version, which I found here, https://raw.githubusercontent.com/anderlli0053/DEV-tools/master/added_to_official_repository/mp3tag_fixed.json As described in https://github.com/ScoopInstaller/Extras/issues/10166 mp3tag does not work correctly without this change. Thanks @anderlli0053 for including the fix in your repo.

Closes #10166 on the Extras repo.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by moltenform** [comment]
Ping, any issues, can this get merged?

**Comment by benf-write** [comment]
Interesting... if the only functionality changes were in `pre_uninstall`, I wonder what causes the installation difference.

**Comment by Zliced13** [comment]
In the `pre_uninstall` script, try adding `Stop-Process -Name 'explorer'` in the line before the `Start-Sleep` function. This should help with removing the context menu, and eliminating errors as well.

**Review by HUMORCE — APPROVED** [review]

**Comment by HUMORCE** [comment]
I didn't test it, but it looks like you guys think this fixes it.

**Pull request merged**
