### PR TITLE
autohotkey@2.0.2: Path escape 

### PR DESCRIPTION
**Pull request by HUMORCE**
Relates to https://github.com/ScoopInstaller/Extras/commit/3bdc740916fbb64121df51b2bcc051501e9bd6f6#commitcomment-95121357

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
When installing, this popped up and I chose "Yes".

image

Installation proceeded successfully. But then I ran my usual script, and this popped up: 
image

What happens if I select "Yes" here? If it downloads v1.1.36.02, will it persist across updates made to Autohotkey by Scoop?

**Comment by rashil2000** [comment]
> Have you installed AHK with official installer before? I have not tested this case

No, I have only installed it using Scoop.

> All sub-versions will be uninstalled.

Then we need a way to persist it, right? Otherwise users will have to download specific versions again and again.

----

Another question: do autohotkey developers actually recommend updating packages to v2? There seems to be no backward compatibility at the moment.

**Comment by HUMORCE** [comment]
> No, I have only installed it using Scoop.

unknown factors..

> Then we need a way to persist it, right? Otherwise users will have to download specific versions again and again.

I will do this in another PR.

> Another question: do autohotkey developers actually recommend updating packages to v2? There seems to be no backward compatibility at the moment.

I have not used AHK for quite time, so I am not sure about that. but the launcher of v2 contains script version detection.

refer. #10066

**Comment by rashil2000** [comment]
> I will do this in another PR.

Yes, please do! It is very essential.

**Pull request merged**
