### PR TITLE
Update Inkscape to 1.1.1 and fix autoupdate

### LINKED ISSUE #6912: [Request] update inkscape to v1.1.1
Could you please update inkscape to 1.1.1?
I noticed that the 32-bit 7z builds are not there anymore.

https://inkscape.org/release/1.1.1/platforms/

### PR DESCRIPTION
**Pull request by tech189**
Closes #6912

- Updates to version 1.1.1
- Removes hash because it's not provided for compressed releases
- Fixes autoupdate using a script inspired by [Chocolatey's](https://github.com/chocolatey-community/chocolatey-packages/blob/master/automatic/inkscape/update.ps1)
- Changes 32bit from 7z to .paf.exe because compressed release not provided

---

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tech189** [comment]
Hmm tests don't like autoupdate urls not being actual urls. But I've tested autoupdate works fine.
```
...
    "64bit": {
        "url": "$matchWin64biturl"
    },
    "32bit": {
        "url": "$matchWin32biturl#/dl.7z"
    }
...
```

**Comment by rashil2000** [comment]
You can construct the URL in autoupdate itself, using variables. Try if that works.

**Comment by tech189** [comment]
Strange... the Appveyor checks pass but github actions don't. Where is the log for the github actions checks?

**Comment by rashil2000** [comment]
The Actions tab

**Comment by tech189** [comment]
Found them at https://github.com/ScoopInstaller/Extras/actions/runs/1616456330 but it says it's passed!

**Comment by rashil2000** [comment]
This is the one https://github.com/ScoopInstaller/Extras/actions/runs/1616443161

**Comment by tech189** [comment]
I can't see the reason for failure it seems to get the version okay:
```

INFO: Checkver

Log of Output:

    GET with 0-byte payload 
    received 18861-byte response of content type text/html 
    GET with 0-byte payload 
    received 18800-byte response of content type text/html 
    inkscape:  
    1.1.1 
     (scoop version is 1.1.1) 
     
    Forcing autoupdate! 
    Autoupdating inkscape 
    Downloading  
    InkscapePortable_1.1.1.paf.exe 
     to compute hashes! 
    Downloading inkscape.org/en/gallery/item/29417/InkscapePortable_1.1.1.paf.exe#/dl.7z (87.6 MB)... 
    Computed hash:  
    657ea0d03a9b2fe5e2d3259bf7c802c2eb37e7c5a04e83d4005dacec0d508399 
    Downloading  
    inkscape-1.1.1_2021-09-20_3bf5ae0d25-x64.7z 
     to compute hashes! 
    Downloading inkscape.org/en/gallery/item/29349/inkscape-1.1.1_2021-09-20_3bf5ae0d25-x64.7z (80.2 MB)... 
    Computed hash:  
    e54263167cd0745c5613cd692aadc4b31e2054b69029ab6618982cae64be4d63 
    Writing updated inkscape manifest

INFO: Checkver done
```

**Comment by rashil2000** [comment]
No idea...

@issaclin32 any guesses?

**Comment by issaclin32** [comment]
I think the problem is that the following output is interpreted as a part of **checkver output**, causing PR checks thinking that some error is happening.
```
GET with 0-byte payload 
    received 18861-byte response of content type text/html 
    GET with 0-byte payload 
    received 18800-byte response of content type text/html 
```
related code: https://github.com/ScoopInstaller/Scoop-GithubActions/blob/main/src/Action/PR.psm1#L191

**Review by issaclin32 — APPROVED** [review]

**Comment by rashil2000** [comment]
Try the same workaround as https://github.com/ScoopInstaller/Versions/pull/356#issuecomment-1000645232

**Comment by LazyGeniusMan** [comment]
> related code: https://github.com/ScoopInstaller/Scoop-GithubActions/blob/main/src/Action/PR.psm1#L191

@issaclin32 I made a PR to fix this on https://github.com/ScoopInstaller/Scoop-GithubActions/pull/2 , Could you check it?

**Pull request merged**
