### PR TITLE
Gisto: Add version 1.13.4 

### PR DESCRIPTION
**Pull request by Baneeishaque**
Gisto is a Cross-platform snippets management desktop application that allows you and/or your team share code snippets fast and easily.

Homepage
http://www.gistoapp.com/

Download Link(s)
https://github.com/Gisto/Gisto/releases

Some Indication of Popularity/Repute
969 stars, 96 forks

Closes [#10293 ](https://github.com/ScoopInstaller/Extras/issues/10293)

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Zliced13** [comment]
Suggestion: You could use the other [Windows package](https://github.com/Gisto/Gisto/releases/download/v1.13.4/Gisto-1.13.4.exe) instead, as there is a dedicated sha512 hash for that installer in the latest release [here](https://github.com/Gisto/Gisto/releases/download/v1.13.4/latest.yml). Doing this will make the **github-actions** job easier as it doesn't have to download the file every time to calculate the hashes.

**Comment by Baneeishaque** [comment]
> Suggestion: You could use the other [Windows package](https://github.com/Gisto/Gisto/releases/download/v1.13.4/Gisto-1.13.4.exe) instead, as there is a dedicated sha512 hash for that installer in the latest release [here](https://github.com/Gisto/Gisto/releases/download/v1.13.4/latest.yml). Doing this will make the **github-actions** job easier as it doesn't have to download the file every time to calculate the hashes.

let me try...

**Comment by Zliced13** [comment]
If you need help, feel free to ask me?

**Comment by Baneeishaque** [comment]
I prepared an App Manifest using the other [Windows package](https://github.com/Gisto/Gisto/releases/download/v1.13.4/Gisto-1.13.4.exe). It uses the dedicated sha512 hash for that installer in the latest release informative yml file : https://github.com/Gisto/Gisto/releases/download/v1.13.4/latest.yml.

See this...

`{
    "version": "1.13.4",
    "description": "Gisto is a code snippet manager that runs on GitHub Gists and adds additional features such as searching, tagging and sharing gists while including a rich code editor. All your data is stored on GitHub and you can access it from GitHub Gists at any time with changes carrying over to Gisto.",
    "homepage": "http://www.gistoapp.com/",
    "license": "MIT",
    "url": "https://github.com/Gisto/Gisto/releases/download/v1.13.4/Gisto-1.13.4.exe#/dl.7z",
    "hash": "sha512:dd61b72e1caafe463dea366453264fd1c5adde1350ed74b60554738f7cf4e6bc81a720efdd4cbb50a3b662cbeec6e300b92e1607029376bd54f699198a0b1336",
    "shortcuts": [
        [
            "gisto.exe",
            "Gisto"
        ]
    ],
    "checkver": {
        "github": "https://github.com/Gisto/Gisto"
    },
    "autoupdate": {
        "url": "https://github.com/Gisto/Gisto/releases/download/v$version/Gisto-$version.exe#/dl.7z",
        "hash": {
            "url": "$baseurl/latest.yml",
            "regex": "sha512: (.+)"
        }
    }
}
`

image

The Problems are...

1. The base64 encoded SHA512 hash on latest.yml is incorrect for the executable file (**checkver.ps1 says hash is 8f941801e93a5825b3691dbaabc619b87d0ca45d78f1d83a31f1134aa987121d250d967cab8a09dc7fa6b925ec9148d96d8fd680b461ad2d16d81f6bb6d0c0d1 - but it is actually dd61b72e1caafe463dea366453264fd1c5adde1350ed74b60554738f7cf4e6bc81a720efdd4cbb50a3b662cbeec6e300b92e1607029376bd54f699198a0b1336**). But, we can hope the developer will fix it on next update - and simply by pass by commenting out the auto update hash section or using --skip argument of the install function.

2. The installation is not success, Reasons ...
image
image
image

The decompression folder not directly contains the executables, files\$PLUGINSDIR contains app-32 / 64 7z achieves - the executables are packaged as app-32 / 64 7z archives. I think - extraction of any one of this archive from the installation exe file is beyond the scope of current scoop implementation - correct me if i am wrong. 

So, i am decided to go with portable package.

**Comment by Baneeishaque** [comment]
I accidently deleted my branch, and the pull request automatically closed. Now, i am restored my branch - Please reopen this pull request @Zliced13.

**Comment by Zliced13** [comment]
Sorry I can't do anything about that, you would have to open another PR for that to happen.

**Comment by aliesbelik** [comment]
@Baneeishaque please re-submit PR if it still actual.
Would be fine to merge it finally.

**Comment by Baneeishaque** [comment]
> I prepared an App Manifest using the other [Windows package](https://github.com/Gisto/Gisto/releases/download/v1.13.4/Gisto-1.13.4.exe). It uses the dedicated sha512 hash for that installer in the latest release informative yml file : https://github.com/Gisto/Gisto/releases/download/v1.13.4/latest.yml.
> 
> See this...
> 
> `{ "version": "1.13.4", "description": "Gisto is a code snippet manager that runs on GitHub Gists and adds additional features such as searching, tagging and sharing gists while including a rich code editor. All your data is stored on GitHub and you can access it from GitHub Gists at any time with changes carrying over to Gisto.", "homepage": "http://www.gistoapp.com/", "license": "MIT", "url": "https://github.com/Gisto/Gisto/releases/download/v1.13.4/Gisto-1.13.4.exe#/dl.7z", "hash": "sha512:dd61b72e1caafe463dea366453264fd1c5adde1350ed74b60554738f7cf4e6bc81a720efdd4cbb50a3b662cbeec6e300b92e1607029376bd54f699198a0b1336", "shortcuts": [ [ "gisto.exe", "Gisto" ] ], "checkver": { "github": "https://github.com/Gisto/Gisto" }, "autoupdate": { "url": "https://github.com/Gisto/Gisto/releases/download/v$version/Gisto-$version.exe#/dl.7z", "hash": { "url": "$baseurl/latest.yml", "regex": "sha512: (.+)" } } } `
> 
> image
> 
> The Problems are...
> 
> 1. The base64 encoded SHA512 hash on latest.yml is incorrect for the executable file (**checkver.ps1 says hash is 8f941801e93a5825b3691dbaabc619b87d0ca45d78f1d83a31f1134aa987121d250d967cab8a09dc7fa6b925ec9148d96d8fd680b461ad2d16d81f6bb6d0c0d1 - but it is actually dd61b72e1caafe463dea366453264fd1c5adde1350ed74b60554738f7cf4e6bc81a720efdd4cbb50a3b662cbeec6e300b92e1607029376bd54f699198a0b1336**). But, we can hope the developer will fix it on next update - and simply by pass by commenting out the auto update hash section or using --skip argument of the install function.
> 2. The installation is not success, Reasons ...
> 
> image
> 
> image
> 
> image
> 
> The decompression folder not directly contains the executables, files$PLUGINSDIR contains app-32 / 64 7z achieves - the executables are packaged as app-32 / 64 7z archives. I think - extraction of any one of this archive from the installation exe file is beyond the scope of current scoop implementation - correct me if i am wrong.
> 
> **So, i am decided to go with portable package.**

Actually the decompression can be performed by a PowerShell script.

But, I think the author abandoned Gisto. Currently, it's website is not working (may be domain expired). And web app is stopped working (It may a side effect of non functional domain. The last commit is 2 years ago.

Anyway, i am planning to release gisto-portable & gisto. The Gisto Portable uses Portable Executable & Gisto uses packaged executable (I think, it is electron packager). Moreover, I already have gisto-np which uses system wide windows installer.

**Pull request closed without merging**
