### PR TITLE
qq-nt: Add version 9.9.16.241121

### PR DESCRIPTION
**Pull request by cscnk52**
Closes https://github.com/ScoopInstaller/Extras/issues/13886
Closes https://github.com/ScoopInstaller/Extras/issues/12803
Closes https://github.com/ScoopInstaller/Extras/pull/12866
Closes https://github.com/ScoopInstaller/Extras/pull/11546

Relates https://github.com/ScoopInstaller/Extras/pull/11329 
Relates https://github.com/ScoopInstaller/Extras/pull/11554 

seem like the script in https://github.com/ScoopInstaller/Extras/pull/11546 is not valid for current version qqnt, I'm not add persist script in my PR.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aliesbelik** [comment]
Closes #12803.

**Comment by cscnk52** [comment]
@aliesbelik consider merge this PR?

**Pull request merged**
