### PR TITLE
nheko: Add version 0.10.1

### PR DESCRIPTION
**Pull request by SonaliBendre**
Closes #XXXX

Relates to #XXXX

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by issaclin32** [comment]
This should go to the [Nonportable bucket](https://github.com/ScoopInstaller/Nonportable/).

**Comment by SonaliBendre** [comment]
anyway to make it portable?

**Comment by issaclin32** [comment]
> anyway to make it portable?

I couldn't find a proper way to extract the installer without installing it.

**Comment by SonaliBendre** [comment]
@issaclin32 https://matrix-static.neko.dev/room/!TshDrgpBNBDmfDeEGN:neko.dev/?anchor=$kvUuh6yav6FRPIlnkY-YeKkMP_k8eP5ILNR1aEFMJRg&offset=30

**Comment by SonaliBendre** [comment]
https://matrix-static.neko.dev/room/!TshDrgpBNBDmfDeEGN:neko.dev/

**Comment by issaclin32** [comment]
> https://matrix-static.neko.dev/room/!TshDrgpBNBDmfDeEGN:neko.dev/

Thanks for the link, but the zip file for **stable version** (commit `7df260f`) is expired and not able to download.

I have added [nheko-nightly](https://github.com/ScoopInstaller/Versions/blob/master/bucket/nheko-nightly.json) to the Versions bucket.

**Comment by issaclin32** [comment]
> @issaclin32 https://github.com/Nheko-Reborn/nheko/releases/tag/v0.10.1 https://github.com/Nheko-Reborn/nheko/releases/download/v0.10.1/nheko-win64-without-installer-v0.10.1.zip

Thanks for the update.

**Pull request merged**
