### PR TITLE
modern7z: Add version 1.8.7

### PR DESCRIPTION
**Pull request by moshg**

### CODE REVIEW

**Comment by moshg** [comment]
We don't need reinstallation after https://github.com/ScoopInstaller/Main/pull/1797.

**Comment by rashil2000** [comment]
/verify

Please do not use aliases in PowerShell scripts - rm, ls, cp, ni. Use the full names.

**Review by rashil2000 — CHANGES_REQUESTED** [review]
Please do not use aliases in PowerShell scripts - rm, ls, cp, ni. Use the full names.

**Review by rashil2000 — APPROVED** [review]

**Comment by niheaven** [comment]
Move this PR to https://github.com/ScoopInstaller/Main

**Pull request closed without merging**
