### PR TITLE
qrscan: Fix `extract_dir` error

### LINKED ISSUE #9321: json bucket manifest typo for package qrscan
Seems like bot code to create manifest definition update/commit has a bug that introduces typo.

20220925
update / install failed on qrscan

typo in 
https://github.com/ScoopInstaller/Extras/blob/master/bucket/qrscan.json 
"version": "0.1.7",
typo in recent commit on 20220923
https://github.com/ScoopInstaller/Extras/blob/6d13834591da90dd2d712fe0e6489acc61dce690/bucket/qrscan.json

correction needed change 0.1.6 to 0.1.7 on line 16
```
<    "extract_dir": "qrscan-0.1.6",
>    "extract_dir": "qrscan-0.1.6",
```
log before correcting
```
PS C:\vol\scoop_01\scoopg> scoop install qrscan
WARN  Purging previous failed installation of qrscan.
ERROR 'qrscan' isn't installed correctly.
Removing older version (0.1.7).
'qrscan' was uninstalled.
Installing 'qrscan' (0.1.7) [64bit] from extras bucket
Loading qrscan-0.1.7-x86_64-pc-windows-msvc.zip from cache
Checking hash of qrscan-0.1.7-x86_64-pc-windows-msvc.zip ... ok.
Extracting qrscan-0.1.7-x86_64-pc-windows-msvc.zip ... Could not find 'qrscan-0.1.6'! (error 16)
At C:\vol\scoop_01\SCOOP\apps\scoop\current\lib\core.ps1:642 char:9
+         throw "Could not find '$(fname $from)'! (error $($proc.ExitCo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find ....6'! (error 16):String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find 'qrscan-0.1.6'! (error 16)

```
After correcting install went smoothly

### PR DESCRIPTION
**Pull request by sitiom**
Closes #9321

Forgot to add it to autoupdate

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by KrisSchneider** [comment]
Do you mind adding this to your first message:

Closes #9321

**Comment by sitiom** [comment]
> Do you mind adding this to your first message:
> 
> Closes #9321

Done. Just a note that this PR came out first before that issue.

**Comment by KrisSchneider** [comment]
Oh I forgot that this PR was before that issue. My bad

**Review by chawyehsu — APPROVED** [review]

**Pull request merged**
