### PR TITLE
live777: Add version 0.3.1

### PR DESCRIPTION
**Pull request by Yin-ZP**
Closes #XXXX

Relates to #XXXX

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Yin-ZP** [comment]
> [Your changes do not pass checks.](https://github.com/ScoopInstaller/GithubActions/wiki/Pull-Request-Checks)
> 
> ### live777
> * [x]  Description
> * [x]  License
> * [x]  Hashes
> * [x]  Checkver
> * [x]  Autoupdate

why it didn't pass? what mistake i made?please tell me

**Comment by Yin-ZP** [comment]
> /verify
What does this mean?Only Description and Checkver didn't pass?or all of these five content didn't pass?
image
Thanks!

**Comment by HUMORCE** [comment]
> why it didn't pass? what mistake i made?please tell me

- Description: typo ``
- Checkver: don't know, wrong JSON syntax caused maybe

I have edited the manifest as a reference.

Local Tests: (git flow is ignored here, )
```
> cd ~\scoop\buckets\<bucket_name>
> ls bin -Name
checkhashes.ps1
checkurls.ps1
checkver.ps1    # mainly
formatjson.ps1

> bin\checkver -app <manifest_name> -f
> scoop install <manifest_name>; scoop uninstall <manifest_name>
```

**Review by HUMORCE — APPROVED** [review]

**Pull request merged**
