### PR TITLE
ab-av1: Add version 0.7.13

### LINKED ISSUE #12774: [Request]: ab-av1
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

ab-av1

### Description

AV1 re-encoding using ffmpeg, svt-av1 & vmaf.

### Homepage

https://github.com/alexheretic/ab-av1

### Download Link(s)

https://github.com/alexheretic/ab-av1/releases/download/v0.7.13/ab-av1.exe

### Some Indication of Popularity/Repute

311 Stars
26 Forks

### PR DESCRIPTION
**Pull request by mpe85**
Closes #12774

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mpe85** [comment]
Hi, @aliesbelik why was the commit in this PR removed by a force-push and hence not merged into master? Is it rejected?

**Comment by aliesbelik** [comment]
Hi, @mpe85.
I'm puzzled a bit why this happens.
As a newbie maintainer here I could be not aware of some settings, but looks like both your PRs (#12771 as well) were closed by this bot.
No, it wasn't rejected, by I could not reopen it.
If you will submit for the third time (sorry) try maybe from separate branch, not from the master.

@HUMORCE, @rashil2000, could you possibly comment?

**Comment by amreus** [comment]
@mpe85 Did you sync your fork of this repo before the pull request was merged? If so, that could have deleted the changes you made. 

Recommend to use a unique, separate branch for each pull request you make. That way if you syn the `main` branch it will not modify your pull request.  The branches can be safely deleted after being merged into Scoop/Extras.

**Comment by amreus** [comment]
@mpe85 it appears you installed an automatic pull bot to your github account: https://github.com/apps/pull

The bot is what deleted your pull request.

Use a branch to submit your pull request, or disable the bot.

**Comment by mpe85** [comment]
@amreus Thanks for pointing this out. I was not aware that this bot is active on my fork.
I will create another PR with the bot disabled and using a branch other than master.

**Pull request merged**
