### PR TITLE
ludwig: Add version 2.1.1

### LINKED ISSUE #9326: [Request]  Ludwig
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [x] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [x] the latest stable version of the program

### Information

**Name:** Ludwig 

**Description:** Ludwig is a unique search engine that helps you find the right English sentences and to feel more confident about it!

**Homepage:** https://ludwig.guru

**Download link(s):** https://ludwig.guru/download

### PR DESCRIPTION
**Pull request by Zliced13**
Closes #9326

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Zliced13** [comment]
@niheaven why is /verify not working?

**Review by HUMORCE — APPROVED** [review]
Tested.

**Pull request merged**
