### PR TITLE
raindrop.io: Add version 5.5.5

### PR DESCRIPTION
**Pull request by hu3rror**
Relates to #8849

The issue mentions that the license is MIT, but I can't find the source information, so I'm using Unknown for now.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by issaclin32** [comment]
I think the author of the issue misunderstood [MIT license in the Clipper extension](https://github.com/raindropio/extensions/blob/master/package.json) as MIT license for the app.

**Comment by issaclin32** [comment]
config location: `$Env:AppData\Raindrop.io`
(This is a reminder. No need to modify anything regard to this.)

**Review by issaclin32 — APPROVED** [review]

**Comment by KrisSchneider** [comment]
I think you should change the license for 'Unknown' to 'Proprietary'. I have tried to find the source code license myself, but all I get are these ISC and MIT licenses.
https://github.com/raindropio/app/search?q=License

**Comment by issaclin32** [comment]
> I think you should change the license from 'Unknown' to 'Proprietary'. I have tried to find the source code license myself, but all I get are these ISC and MIT licenses. https://github.com/raindropio/app/search?q=License

I am not an expert on licenses, but I think `Freeware` is okay for this case. What do you think?

**Comment by KrisSchneider** [comment]
I think freeware works fine.

**Comment by issaclin32** [comment]
Changed to `Freeware` in https://github.com/ScoopInstaller/Extras/commit/4b7c33a0b22bb116f7f0908ebbd03a733bda5d45.

**Pull request merged**
