### PR TITLE
nconvert: Add version 7.121

### PR DESCRIPTION
**Pull request by Zliced13**
- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by niheaven** [comment]
Move it to main bucket

**Comment by Zliced13** [comment]
It's not open source, so I don't it fits the criteria of the main bucket.

**Comment by niheaven** [comment]
It is provided as FREEWARE, so it's okay.

BTW, license should be `Freeware`.

**Comment by Zliced13** [comment]
Got it, closing this PR.

**Pull request closed without merging**
