### PR TITLE
added google assistant

### LINKED ISSUE #8173: [Request] Google-Assistant-Unofficial-Desktop-Client
## Package Request
https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client
### Information

**Name:** Google-Assistant-Unofficial-Desktop-Client

**Description:** Google Assistant for Desktop

**Homepage:** https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client

**Download link(s):** https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/releases

**Some indication of popularity/repute:** 2.7k Github Stars

Can provide PR

### PR DESCRIPTION
**Pull request by Console32**
Closes #8173

Relates to #XXXX

- [ x ] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
It might be possible to extract the installer, instead of running it. Can you try it?

**Comment by rashil2000** [comment]
Please create the PR from a new branch other than `master`

**Comment by rashil2000** [comment]
Closing because of unrelated changes...

**Comment by Console32** [comment]
@rashil2000 will create a new one, not called master. What do you mean by extracting the installer instead of running it?

**Pull request closed without merging**
