### PR TITLE
gitextensions: Update to version 4.0.1 and fix

### PR DESCRIPTION
**Pull request by ClassicDarkChocolate**
- Description is from official.
- `gitex` is the correct name in [document](https://git-extensions-documentation.readthedocs.io/en/release-4.0/command_line.html)
- checkver by script (relates to https://github.com/ScoopInstaller/Scoop/issues/5190)

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by val1984** [comment]
Hi @ClassicDarkChocolate,
I made a similar PR #10085
Do you think we can merge them?

**Comment by ClassicDarkChocolate** [comment]
> Hi @ClassicDarkChocolate, I made a similar PR #10085 Do you think we can merge them?

Hi, your autoupdate will not work, because there's [a scoop bug](https://github.com/ScoopInstaller/Scoop/issues/5190) currently.

**Comment by val1984** [comment]
And yet it did work on this run of excavate: https://github.com/val1984/scoop-main-alternative-location/actions/runs/3756972758/jobs/6383655701

**Comment by ClassicDarkChocolate** [comment]
> And yet it did work on this run of excavate: https://github.com/val1984/scoop-main-alternative-location/actions/runs/3756972758/jobs/6383655701
> 
> I initialized this repo from scoop bucket template.

Have you tried run `bin/checkver.ps1`? Though the maintainer have already merged yours.

**Comment by val1984** [comment]
Autoupdate [worked](https://github.com/ScoopInstaller/Extras/commit/bd5999563d7e593d29d6681cb8c48ce60da6aaa4) :)

**Pull request closed without merging**
