### PR TITLE
autoruns: Add version 14.09

### PR DESCRIPTION
**Pull request by cloudmaker97**
Added a manifest for an utility from windows: "This utility, which has the most comprehensive knowledge of auto-starting locations of any startup monitor, shows you what programs are configured to run during system bootup or login, and when you start various built-in Windows applications like Internet Explorer, Explorer and media players. These programs and drivers include ones in your startup folder, Run, RunOnce, and other Registry keys. Autoruns reports Explorer shell extensions, toolbars, browser helper objects, Winlogon notifications, auto-start services, and much more. Autoruns goes way beyond other autostart utilities."

https://docs.microsoft.com/en-us/sysinternals/downloads/autoruns

- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cloudmaker97** [comment]
Oh, i forgot to implement "checkver". I should amend that.

**Comment by cloudmaker97** [comment]
Hmm, okay. Didn't see that. `scoop search autoruns` delivered me no output. Sad that it's not searching in the shortcut descriptions for it, so this wouldn't so confusing and misleading. 🙂

**Comment by rasa** [comment]
That's an excellent point. scoop could search in the manifest's `bin` and `shortcuts` sections. In fact, I thought it did.

**Pull request closed without merging**
