### PR TITLE
ImPlay: Add version 1.4.0

### PR DESCRIPTION
**Pull request by wzdnzd**
Add [ImPlay](https://github.com/tsl0922/ImPlay)

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by candrapersada** [comment]
why use `.msi` not `.zip`?
and why there is no persist like `"persist": "portable_config",`

**Comment by wzdnzd** [comment]
> why use `.msi` not `.zip`?
 
The directory of the .exe executable file in the zip file is dynamic, such as ImPlay-$version-win64. For convenience, I used .msi. If necessary, I can change it to .zip.

> why there is no persist like `"persist": "portable_config",`

The configuration and user data directory of this software is located at `%APPDATA%/implay`, which cannot be changed, so there is no need to specify `persist`.

**Comment by candrapersada** [comment]
why make ImPlay on Scoop when ImPlay already exists on winget?

**Comment by wzdnzd** [comment]
> why make ImPlay on Scoop when ImPlay already exists on winget?

No, it seems that the software has not been submitted to winget yet.

**Comment by candrapersada** [comment]
https://github.com/microsoft/winget-pkgs/tree/master/manifests/t/tsl0922/ImPlay

**Comment by wzdnzd** [comment]
> https://github.com/microsoft/winget-pkgs/tree/master/manifests/t/tsl0922/ImPlay

Sorry, I didn't find the information to submit to winget before. So what should I do?

**Pull request closed without merging**
