### PR TITLE
Include bin statements in p4v

### PR DESCRIPTION
**Pull request by Jestar342**
- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
Reason?

**Comment by Jestar342** [comment]
Without those bin statements, they aren't added to $Env:PATH, and can't be found from cli - so stuff like using p4merge as git's diff/merge tool fails to work.

**Comment by rashil2000** [comment]
Do all of them support CLI arguments?

**Comment by Jestar342** [comment]
Yes, they all do.

**Comment by rashil2000** [comment]
Move them below the extract_dir field. 

What is the difference between p4.exe and p4v.exe?

**Comment by Jestar342** [comment]
I believe p4 is the cli/tui client, whilst p4v is the visual client. Both accept cli args though, as you can start the visual client with connection details etc straight from the cli.

image

**Pull request merged**
