### PR TITLE
imageglass: Update to version 8.3.11.21

### PR DESCRIPTION
**Pull request by eugenesvk**
Used `checkver.ps1` ​from [autoupdate guide](https://github.com/ScoopInstaller/Scoop/wiki/App-Manifest-Autoupdate) to update imageglass

Fixes: #7412

### CODE REVIEW

**Comment by eugenesvk** [comment]
@rashil2000 by the way, as far as I understand, the lack of autoupate is related to GitHub rate limiting, however some apps (like this one) also host binaries on their websites (https://imageglass.org/release/download/imageglass-kobe-8-3-11-21-79), would it make sense to go (back) to checking the website? Or is there a fallback option in the manifest for an alternative link or something?
Or is it not worth the hassle before the rate limit issue is resolved?

**Comment by rashil2000** [comment]
If you can update the checkver to use an alternative source (like the website you mentioned), it would be great!

**Comment by eugenesvk** [comment]
Well, I don't want to replace the link (websites can be brittle too, change format etc., so besides the rate limit issue, are actually worse than GitHub), but from a brief look at the app [manifest spec](https://github.com/ScoopInstaller/Scoop/wiki/App-Manifests) I gather there is actually no option for multiple source urls, **is that so**?

**Comment by rashil2000** [comment]
For checker, only one URL is allowed.

**Pull request merged**
