### PR TITLE
CloudflareWarpSpeedTest: Add version v1.1.4

### PR DESCRIPTION
**Pull request by peanut996**
- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by peanut996** [comment]
@CryoRenegade Have a look 👁️

**Comment by peanut996** [comment]
> Could you add a checkver? It allows github actions to update the file automatically. You can find the documentation in creating a package.

I ll add it later. thanks for your feedback!

**Comment by peanut996** [comment]
> Could you add a checkver? It allows github actions to update the file automatically. You can find the documentation in creating a package.

@CryoRenegade  already add checkver, have a look 👁️

**Comment by peanut996** [comment]
@CryoRenegade PTAL 😀

**Comment by CryoRenegade** [comment]
Cool, now we wait for a maintainer to merge!

**Comment by aliesbelik** [comment]
@peanut996 Please add arm64 option and update to the latest version.

**Pull request closed without merging**
