### PR TITLE
Add: drivedlgo

### PR DESCRIPTION
**Pull request by semisoft0072**
- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by semisoft0072** [comment]
hey @HUMORCE sorry for ping but this is i am first time doing poll request so if i did any thing wrong please let me know

**Comment by HUMORCE** [comment]
1 PR for 1 manifest, unless they are highly correlated with each other.

**Comment by semisoft0072** [comment]
oh okay noted

**Comment by semisoft0072** [comment]
@HUMORCE hey there is issues on drivedlgo pkg json `extract_dir` is wrong and also no need
how can remove that so do i have to make new poll request for that?
Sorry for the inconvenience!

**Comment by HUMORCE** [comment]
force push or close this one then create new one.

**Comment by semisoft0072** [comment]
Closing this poll request in favour of adding fix version of drivedlgo.json

**Pull request closed without merging**
