### PR TITLE
foxmail: Add version 7.2.25.213 with new checkver

### LINKED ISSUE #10685: [Request]: Foxmail is a freeware e-mail client developed by Tencent.
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

foxmail

### Description

a freeware e-mail client developed by Tencent

### Homepage

https://www.foxmail.com/

### Download Link(s)

https://dldir1.qq.com/foxmail/windows/FoxmailSetup_7.2.25.213.exe

### Some Indication of Popularity/Repute

https://github.com/ScoopInstaller/Extras/pull/10468

The following is from Wikipedia:

In 2003, in a joint press-release with [Verisign](https://en.wikipedia.org/wiki/Verisign) promoting [Internationalized domain names](https://en.wikipedia.org/wiki/Internationalized_domain_name), the authors' reported over 3 million daily Foxmail users in China.[[3]](https://en.wikipedia.org/wiki/Foxmail#cite_note-3) (For perspective, the [CNNIC](https://en.wikipedia.org/wiki/CNNIC) reported a total number of 35 million Internet users in China in January 2002.[[4]](https://en.wikipedia.org/wiki/Foxmail#cite_note-HughesWacker2003-4))

### PR DESCRIPTION
**Pull request by b4imetu**
Closes #10685

Relates to #XXXX

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by b4imetu** [comment]
Foxmail is Tencent's free email client.
/verify

**Comment by b4imetu** [comment]
/verify

Foxmail is Tencent's free email client.

**Review by StarsbySea — APPROVED** [review]

**Comment by StarsbySea** [comment]
Closes #10685

**Comment by Zliced13** [comment]
Closes #10685

**Comment by b4imetu** [comment]
Closes #10685
@Zliced13 Thank you.

**Review by HUMORCE — APPROVED** [review]

**Review by StarsbySea — APPROVED** [review]

**Pull request merged**
