### PR TITLE
kdoc-formatter: Add version 1.4.1

### PR DESCRIPTION
**Pull request by astelmachonak-nydig**
Add version 1.4.1 of [kdoc-formatter](https://github.com/tnorbye/kdoc-formatter) - Kotlin KDoc auto-format tool

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by issaclin32** [comment]
This looks like a pure command-line app.
Is there any reason **not** to add this package to the [main bucket](https://github.com/ScoopInstaller/Main)?

**Comment by astelmachonak-nydig** [comment]
@issaclin32 quite a specific app with small userbase. I did follow the ktlint package, which is related app and in extra bucket now.

**Comment by issaclin32** [comment]
> @issaclin32 quite a specific app with small userbase. I did follow the ktlint package, which is related app and in extra bucket now.

Ok. I see.

**Review by issaclin32 — APPROVED** [review]

**Pull request merged**
