### PR TITLE
godot & godot-mono: Enhance `pre_install` script

### PR DESCRIPTION
**Pull request by Zliced13**
- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by niheaven** [comment]
I'm not sure why whole file is changed, so just change `pre_install` in a direct commit.

**Comment by drilus** [comment]
This commit breaks the install for me. I think you need:

``"Get-ChildItem \"$dir\\Godot_*.exe\"``

in order to properly rename a wildcard

**Comment by Zliced13** [comment]
You don't have to worry about this commit merging @drilus. @niheaven closed this issue already.

**Comment by ikenichiro** [comment]
I think @drilus is saying that the installation is still broken after e7843a9 .
I also get the following error when trying to install godot with the current configuration.

```
+ Rename-Item "$dir\Godot_*.exe" 'godot.exe'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Rename-Item]、PSArgumentException
    + FullyQualifiedErrorId : Argument,Microsoft.PowerShell.Commands.RenameItemCommand
```
Could you guys take a look? @niheaven @Zliced13

**Comment by niheaven** [comment]
It works for me in PS5 and PS7, how about yours? @Zliced13 

image

**Comment by Zliced13** [comment]
I was also able to install **godot** just fine.
(WindowsTerminal)c1K2k4_11-22-2022

**Comment by ikenichiro** [comment]
I was able to reproduce the error and also find a working around on multiple environments, but I'm not exactly sure why this error occurs.
1. Execute ``scoop install godot`` having PowerShell's working directory anywhere inside drive C: (e.g. C: or C;\Users\someuser\scoop\)

Executing the install command when having the working directory at any other drive (ex. D: ) works as expected.

godot-not-installing

This screenshot is from PSVersion 5.1.19041.1645, but I have also confirmed the same errors on 5.1.19041.1682.
Both environments run having the WIndows environment in Japanese, however, the username does not include any multi-byte chars (only composed of non-special ASCII, all small-case a-z ).

**Comment by ikenichiro** [comment]
confirmed fixed by #9825 .
Many thanks for the fast work ;)

**Pull request closed without merging**
