### PR TITLE
Create vectormagic.json

### LINKED ISSUE #9176: [Request]  vector magic
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [x] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [x] the latest stable version of the program

### Information

**Name:** vector magic

**Description:** Stand-alone desktop application to convert bitmap images to vector images offline.

**Homepage:** https://vectormagic.com/

**Download link(s):** https://vectormagic.com/desktop

### PR DESCRIPTION
**Pull request by micah-gant**
This is my first contribution attempt. Would somebody mind helping to guide me through the aspects I am not familiar with yet?

Closes #9176

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by micah-gant** [comment]
I left comments that will obviously have to be taken out. I just wanted to note aspects I was having trouble with within the .json file.

**Comment by micah-gant** [comment]
I have discovered the App-Manifests wiki for this repository. Time to read up on that.

**Comment by micah-gant** [comment]
Had to work on other things up until today for other classes. Will be focusing on finishing this today and tomorrow.

**Comment by micah-gant** [comment]
I had to make a local version of the download link for uploading. I'm really not sure how to use checkver in reference to an app where the site's download doesn't contain an actual link. (ie. I had to make a mirror download just for the link, but that's not going to autoupdate)

**Comment by jasongodev** [comment]
@micah-gant what's the progress of this PR?

**Comment by HUMORCE** [comment]
When you are ready to refine the manifest, ping the maintainers and reopen the PR.

**Pull request closed without merging**
