### PR TITLE
openelement: add version 1.57.R9

### LINKED ISSUE #9337: [Request]  Add openElement
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [x] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [x] the latest stable version of the program

### Information

**Name:** [openElement]

**Description:** [WEBSITE EDITOR WITH TOTAL CONTROL
MODIFY ANY ELEMENT AND STYLE THE WAY YOU WANT]

**Homepage:** [https://openelement.uk/index.htm]

**Download link(s):** [https://openelement.uk/Download.htm]

**Some indication of popularity/repute:** [Cannot find it like that]

### PR DESCRIPTION
**Pull request by Zliced13**
Closes #9337

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by HUMORCE** [comment]
non-portable

**Comment by Zliced13** [comment]
@HUMORCE what are you talking about? It worked fine for me,
(WindowsTerminal)e7v218_04-15-2023
```bat
 scoop install open-element
Installing 'open-element' (1.57.R9) [64bit] from MyScoop bucket
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 798b70|OK  |   2.8MiB/s|C:/Users/krist/scoop/cache/open-element#1.57.R9#https_openelement.uk_Files_Other_openElement.exe
Download: Status Legend:
Download: (OK):download completed.
Checking hash of openElement.exe ... ok.
Running pre_install script...
Linking ~\scoop\apps\open-element\current => ~\scoop\apps\open-element\1.57.R9
Creating shim for 'openElement'.
Creating shortcut for openElement (openElement.exe)
'open-element' (1.57.R9) was installed successfully!
```

**Review by HUMORCE — APPROVED** [review]

**Comment by Zliced13** [comment]
@HUMORCE wait, I need to make a small change.

**Comment by Zliced13** [comment]
Alright it should be good now, just had to make a small change. Now the GUI progress bar will not appear on the user's screen during the `pre_install` script.

**Pull request merged**
