### PR TITLE
chore (GitHub API): Use repo ID, instead of repo name

### PR DESCRIPTION
**Pull request by brian6932**
Repo names are subject to change, IDs aren't

Relates to https://github.com/ScoopInstaller/Main/pull/5215 https://github.com/ScoopInstaller/Versions/pull/1429

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by brian6932** [comment]
I'm unsure why `debugviewpp` fails `/verify`, it works perfectly fine when setting `version` to `0`, and running `bin\checkver.ps1 -u` on it

**Comment by rashil2000** [comment]
> I'm unsure why `debugviewpp` fails `/verify`, it works perfectly fine when setting `version` to `0`, and running `bin\checkver.ps1 -u` on it

Let's debug that in a separate PR

**Pull request merged**
