### PR TITLE
added bin section to regexp - registry explorer

### PR DESCRIPTION
**Pull request by amreus**
- [ ] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
What are the supported commandline arguments for the binary?

**Comment by amreus** [comment]
No idea. Why?

**Comment by rashil2000** [comment]
Check the contributing guide

**Comment by amreus** [comment]
I already closed the request when you replied.

**Comment by rashil2000** [comment]
I was just mentioning that we only add `bin` if the binary supports commandline arguments.

**Comment by amreus** [comment]
I see. Thanks for your patience. I'll be less impulsive.

**Pull request closed without merging**
