### PR TITLE
capframex: remove extract directory

### PR DESCRIPTION
**Pull request by 404NetworkError**
- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
?

You changed the version

**Comment by 404NetworkError** [comment]
Whoops. Thanks for catching my mistake. This PR is only supposed to remove the `extract_dir`.

**Comment by 404NetworkError** [comment]
Sorry to waste your time on the silly mistakes.

**Comment by rashil2000** [comment]
No worries

**Pull request merged**
