### PR TITLE
activitywatch: Add version 0.12.1

### PR DESCRIPTION
**Pull request by Pkcarreno**
Add the ActivityWatch app to the bucket

Closes https://github.com/ScoopInstaller/Extras/issues/10647

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jasongodev** [comment]
@Pkcarreno can you fix your manifest file to make checkver and autoupdate work?

**Comment by Pkcarreno** [comment]
@jasongodev sorry for the delay, I did the checkver test on my end and it works ok and I solved all the errors that the `/verify` showed

**Pull request merged**
