### PR TITLE
archisteamfarm: Add version 5.2.7.7

### PR DESCRIPTION
**Pull request by b4imetu**
JustArchiNET/ArchiSteamFarm : farming Steam cards from multiple accounts simultaneously
Github 8.3k stars
Code modified from [chawyehsu/dorado](https://github.com/chawyehsu/dorado/blob/master/bucket/archisteamfarm.json)

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by issaclin32** [comment]
Tested. The manifest works fine.
CI for Powershell 5 has some problems. I am still finding the reason.

**Review by issaclin32 — APPROVED** [review]

**Review by tech189 — APPROVED** [review]

**Comment by b4imetu** [comment]
> The manifest works fine. CI for Powershell 5 has some problems. I am still finding the reason.

Thank you for testing and approval

**Pull request merged**
