### PR TITLE
archi: fix url

### LINKED ISSUE #13962: archi@5.4.0: download via aria2 failed
This is the console output:
```
PS C:\Users\jesus> scoop update *
archi: 5.3.0 -> 5.4.0
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  To disable this warning, run 'scoop config aria2-warning-enabled false'.
Updating one outdated app:
Updating 'archi' (5.3.0 -> 5.4.0)
Downloading new version
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: e51468|ERR |       0B/s|C:/Users/jesus/scoop/cache/archi#5.4.0#bedf33d.zip
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.

ERROR Download failed! (Error 3) Resource was not found
ERROR https://www.archimatetool.com/downloads/archi/5.4.0/Archi-Win64-5.4.0.zip
    referer=https://www.archimatetool.com/downloads/archi/5.4.0/
    dir=C:\Users\jesus\scoop\cache
    out=archi#5.4.0#bedf33d.zip

ERROR & 'C:\Users\jesus\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\jesus\scoop\cache\archi.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.4 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=24460 --continue --summary-interval=0 --auto-save-interval=1
```

### PR DESCRIPTION
**Pull request by abgox**
Closes #13962

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by abgox** [comment]
@aliesbelik There seems to be a problem with this Actions not detecting `Autoupdate` correctly.

**Comment by ogerardin** [comment]
> @aliesbelik There seems to be a problem with this Actions not detecting `Autoupdate` correctly.

Autoupdate URL needs to be updated too as it does not match the current download URL.
The URL pattern seems to have changed (again) from
https://www.archimatetool.com/downloads/archi/$version/Archi-Win64-$version.zip
to
https://www.archimatetool.com/downloads/archi/$majorversion.$minorversion/Archi-Win64-$version.zip

**Comment by abgox** [comment]
> > @aliesbelik There seems to be a problem with this Actions not detecting `Autoupdate` correctly.
> 
> Autoupdate URL needs to be updated too as it does not match the current download URL. The URL pattern seems to have changed (again) from `https://www.archimatetool.com/downloads/archi/$version/Archi-Win64-$version.zip` to `https://www.archimatetool.com/downloads/archi/$majorversion.$minorversion/Archi-Win64-$version.zip`

- But `4.0` is a special case.
- If chang to `https://www.archimatetool.com/downloads/archi/$majorversion.$minorversion/Archi-Win64-$version.zip` When the app is updated to `4.0.1`, the problem occurs again.
- I think this is a special url fix and should ignore the Actions error.

**Comment by ogerardin** [comment]
> > Autoupdate URL needs to be updated too as it does not match the current download URL. The URL pattern seems to have changed (again) from `https://www.archimatetool.com/downloads/archi/$version/Archi-Win64-$version.zip` to `https://www.archimatetool.com/downloads/archi/$majorversion.$minorversion/Archi-Win64-$version.zip`
> 
> * But `4.0` is a special case.

You mean 5.4.0? Maybe it is, maybe not. We don't know how the publisher will structure the URL for future versions. There has already been several changes for this app.

> * If change to `https://www.archimatetool.com/downloads/archi/$majorversion.$minorversion/Archi-Win64-$version.zip` When the app is updated to `4.0.1`, the problem occurs again.

Assuming you mean 5.4.1, not necessarily. If the URL pattern remains the same it could be  `https://www.archimatetool.com/downloads/archi/5.4/Archi-Win64-5.4.1.zip`
Only the publisher knows. 

> * I think this is a special url fix and should ignore the Actions error.

You may be right, I think the publishing is manual and the change could be an accident.

**Comment by ogerardin** [comment]
For info, I made a request on Archi's GitHub to ask if they could stick to a consistent download URL pattern: my request was deleted without explanation. 

I asked the question on the Archi user forum and my **account** got deleted immediately without explanation!

I understand that scoop is not a supported installation method but it's the installation/update method chosen by many Archie users, who deserve respect and at least a response to a legitimate request, even if it was just to say "we can't commit to that". 

It's now clear the Archie people don't care about them.

**Pull request closed without merging**
