### PR TITLE
BambuStudio: Add version 01.04.00.18

### LINKED ISSUE #10174: [Request]: BambuStudio
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

BambuStudio

### Description

G-code generator for 3D printers from bambu lab

### Homepage

https://bambulab.com/de/download

### Download Link(s)

https://github.com/bambulab/BambuStudio/releases or https://bambulab.com/de/download

### Some Indication of Popularity/Repute

About 300 Stars on GH and 5.500 Backer on Kickstarter (for the printer itself)

### PR DESCRIPTION
**Pull request by b-reich**
Adds the BambuStudio Slicer Software.

Closes #10174

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by b-reich** [comment]
Is it possible to save something to $APPDATA?

**Review by HUMORCE — CHANGES_REQUESTED** [review]
- syntax
- order of fields

**Comment by b-reich** [comment]
@HUMORCE did I miss anyhting?

**Comment by b-reich** [comment]
> > Is it possible to save something to $APPDATA?
> 
> Unless it is necessary step make program runs correctly or disables built-in updater.

Without it the camera live feed wont work. Do you have an example for me?

**Comment by HUMORCE** [comment]
> Without it the camera live feed wont work

Then these extra files need to be pre-created.

**Comment by Roemer** [comment]
Newer releases are now on GitHub, I created a PR with a manifest using GitHub for the version and download: https://github.com/ScoopInstaller/Extras/pull/13479

**Comment by aliesbelik** [comment]
Closing in favor of #13479.

**Pull request closed without merging**
