### PR TITLE
chromium-nosync: Move into versions bucket

### PR DESCRIPTION
**Pull request by LazyGeniusMan**
…pdate

Closes #XXXX

Relates to #7292 

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

## Notes
- List of files can be found here: : https://github.com/LazyGeniusMan/Sc00p-Test/runs/4697442253?check_suite_focus=true#step:3:115
- Should I also add bin & scripts that's used in ungoogled-chromium ?

### CODE REVIEW

**Comment by rashil2000** [comment]
> Should I also add bin & scripts that's used in ungoogled-chromium?

Yes. After that, please shift this PR to Versions bucket. I think that's a better place for this.

**Comment by LazyGeniusMan** [comment]
> Yes. After that, please shift this PR to Versions bucket. I think that's a better place for this.

How do I do that? close this and make a new PR?, or is there any efficient way?

**Comment by rashil2000** [comment]
No efficient way I'm afraid.

**Comment by LazyGeniusMan** [comment]
@rashil2000 done, could you merged this PR [to](url) delete the manifest in depreciated folder?

**Pull request merged**
