### PR TITLE
powershell-beautifier: Add version 1.2.5

### PR DESCRIPTION
**Pull request by matracey**
This PR adds the PowerShell-Beautifier module, a whitespace reformatter and code cleaner for Windows PowerShell and PowerShell Core that is compatible with all OSes.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by HUMORCE** [comment]
go main bucket.

**Comment by matracey** [comment]
Ok, I will raise a PR on the main bucket.

**Pull request closed without merging**
