### PR TITLE
sunshine: Fix persist

### PR DESCRIPTION
**Pull request by sitiom**
The `config` folder contains template files that are copied to the root folder when running Sunshine for the first time.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by issaclin32** [comment]
Since these files does not exist at the beginning (but rather created upon first run)
We need to create the files in `pre_install`, otherwise *Scoop* will persist them as folders. (by default)

```
"'apps.json', 'sunshine.conf' | ForEach-Object {"
"    if (!(Test-Path \"$persist_dir\\$_\")) { New-Item \"$dir\\$_\" | Out-Null }",
"}",
```

**Comment by sitiom** [comment]
It would be better to copy the default configs from the `config` folder:
```json
"'apps.json', 'sunshine.conf' | ForEach-Object {",
"    if (!(Test-Path \"$persist_dir\\$_\")) { Copy-Item \"$dir\\config\\$_\" \"$dir\\$_\" | Out-Null }",
"}",
```

**Comment by issaclin32** [comment]
> It would be better to copy the default configs from the `config` folder (which is what Sunshine does):

Oh. I see.

**Pull request merged**
