### PR TITLE
Add .reg files for Notepad++ context menu

### LINKED ISSUE #771: Add NppShell.dll to notepad++
Add NppShell.dll to notepad++ to be able to add it to the Windows Explorer context menu:
http://docs.notepad-plus-plus.org/index.php/Explorer_Context_Menu

### PR DESCRIPTION
**Pull request by tomihawk**
Add install-context.reg and uninstall-context.reg to add "Open with Notepad++" to the explorer context menu
Changes based on similar functionality in Sublime Text.

Resolves #771

### CODE REVIEW

**Review by rasa — APPROVED** [review]

**Comment by tomihawk** [comment]
Is there something else I need to do here to merge?  Not trying to rush anyone.  I just don't want to be the hold-up if the ball is in my court and people are waiting on me.  I haven't contributed to this project before.

**Review by rasa — APPROVED** [review]

**Comment by AntonOks** [comment]
> 
> 
> /verify

Hi @rasa  What happened to this pull? After the notepad++ update some days ago this issue poped up again...

**Comment by maksymgendin** [comment]
@tomihawk Wanted to raise a pull request for Notepad++ context menu items and came across this pull request. Would you like to resolve the conflicts so that this can be merged?

**Comment by maksymgendin** [comment]
@Ash258 @r15ch13 Could you please take a look at this? Thanks 🙏

**Comment by Ash258** [comment]
/unsubsribe

No. I am not going to continue with merging some random registry tweak even when it is optional. If the application is not capable o doing this from settings menu, handle it manually.

**Comment by tomihawk** [comment]
I'd hardly call it _random._  It's the same _registry tweak_ that Vim, Sublime Text and VSCode have been using for years.

https://github.com/ScoopInstaller/Main/blob/master/bucket/vim.json
https://github.com/ScoopInstaller/Main/blob/master/scripts/vim/install-context.reg

https://github.com/lukesampson/scoop-extras/blob/master/bucket/sublime-text.json
https://github.com/lukesampson/scoop-extras/blob/master/scripts/sublime-text/install-context.reg

https://github.com/lukesampson/scoop-extras/blob/master/bucket/vscode.json
https://github.com/lukesampson/scoop-extras/blob/master/scripts/vscode-install-context.reg

**Comment by AntonOks** [comment]
> 
> 
> I'd hardly call it _random._ It's the same _registry tweak_ that Vim, Sublime Text and VSCode have been using for years.
> 
> https://github.com/ScoopInstaller/Main/blob/master/bucket/vim.json
> https://github.com/ScoopInstaller/Main/blob/master/scripts/vim/install-context.reg
> 
> https://github.com/lukesampson/scoop-extras/blob/master/bucket/sublime-text.json
> https://github.com/lukesampson/scoop-extras/blob/master/scripts/sublime-text/install-context.reg
> 
> https://github.com/lukesampson/scoop-extras/blob/master/bucket/vscode.json
> https://github.com/lukesampson/scoop-extras/blob/master/scripts/vscode-install-context.reg

I'm also using the "registry tweak" in my [notepad++ manifest](https://github.com/AntonOks/scoop-aoks/blob/master/bucket/notepadplusplus-aoks.json) now. Initially I started with the ["regsvr32 /i"](https://github.com/AntonOks/scoop-aoks/blob/9d83dd50e8873c3719df65bf78ab9dc183bdd3e8/bucket/notepadplusplus-aoks.json#L8) thing, but once the **_NppShell.dll_** DLL is injected, I couldn't de-install (and therefore also not update!) notepad++ anymore... so the registry thing is ways better.

**Comment by igitur** [comment]
@tomihawk I don't have high hope that this will be merged, but resolving the conflicts will get it one step closer.

**Comment by maksymgendin** [comment]
Fantastic work, guys! Thank you very much for the efforts 🙏🏻

**Pull request merged**
