### PR TITLE
robocopy-gui: Use archived link

### PR DESCRIPTION
**Pull request by kazzarin**
Original link is dead

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by StarsbySea — APPROVED** [review]

**Comment by kazzarin** [comment]
Blocked on https://github.com/ScoopInstaller/Binary/pull/16

**Comment by HUMORCE** [comment]
Due upstream is no longer available and unknown licenses. `extras/robocopy-gui` and `extras/richcopy`(#10806) distributed as-is.

**Comment by kazzarin** [comment]
@HUMORCE somewhat related, should I also be doing the same for this https://github.com/ScoopInstaller/Main/commit/78622a7dd19e066391aed3a8f0b9604dcc4dbab0 which got merged recently

**Pull request merged**
