### PR TITLE
certigo: add version 1.16.0

### PR DESCRIPTION
**Pull request by cr1cr1**
- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aliesbelik** [comment]
Just wonder this should be PR to the `main` bucket instead, since the app completely fits the [Main criteria](https://github.com/ScoopInstaller/Scoop/wiki/Criteria-for-including-apps-in-the-main-bucket).

**Comment by aliesbelik** [comment]
Fixes square/certigo#288.

**Review by StarsbySea — COMMENTED** [review]
Local test pass
图片

**Comment by HUMORCE** [comment]
Please add this manifest to the main bucket instead of extras bucket

**Pull request closed without merging**
