### PR TITLE
vncviewer: Update domain of realvnc

### LINKED ISSUE #10742: [Bug]: Domain for realvnc has moved
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

vncviewer

### Expected/Current Behaviour

When installing vncviewer by executing `scoop install vncviewer`, it showed that `URL https://www.realvnc.com/download/file/viewer.files/VNC-Viewer-7.0.1-Windows-64bit.exe#/vncviewer.exe is not valid`

### Steps to Reproduce

```console
PS> scoop install vncviewer
Installing 'vncviewer' (7.0.1) [64bit] from extras bucket
URL https://www.realvnc.com/download/file/viewer.files/VNC-Viewer-7.0.1-Windows-64bit.exe#/vncviewer.exe is not valid
```

### Possible Solution

Change www.realvnc.com to downloads.realvnc.com in vncviewer.json

### Scoop and Buckets Version

```console
PS> scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
36dc2e2f4 (HEAD -> master, origin/master, origin/HEAD) scite: Update to version 5.3.5

'main' bucket:
5b5caf98f (HEAD -> master, origin/master, origin/HEAD) static-web-server: Update to version 2.15.0
```

### Scoop Config

```console
PS>  scoop config

last_update                       proxy           scoop_branch scoop_repo
-----------                       -----           ------------ ----------
2023-03-13T14:35:19.6823616+08:00 127.0.0.1:10809 master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22621.963
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.963
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Additional Softwares

_No response_

### PR DESCRIPTION
**Pull request by milkice233**
Closes #10742 

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by jasongodev — APPROVED** [review]
The manifest changes installed correctly. This can be merged without problems.

```powershell
PS C:\Users\jason> scoop cat vncviewer
{
    "version": "7.0.1",
    "description": "Control VNC enabled computers.",
    "homepage": "https://www.realvnc.com/download/viewer",
    "license": {
        "identifier": "Freeware",
        "url": "https://www.realvnc.com/en/legal/#eulas"
    },
    "architecture": {
        "64bit": {
            "url": "https://downloads.realvnc.com/download/file/viewer.files/VNC-Viewer-7.0.1-Windows-64bit.exe#/vncviewer.exe",
            "hash": "a5bac8a4e844955206ca700efeb87051a281d065f37f5f10b62f8b99206587be"
        },
        "32bit": {
            "url": "https://downloads.realvnc.com/download/file/viewer.files/VNC-Viewer-7.0.1-Windows-32bit.exe#/vncviewer.exe",
            "hash": "3f77cab63629bf3134e62060e2bb76f60b474a4f2ed26ca43337dbce361b637e"
        }
    },
    "bin": "vncviewer.exe",
    "shortcuts": [
        [
            "vncviewer.exe",
            "VNC Viewer"
        ]
    ],
    "checkver": {
        "url": "https://www.realvnc.com/en/connect/download/viewer/",
        "regex": "VNC-Viewer-([\\d.]+)-Windows"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://downloads.realvnc.com/download/file/viewer.files/VNC-Viewer-$version-Windows-64bit.exe#/vncviewer.exe"
            },
            "32bit": {
                "url": "https://downloads.realvnc.com/download/file/viewer.files/VNC-Viewer-$version-Windows-32bit.exe#/vncviewer.exe"
            }
        },
        "hash": {
            "url": "https://www.realvnc.com/en/connect/download/viewer/",
            "regex": "(?sm)$basename.*?SHA-256: $sha256"
        }
    }
}
PS C:\Users\jason> scoop install vncviewer
Installing 'vncviewer' (7.0.1) [64bit] from extras bucket
Loading VNC-Viewer-7.0.1-Windows-64bit.exe from cache
Checking hash of VNC-Viewer-7.0.1-Windows-64bit.exe ... ok.
Linking ~\scoop\apps\vncviewer\current => ~\scoop\apps\vncviewer\7.0.1
Creating shim for 'vncviewer'.
Creating shortcut for VNC Viewer (vncviewer.exe)
'vncviewer' (7.0.1) was installed successfully!
```

**Review by jasongodev — CHANGES_REQUESTED** [review]
The autoupdate hash routine is not reliable because the help page of realvnc seems to block non-browser access to it. Therefore scoop can not see this page for hash checking.

```powershell
PS C:\Users\jason\scoop\apps\scoop\current> ./bin/checkver.ps1 realvnc -Update -Dir "C:\Users\jason\scoop\buckets\extras\bucket\"
realvnc: 7.0.1 (scoop version is 7.0.0) autoupdate available
Autoupdating realvnc
Searching hash for VNC-Viewer-7.0.1-Windows-32bit.exe in https://help.realvnc.com/hc/en-us/articles/5835892358941-VNC-Connect-Download-Checksums
The remote server returned an error: (403) Forbidden.
URL https://help.realvnc.com/hc/en-us/articles/5835892358941-VNC-Connect-Download-Checksums is not valid
Could not find hash in https://help.realvnc.com/hc/en-us/articles/5835892358941-VNC-Connect-Download-Checksums
Downloading VNC-Viewer-7.0.1-Windows-32bit.exe to compute hashes!
Loading VNC-Viewer-7.0.1-Windows-32bit.exe from cache
Computed hash: 3f77cab63629bf3134e62060e2bb76f60b474a4f2ed26ca43337dbce361b637e
Searching hash for VNC-Viewer-7.0.1-Windows-64bit.exe in https://help.realvnc.com/hc/en-us/articles/5835892358941-VNC-Connect-Download-Checksums
The remote server returned an error: (403) Forbidden.
URL https://help.realvnc.com/hc/en-us/articles/5835892358941-VNC-Connect-Download-Checksums is not valid
Could not find hash in https://help.realvnc.com/hc/en-us/articles/5835892358941-VNC-Connect-Download-Checksums
Downloading VNC-Viewer-7.0.1-Windows-64bit.exe to compute hashes!
Loading VNC-Viewer-7.0.1-Windows-64bit.exe from cache
Computed hash: a5bac8a4e844955206ca700efeb87051a281d065f37f5f10b62f8b99206587be
Writing updated realvnc manifest
```

I suggest not to include the hash property and let scoop download the file manually for hash calculation.

**Review by niheaven — APPROVED** [review]

**Pull request merged**
