### PR TITLE
Update freecad.json

### PR DESCRIPTION
**Pull request by jeremy886**
Closes #XXXX

Relates to #XXXX

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by jeremy886 — COMMENTED** [review]
update to newest version. fix a few wrong file names or paths.

**Comment by danielpauldd** [comment]
I think this PR is obsolete, as the current manifest refers to the current freecad version and also have an autoupdate section. Please close this PR.

**Comment by aliesbelik** [comment]
Superseded by #12658.

**Pull request closed without merging**
