### PR TITLE
netron: Update homepage 

### LINKED ISSUE #7247: netron: update homepage to https://netron.app/
https://github.com/ScoopInstaller/Extras/blob/master/bucket/netron.json

We need to update the homepage to https://netron.app/

This is a good issue to fix for new users or existing users who wish to better their understanding of Scoop.

We would definitely help out.

### PR DESCRIPTION
**Pull request by infomaniac50**
Closes #7247

### CODE REVIEW

**Comment by rashil2000** [comment]
You will need to update the checkver property too, since it no longer knows where the repo is

**Comment by infomaniac50** [comment]
Autoupdate is correct. I assume the bot stops on the first error.

**Comment by rashil2000** [comment]
Great, thanks for the fix!

**Pull request merged**
