### PR TITLE
ddu@18.0.6.0: remove extract_dir

### LINKED ISSUE #10295: [Bug]: ddu fails to update
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

ddu

### Expected/Current Behaviour

Error when updating:
``Could not find 'DDU v18.0.6.0'! (error 16)``

### Steps to Reproduce

```console
➜ scoop update ddu
ERROR 'ddu' isn't installed correctly.
ddu: 18.0.5.9 -> 18.0.6.0
Updating one outdated app:
Updating 'ddu' (18.0.5.9 -> 18.0.6.0)
Downloading new version
Loading DDU%20v18.0.6.0.exe from cache
Checking hash of DDU%20v18.0.6.0.exe ... ok.
Uninstalling 'ddu' (18.0.5.9)
Installing 'ddu' (18.0.6.0) [64bit] from extras bucket
Loading DDU%20v18.0.6.0.exe from cache
Extracting dl.7z ... Exception: C:\Users\xyz\scoop\apps\scoop\current\lib\core.ps1:638
Line |
 638 |          throw "Could not find '$(fname $from)'! (error $($proc.ExitCo …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not find 'DDU v18.0.6.0'! (error 16)
```

### Possible Solution

The latest version changes the way the program is installed. It now uses NSIS, when the older version, e.g. v18.0.5.9, uses a self-extracting archive.

### Scoop and Buckets Version

```console
➜ scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'bkmeneguello_scoop-bucket' bucket:
772abe6 (HEAD -> master, origin/master, origin/HEAD) godot-4-mono-beta: Update to version 4.0-beta14

'cc713_ownscoop' bucket:
6af61d0 (HEAD -> master, origin/master, origin/HEAD) scoop-directory: Update to version 2023-01-22-00-51-31

'couleur-tweak-tips_utils' bucket:
d2bff5e (HEAD -> main, origin/main, origin/HEAD) Merge pull request #15 from he3als/patch-1

'dank-scoop' bucket:
c8ed005 (HEAD -> master, origin/master, origin/HEAD) uosc-main: Update to version 1674335640

'emulators' bucket:
9467da0f (HEAD -> master, origin/master, origin/HEAD) dolphin-dev: Update to version 5.0-18281

'extras' bucket:
6dc3c60b6 (HEAD -> master, origin/master, origin/HEAD) sfsu: Update to version 1.3.0

'games' bucket:
a1c333bf (HEAD -> master, origin/master, origin/HEAD) redream-dev: Update to version 1.5.0-1051-g4ba6a39

'holes' bucket:
9486e2d (HEAD -> master) MEGASync manifest added that is up-to-date unlike extras

'main' bucket:
279dc5a50 (HEAD -> master, origin/master, origin/HEAD) groovy: Update to version 4.0.8

'nerd-fonts' bucket:
0b6bcd4 (HEAD -> master, origin/master, origin/HEAD) LXGW-Bright: Update to version 4.156

'nonportable' bucket:
2a604aa (HEAD -> master, origin/master, origin/HEAD) spotx-np: fixed url and added new theme (#132)

'ovyerus' bucket:
3d20b27 (HEAD -> master, origin/master, origin/HEAD) bandsnatch: Update to version 0.1.1

'Scoop-Apps' bucket:
c4451002 (HEAD -> master, origin/master, origin/HEAD) Jacket-Portable: Update to version 0.20.2687

'sysinternals' bucket:
3bce1cc (HEAD -> main, origin/main, origin/HEAD) autoruns: Removes /accepteula arg (#3)

'versions' bucket:
213dcfb60 (HEAD -> master, origin/master, origin/HEAD) r-patched: Update to version 4.2.2-r83653
```

### Scoop Config

```console
➜ scoop config

last_update         aria2-enabled scoop_branch scoop_repo
-----------         ------------- ------------ ----------
22.01.2023 09:35:45         False master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
➜ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Additional Softwares

_No response_

### PR DESCRIPTION
**Pull request by hu3rror**
Closes #10295

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by brian6932** [comment]
lol

**Comment by brian6932** [comment]
terrible timing

**Comment by HUMORCE** [comment]
> terrible timing

Are any other issue here?

**Comment by brian6932** [comment]
Nope, that was just a nit cause the package had some other extra things not useful to most people like a pdb debug file, and some txt files

**Pull request merged**
