### PR TITLE
jellyfin-media-player: Add v1.10.0

### PR DESCRIPTION
**Pull request by rdbisme**
Closes #XXXX

Relates to #XXXX

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rdbisme** [comment]
@aliesbelik can you tell me what's missing for the `autoupdate` to work? 

Also what does `package-request-needed` label means?

**Comment by rdbisme** [comment]
> @aliesbelik can you tell me what's missing for the `autoupdate` to work?
> 
> Also what does `package-request-needed` label means?

Ok nevermind, I'm missing the autoupdate section entirely. I thought `checkver` was enough.

**Comment by aliesbelik** [comment]
> Also what does `package-request-needed` label means?

The normal flow [requires](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md#proposing-a-new-issue) to [create package request](https://github.com/ScoopInstaller/Extras/issues/new?assignees=&labels=package-request&projects=&template=package-request.yml&title=%5BRequest%5D%3A+) for missing package first.
Well, any contribution is helpful but categorization of issues/PRs helps to prioritize their processing.

And another point.

> Fork the repository and create a new branch from the default branch (usually master), with an appropriate name.

Please use separate branch different from `master` to submit PR, or disable the automatic pull bot / app (if any is configured for your account / fork) to avoid synchronization issues like above.

**Comment by rdbisme** [comment]
I'm opening again with another branch to disable the auto update.

**Pull request closed without merging**
