### PR TITLE
rustdesk: Add version 1.1.9

### PR DESCRIPTION
**Pull request by SonaliBendre**
True Open-source teamviewer/anydesk alternative

Closes #XXXX

Relates to #XXXX

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
There are unrelated changes here

**Comment by issaclin32** [comment]
It looks like your new branch is based on your `master` branch, which has been modified previously.

To avoid this problem in the future, you can start a new branch from `origin/master`.

```
git remote add upstream https://github.com/ScoopInstaller/Extras
git checkout -b "rustdesk" upstream/master

git add ....
git commit ....

git push origin  # This pushes "rustdesk" branch to your own fork
```

**Comment by issaclin32** [comment]
*persist* is not needed because config is at `$Env:AppData\RustDesk`.

(This is a reminder, no need to modify anything)

**Review by issaclin32 — APPROVED** [review]

**Review by rashil2000 — APPROVED** [review]

**Pull request merged**
