### PR TITLE
xmind8: Update to version 3.7.9

### PR DESCRIPTION
**Pull request by Absolves**
Closes #XXXX

Relates to #XXXX

### CODE REVIEW

**Comment by rashil2000** [comment]
Autoupdate missing

**Comment by issaclin32** [comment]
Although there is a trackable page (https://www.xmind.net/download/previous/), which says `XMind 8 v3.7.9`, we cannot assure file name (`xmind-8-update9-windows.zip`) and *extract_dir* is always in the same pattern.

Therefore, I think the better way is to accept that we have to update this package **maunally*, unless we managed to track the file name by other means (e.g. a bot that downloads the file and checks version number regularly)

**Comment by rashil2000** [comment]
> Therefore, I think the better way is to accept that we have to update this package *maunally, unless we managed to track the file name by other means (e.g. a bot that downloads the file and checks version number regularly)

Seems fair. 
On a future note, this can be a candidate for updating via the new proposed repository UpdateTracker.

**Comment by Absolves** [comment]
In fact, I successfully downloaded the version using https://www.xmind.net/xmind/downloads/xmind-8-update9-windows.zip, and no problems were found during the installation. At least for now, the extract_dir is still xmind 8 update 9.

In addition, you can download its latest portable version (zip) at https://www.xmind.net/download/xmind8/.

It is worth mentioning that the update frequency of this software is very slow, so maybe we don't need to update it frequently.

thank you for your reply.
发件人: Rashil ***@***.***>
发送时间: 2021年11月13日 0:38
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [ScoopInstaller/Extras] xmind8: Update to version 3.7.9 (PR #7312)


Therefore, I think the better way is to accept that we have to update this package *maunally, unless we managed to track the file name by other means (e.g. a bot that downloads the file and checks version number regularly)

Seems fair.
On a future note, this can be a candidate for updating via the new proposed repository UpdateTracker.

―
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FScoopInstaller%2FExtras%2Fpull%2F7312%23issuecomment-967254320&data=04%7C01%7C%7Cdf34f96aa1c848c3545508d9a5fad9e4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637723319077077474%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=AB6klUPkBBmjQ3xBVJ%2F%2F7tutvBOIr%2BD6wwR4NuE3O70%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALJTY5OUW4ZEI7SZ7TEI73DULU7IFANCNFSM5H5EAFZA&data=04%7C01%7C%7Cdf34f96aa1c848c3545508d9a5fad9e4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637723319077087462%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=FTLmgg0lVR66A5nYzhMHMolSfz31zE04YpjJNaym6fo%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cdf34f96aa1c848c3545508d9a5fad9e4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637723319077087462%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YYYM3k0wUQrS9%2F8WgxBUZRprYHr%2B36lxkcghDe9LJFg%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cdf34f96aa1c848c3545508d9a5fad9e4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637723319077097452%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Ko%2Bkkh9ZXyLPgHrVgtO5w39W5nwnVto0FFRDP%2BwfKIM%3D&reserved=0>.

**Comment by Absolves** [comment]
In fact, I successfully downloaded the version using https://www.xmind.net/xmind/downloads/xmind-8-update9-windows.zip, and no problems were found during the installation. At least for now, the extract_dir is still xmind 8 update 9.

In addition,@issaclin32, you can download its latest portable version (zip) at https://www.xmind.net/download/xmind8/.

It is worth mentioning that the update frequency of this software is very slow, so maybe we don't need to update it frequently.

**Review by rashil2000 — APPROVED** [review]

**Review by issaclin32 — APPROVED** [review]

**Pull request merged**
