### PR TITLE
Umlet: Add version 15.0.0

### LINKED ISSUE #9152: [Request] Umlet
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [x] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [x] the latest stable version of the program

### Information

**Name:** Umlet

**Description:** Free UML Tool for Fast UML Diagrams

**Homepage:** https://www.umlet.com/

**Download link(s):** https://www.umlet.com/changes.htm

**Some indication of popularity/repute:** 274 forks, 1.2k stars

### PR DESCRIPTION
**Pull request by basejumpa**
Add lightweight UML tool "Umlet" in most recent stable version (15.0.0).

Closes #9152

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by basejumpa** [comment]
Can be merged from my side.

**Review by issaclin32 — APPROVED** [review]

**Pull request merged**
