### PR TITLE
Propertree: Add version 0.2022.01.22

### PR DESCRIPTION
**Pull request by hu3rror**
- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

No persist file.

### CODE REVIEW

**Comment by rashil2000** [comment]
I see python scripts, we should add `"depends": "python",`, no?

**Comment by hu3rror** [comment]
> I see python scripts, we should add `"depends": "python",`, no?

You are right, it has been corrected, thank you!

**Comment by hu3rror** [comment]
Why can't checkver pass after I add depends?🤔

**Comment by rashil2000** [comment]
It fails because there's a new version available

**Pull request merged**
