### PR TITLE
Fix "tor-browser" download URLs

### PR DESCRIPTION
**Pull request by xmha97**
Fix `tor-browser` download URLs

### CODE REVIEW

**Comment by rashil2000** [comment]
Change the links in the autoupdate section too

**Comment by xmha97** [comment]
> Change the links in the autoupdate section too

I have done it.

**Comment by xmha97** [comment]
> Change the links in the autoupdate section too

I have done it. @rashil2000

**Comment by xmha97** [comment]
I have done it. @rashil2000

**Pull request merged**
