### PR TITLE
veracrypt: Add version 1.25.9

### LINKED ISSUE #2381: [Request] Add VeraCrypt
Website: [VeraCrypt.fr](https://www.veracrypt.fr/)
License: Multi-licensed under Apache License 2.0 and the TrueCrypt License 3.0 (See [VeraCrypt License](https://www.veracrypt.fr/en/VeraCrypt%20License.html))
Source: [GitHub](https://github.com/veracrypt/VeraCrypt/)
Binaries: [Launchpad](https://launchpad.net/veracrypt/trunk/), [SourceForge](https://sourceforge.net/projects/veracrypt/files/)
Checksums: SHA-256 provided in the binary repos.
Official portable installer **is** available.

### PR DESCRIPTION
**Pull request by ryoid**
Adds MSI installer.

Closes #2381 

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Zliced13** [comment]
This should be added to the nonportable bucket instead of the extras bucket. The extras bucket is for apps that can be used in a portable way, or are made to be portable.

**Comment by Zliced13** [comment]
I found out there is a way of installing the veracrypt.inf driver from the extracted .msi file from the command line, without having to use msiexec. The driver is required if you want to encrypt your system partition, or encrypt a non-system drive partition. Also, the driver installation does not require rebooting your system.

`pnputil.exe /add-driver ".\Downloads\VeraCrypt_Setup_x64_1.25.9.msi extracted\Veracrypt\veracrypt.inf" /install`

**Comment by Stzx** [comment]
Any progress?

> This should be added to the nonportable bucket instead of the extras bucket. The extras bucket is for apps that can be used in a portable way, or are made to be portable.

Using the portable version should meet the requirements.

**Comment by Zliced13** [comment]
@HUMORCE Should this PR be closed? @ryoid you make a new PR in the **[NonPortable](https://github.com/ScoopInstaller/Nonportable)** bucket and close this one.

**Comment by mariobrostech** [comment]
Is there any reason why this couldn't be converted into the portable version? VeraCrypt has one that we can use, and I thought that Scoop generally prefers portable applications when they're available.

**Pull request closed without merging**
