### PR TITLE
calibre-normal@7.0.0:  Path error, unable to install

### LINKED ISSUE #12262: [Bug]:  calibre-normal cannot be installed
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

calibre-normal

### Expected/Current Behaviour

When installing calibre-normal, the error "Could not find 'Calibre2'" is encountered.

### Steps to Reproduce

```console
PS> scoop install calibre-normal
WARN  Purging previous failed installation of calibre-normal.
ERROR 'calibre-normal' isn't installed correctly.
Removing older version (7.0.0).
'calibre-normal' was uninstalled.
Installing 'calibre-normal' (7.0.0) [64bit] from extras bucket
Loading calibre-64bit-7.0.0.msi from cache
Checking hash of calibre-64bit-7.0.0.msi ... ok.
Extracting calibre-64bit-7.0.0.msi ... Exception: 
~\scoop\apps\scoop\current\lib\core.ps1:641
Line |
 641 |          throw "Could not find '$(fname $from)'! (error $($proc.ExitCo …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not find 'Calibre2'! (error 16)
```

### Possible Solution

[calibre-normal.json](https://github.com/ScoopInstaller/Extras/blob/b38141e1a0fdaebe23adb200cc457150bac91aba/bucket/calibre-normal.json#L11
)

Change "extract_dir": "PFiles\Calibre2" to "extract_dir": "PFiles64\Calibre2"

### Scoop and Buckets Version

```console
Unrelated
```

### Scoop Config

```console
Unrelated
```

### PowerShell Version

```console
Unrelated
```

### Additional Softwares

_No response_

### PR DESCRIPTION
**Pull request by mo-n**
Closes #12262 

- [x ] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by pohlymorph** [comment]
> /verify

Cherry-picking the one and only commit of this PR worked for me:
image

Thanks for the fix :)


```
>git cherry-pick aee9f005bc20c960982842cae16cdfdbb0c498e8
[master 3fec31f01] fix: Calibre normal path error
 Author: mo_n <mo_n.tt@outlook.com>
 Date: Sat Nov 18 11:25:11 2023 +0800
 1 file changed, 1 insertion(+), 1 deletion(-)

> git log --oneline -3
3fec31f01 (HEAD -> master) fix: Calibre normal path error
7f83941c4 (origin/master, origin/HEAD) notesnook: Update to version 2.6.9
d7d91e4a9 elisa: Update to version 23.08.3-1687
```

**Review by tech189 — APPROVED** [review]

**Comment by tech189** [comment]
@mo-n thank you for your contribution!

**Pull request merged**
