### PR TITLE
visualboyadvance: Add version 1.8.0-beta.3

### PR DESCRIPTION
**Pull request by snowman**
- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by HUMORCE** [comment]
Seems you are adding an older version of this app. why?

**Comment by snowman** [comment]
I didn't notice there has new bucket `games`, maybe I should send pull request there.

> why?

because they are two different versions, the older version startup fast, less performance required, less file size, like a classic version.

image

**Comment by HUMORCE** [comment]
> maybe I should send pull request there.

Yes

**Pull request closed without merging**
