### PR TITLE
libreoffice: Update to version 7.5.1.1

### PR DESCRIPTION
**Pull request by i2**
Relates to: updating LibreOffice to 7.5.0.3 (latest version)

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by 404NetworkError** [comment]
The `autoupdate` URL for `64bit` needs to be updated too.

**Comment by ivaquero** [comment]
libreoffice also supports arm64 architecture now, please consider adding in `architecture`.

**Comment by i2** [comment]
@404NetworkError @ivaquero done and done.

**Comment by i2** [comment]
Also what do you think of the following fixes/suggestions:

- Rename the following to reflect the actual name of architecture, since 64Bit is now vague! 64 bit for x86 or arm?!
1. `64Bit` -> `x86_64`
2.  `32Bit` to `x86`

- In lines 12 and 16, replace url with "https://downloadarchive.documentfoundation.org/libreoffice/old/$version/win/x86_64/LibreOffice_$version_$architecture.msi

**Comment by ivaquero** [comment]
Thanks for your good suggestions, however this is upstream work of https://github.com/ScoopInstaller/Scoop and tightly bound with the current manifest scheme. Such revisions are reasonable, but not urgent, furthermore this may bring huge rework, I am not sure whether the core maintainers would like to append this to the road map.


> Also what do you think of the following fixes/suggestions:
> 
> * Rename the following to reflect the actual name of architecture, since 64Bit is now vague! 64 bit for x86 or arm?!
> 
> 1. `64Bit` -> `x86_64`
> 2. `32Bit` to `x86`
> 
> * In lines 12 and 16, replace url with "https://downloadarchive.documentfoundation.org/libreoffice/old/$version/win/x86_64/LibreOffice_$version_$architecture.msi

**Comment by i2** [comment]
Okay. We can leave those suggestions for later. Please merge this PR as fit. Thanks!

**Review by ivaquero — CHANGES_REQUESTED** [review]
You also need to change `regex` in `checkver`

**Comment by i2** [comment]
>     * `"regex"` in `"checkver"`: `x64` -> `x86_64`

I believe this should be `x86**-**64`, correct?

**Comment by ivaquero** [comment]
Yeah, you are right.

**Review by ivaquero — CHANGES_REQUESTED** [review]
`"autoupdate"`.`"architecture"`.`"64bit"`.`"url"`: `$version_Win_x86_64` -> `$version_Win_x86-64`

**Comment by i2** [comment]
> `"autoupdate"`.`"architecture"`.`"64bit"`.`"url"`: `$version_Win_x86_64` -> `$version_Win_x86-64`

done.

This is exactly why I wish naming conventions were a bit less confusing. Anyways, hope that was all the fixes needed.

**Comment by i2** [comment]
> Yeah, you are right.

This is exactly why I wish naming conventions were a bit less confusing. Anyways, hope that was all the fixes needed.

**Comment by StarsbySea** [comment]
LGTM

**Comment by i2** [comment]
A question out of curiosity: Is it normal for scoop PRs to take this long to be merged to upstream? Thanks.

**Comment by ivaquero** [comment]
Since last year, the responses for PRs became particularly slow. Several former maintainers left, and the current maintainers' schedules are obviously too tight.  What's worse is that it takes a long time to become a member of the core team.

**Comment by ivaquero** [comment]
I really suggest that the core team to clarify and simplify the procedure of being a maintainer.

**Comment by i2** [comment]
I agree! I'm used to `pacman` and it's fast-paced package management and updates and I was wishing `scoop` can be that on Windows. I like it over WinGet and Chocolatey, but I think the general turnover should be much faster.

**Comment by StarsbySea** [comment]
@r15ch13, if you have time, can you review this pull request and merge it into the master branch if it's fine, please?

**Review by StarsbySea — APPROVED** [review]

**Comment by StarsbySea** [comment]
@niheaven , if you have time, can you review this pull request and merge it into the master branch if it's fine, please?

**Review by niheaven — APPROVED** [review]

**Pull request merged**
