### PR TITLE
superf4: Add version 1.4

### PR DESCRIPTION
**Pull request by RavenMacDaddy**
Force quit apps by pressing Ctrl-Alt-F4.

- [ X ] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by RavenMacDaddy** [comment]
What does the following mean:

image

**Comment by rashil2000** [comment]
Can you merge with master?

**Comment by RavenMacDaddy** [comment]
image

Seems like it.

**Comment by rashil2000** [comment]
Then do it

**Comment by RavenMacDaddy** [comment]
Sorry, misunderstood, I'm not able to merge, I thought you meant any conflicts existing with the branch - I'm not personally able to merge to the repository.

**Comment by rashil2000** [comment]
Do you know how to use git on the command line?

**Comment by RavenMacDaddy** [comment]
I do not, but I've the GitHub Desktop app if that helps.

**Comment by RavenMacDaddy** [comment]
Apparently I could do it through the webpage it seems, didn't feel like my attempt in a CLI was successful anyway.

**Comment by rashil2000** [comment]
> Apparently I could do it through the webpage it seems

Yes, using the `Fetch Upstream` button in your branch

**Comment by RavenMacDaddy** [comment]
> > Apparently I could do it through the webpage it seems
> 
> Yes, using the `Fetch Upstream` button in your branch

So, just to avoid any future mistakes, what should I'd done initially to avoid the appveyor errors?

**Comment by rashil2000** [comment]
> So, just to avoid any future mistakes, what should I'd done initially to avoid the appveyor errors?

That was a mistake on our part, nothing from your end :)

**Comment by RavenMacDaddy** [comment]
Oh, that explains why it wasn't pointing to the manifest in my PR, thanks.

**Pull request merged**
