### PR TITLE
gitnuro: Add version 1.1.1

### LINKED ISSUE #9894: [Request]: Gitnuro
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

Gitnuro

### Description

A FOSS Git multiplatform client for newbies and pros

### Homepage

https://github.com/JetpackDuba/Gitnuro/

### Download Link(s)

https://github.com/JetpackDuba/Gitnuro/releases/download/v1.1.1/Gitnuro_Windows_Portable_1.1.1.zip

### Some Indication of Popularity/Repute

205 Stars on GitHub

### PR DESCRIPTION
**Pull request by ViCrack**
config location: $env:LocalAppData/D3DSCache

Closes #9894

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by giflw — CHANGES_REQUESTED** [review]
Please, add bin section to be able to call gitnuro from command line:
```
    "bin": [
        "Gitnuro.exe",
        [
            "Gitnuro.exe",
            "gitnuro"
        ]
    ],
```

**Review by giflw — APPROVED** [review]

**Comment by HUMORCE** [comment]
> add bin section to be able to call gitnuro from command line

this app does not accept any command line arguments in fact.
if you want open its main window from command line, `scoop-shim` or powershell alias.

**Comment by giflw** [comment]
For the next release (1.2.0) it's planned to add support for opening current dir from command line. That's why I asked for it.

**Comment by HUMORCE** [comment]
> it's planned to add support for opening current dir from command line. That's why I asked for it.

the manifest should be for the current version only. I respect the information you have provided.

**Pull request merged**
