### PR TITLE
liquidsoap: Update to version 2.0.5, fix autoupdate

### PR DESCRIPTION
**Pull request by tech189**
Relates to Excavator unable to update due to change in file name: https://github.com/ScoopInstaller/Extras/runs/6722644998?check_suite_focus=true#step:3:263

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
That's odd, version appears twice in the name. Is it really intentional?

**Comment by tech189** [comment]
Not sure, only the Windows release has the version number twice: https://github.com/savonet/liquidsoap/releases/tag/v2.0.5

**Comment by issaclin32** [comment]
I have [reported the issue upstream](https://github.com/savonet/liquidsoap/issues/2435) to see if it is a **typo**.

**Comment by issaclin32** [comment]
Fixed upstream: https://github.com/savonet/liquidsoap/issues/2435#issuecomment-1164448839

**Pull request closed without merging**
