### PR TITLE
stirling-pdf: Update to version 0.36.5

### PR DESCRIPTION
**Pull request by Jin1c-3**
- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by rasa — APPROVED** [review]

**Comment by Absolves** [comment]
Failed to create shortcut
image

**Comment by Absolves** [comment]
I think it still needs to be adjusted @Jin1c-3

**Comment by Jin1c-3** [comment]
I can't resolve this issue: in versions 0.36.4 and earlier of the Stirling-pdf repository, the release contains a `portable version` named stirling-pdf.exe. However, this portable version is `absent` in versions 0.35.5 and later. I also tried using `innounp`, but it does not support the Stirling-pdf installation package. Can you help resolve this problem?

> I think it still needs to be adjusted @Jin1c-3

**Comment by milnak** [comment]
I looked into this.  The portable app is now "Stirling-PDF-Server.exe".  `https://github.com/Stirling-Tools/Stirling-PDF/releases/download/v0.36.6/Stirling-PDF-Server.exe`. Should be an easy manifest fix.

**Comment by Gestrid** [comment]
Copying my comment from the above linked related issue:

This still seems to be an issue. v0.37.0 was just released to Scoop, and the issue hasn't been fixed.

Log of the attempted install below:

```
Installing 'stirling-pdf' (0.37.0) [64bit] from 'extras' bucket
Stirling-PDF-win-installer.exe (150.4 MB) [===================================================================] 100%
Checking hash of Stirling-PDF-win-installer.exe ... ok.
Linking ~\scoop\apps\stirling-pdf\current => ~\scoop\apps\stirling-pdf\0.37.0
Creating shortcut for Stirling-PDF (Stirling-PDF.exe) failed: Couldn't find C:\Users\[USER]\scoop\apps\stirling-pdf\current\Stirling-PDF.exe
Persisting configs
Persisting customFiles
Persisting logs
'stirling-pdf' (0.37.0) was installed successfully!
```

Obviously, the text at the bottom isn't true.

**Comment by Jin1c-3** [comment]
I fixed this issue in pull request #14682 , but I am unsure why it has not been merged yet.

**Pull request merged**
