### PR TITLE
threema: Fix `pre_install` for PowerShell 5

### PR DESCRIPTION
**Pull request by Zliced13**
- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tech189** [comment]
Could you explain why you propose this change? I am able to install the manifest okay as-is.

**Comment by Zliced13** [comment]
I changed it because `Rename-Item` does not work with wildcards in **PowerShell 5**, I made this change to make it backwards compatible.

**Review by tech189 — APPROVED** [review]
Thanks!

**Pull request merged**
