### PR TITLE
mullvad-browser: Add version 12.0.4

### LINKED ISSUE #10888: [Request]: Mullvad Browser
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

Mullvad Browser

### Description

The Mullvad Browser is developed – in collaboration between Mullvad VPN and the Tor Project – to minimize tracking and fingerprinting.

### Homepage

https://mullvad.net/en/browser

### Download Link(s)

https://mullvad.net/en/download/browser/win64/latest

### Some Indication of Popularity/Repute

Mullvad VPN is a popular VPN service provider.

### PR DESCRIPTION
**Pull request by Zliced13**
Closes #10888

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by StarsbySea — CHANGES_REQUESTED** [review]
With these modifications I think it's good.
屏幕截图 2023-04-04 212924

**Review by StarsbySea — APPROVED** [review]

**Review by HUMORCE — APPROVED** [review]

**Pull request merged**
