### PR TITLE
macast-debug: Add version 0.7

### LINKED ISSUE #7862: [Request] macast-debug V0.7
### Information

**Name:** macast-debug

**Description:** debug version of macast

**Homepage:** https://github.com/xfangfang/Macast

**Download link(s):** https://github.com/xfangfang/Macast/releases/

**Some indication of popularity/repute:**

### PR DESCRIPTION
**Pull request by happytommyl**
Debug version for `macast`, with command-line output.

Closes #7862

Relates to #7862 and  #7758

- [ -] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by issaclin32** [comment]
I think this needs to be in [Versions bucket](https://github.com/ScoopInstaller/Versions).

**Comment by rashil2000** [comment]
I'm fine with adding this here, since it's stable after all.

**Comment by issaclin32** [comment]
> I'm fine with adding this here, since it's stable after all.
Ok. Let's keep it here.

**Review by issaclin32 — APPROVED** [review]

**Pull request merged**
