### PR TITLE
camo-studio: Add version 1.1.6.7135

### LINKED ISSUE #8325: [Request] Camo Studio
### Information

**Name:** Camo Studio

**Description:** Use your phone as a webcam

**Homepage:** https://reincubate.com/camo/

**Download link(s):** https://reincubate.com/res/labs/camo/camo-windows-latest.msi

**Some indication of popularity/repute:**
The [mobile counterpart](https://apps.apple.com/us/app/camo-webcam-for-mac-and-pc/id1514199064) to the app carries a 4.8 star rating from 1.6K reviews.

### PR DESCRIPTION
**Pull request by MathewBlock**
Closes #8325 

Adds Camo Studio app used as a bridge to allow phones to become Windows recognized webcams.

- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
Just making sure: this is a 32bit app right?

**Comment by MathewBlock** [comment]
I thought it was, but I just checked, it's 64bit.
I'll need to commit an update to mark that up properly in the manifest.

**Comment by rashil2000** [comment]
Sure, please do!

**Pull request merged**
