### PR TITLE
ilspy: update to 7.1.0.6543

### PR DESCRIPTION
**Pull request by pratikpc**
add missing autoupdate

close https://github.com/ScoopInstaller/Extras/issues/6293

@rubenprins could you check this once?

I personally don't use ILSPY

### CODE REVIEW

**Comment by rubenprins** [comment]
@pratikpc looks like the right version & download URL 👍

**Comment by pratikpc** [comment]
@rubenprins could you install ILSPY from this file and check if it works?

Or if changes need to be made?

Because even if we have correct URLs, we might need to make other changes

**Comment by rubenprins** [comment]
@pratikpc Installing the app definition from this PR works:
```
scoop install https://raw.githubusercontent.com/ScoopInstaller/Extras/b260437ef4730a39d3741f524d15938a36f5cd50/bucket/ilspy.json
```
So, no need for additional changes, I guess.

**Comment by pratikpc** [comment]
@rubenprins after that you were able to use it without issues as well right?

Try some production workloads with it once

**Comment by rubenprins** [comment]
@pratikpc Yes, the app works fine this way. In fact, I normally update the app in exactly the same way as Scoop does: extract the zip file into some user folder, and run ILSpy.exe. User settings are stored in your AppData.

**Review by issaclin32 — APPROVED** [review]

**Pull request merged**
