### PR TITLE
k8s-pixy-auth: Add version 0.5.0

### PR DESCRIPTION
**Pull request by 0x326**
Closes https://github.com/ScoopInstaller/Main/pull/5377

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by StudentWeis** [comment]
This repository has stopped maintenance.

**Comment by 0x326** [comment]
@StudentWeis Sorry, I didn't realize the Extras bucket didn't accept archived applications. Do you know of a bucket that does? My company still actively uses this program and it'd be nice to have Scoop install it for us!

**Comment by 0x326** [comment]
@StudentWeis Any thoughts on where this package should live?

**Pull request closed without merging**
