### PR TITLE
sirikali: Add version 1.5.0

### PR DESCRIPTION
**Pull request by sitiom**
- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
32bit or 64bit?

**Comment by sitiom** [comment]
> 32bit or 64bit?

32-bit (and you can use it on 64-bit).

**Comment by rashil2000** [comment]
/verify

You should comment `/verify` after each commit in a PR

**Comment by sitiom** [comment]
> /verify
> 
> You should comment `/verify` after each commit in a PR. And add a basic description in the PR about what the new package is

Noted, I tend to forget. And the description is in the manifest.

**Pull request merged**
