### PR TITLE
010editor: Update manifest

### LINKED ISSUE #10657: [Bug]: 010 Editor - Change from portable to normal install
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

010editor

### Expected/Current Behaviour

it currently uses the portable version of 010 editor which has limited functionality. the full version is a better package to install.

### Steps to Reproduce

```console
scoop install 010editor
open and observe window title bar includes "portable"
```

### Possible Solution

use full installer rather than portable

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
a95293c7b (HEAD -> master, origin/master, origin/HEAD) icnsify: Add version 2.2.1 (#10612)

'main' bucket:
ebdbf8678 (HEAD -> master, origin/master, origin/HEAD) fastfetch: Update to version 1.10.3
```

### Scoop Config

```console
last_update                       scoop_branch scoop_repo
-----------                       ------------ ----------
2023-03-03T09:41:47.6681551-08:00 master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.22621.963
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.963
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Additional Softwares

_No response_

### PR DESCRIPTION
**Pull request by FlawlessCasual17**
Added `autoupdate.hash`, Added `post_install` & `pre_uninstall`, updated `notes`, and fixed `bin`.

Closes #10657

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Zliced13** [comment]
@JamesHabben Could you please test this for me to see if works for your needs?
```pwsh
scoop bucket add MyScoop 'https://github.com/Zliced13/MyScoop'
```
```
scoop install 010editor_fixed
```

**Comment by JamesHabben** [comment]
I tried running this but get an error protocol “https” is not supported.

On Apr 10, 2023, at 1:48 PM, Kris Schneider ***@***.***> wrote:



@JamesHabben<https://github.com/JamesHabben> Could you please test this for me to see if it works for your needs?

scoop bucket add MyScoop 'https://github.com/Zliced13/MyScoop'

scoop install 010editor_fixed

**Comment by Zliced13** [comment]
@JamesHabben is everything ok? You haven't responded to this discussion in a while.

**Pull request closed without merging**
