### PR TITLE
Add opam manifest

### LINKED ISSUE #14217: [Request]: opam
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

opam

### Description

A Package Manager for OCaml

### Homepage

https://github.com/ocaml/opam

### Download Link(s)

https://github.com/ocaml/opam/releases

### Some Indication of Popularity/Repute

1.2k github stars

### PR DESCRIPTION
**Pull request by xoriath**
Add manifest of the opam cli from https://github.com/ocaml/opam

Closes #14217

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aliesbelik** [comment]
Duplicates PR already created in Main bucket: ScoopInstaller/Main#6196.

**Comment by xoriath** [comment]
Argh, I didn't find a Issue for opam in the main bucket and assumed there wouldn't be a PR for it :)

**Pull request closed without merging**
