### PR TITLE
dart-sass-embedded: Add version 1.56.1

### LINKED ISSUE #9856: [Request]: Embedded Dart Sass
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

Embedded Dart Sass

### Description

A wrapper for Dart Sass that implements the compiler side of the Embedded Sass protocol

### Homepage

https://github.com/sass/dart-sass-embedded

### Download Link(s)

https://github.com/sass/dart-sass-embedded/releases

### Some Indication of Popularity/Repute

Embedded Dart Sass is a wrapper for [Dart Sass] that implements the compiler side of the [Embedded Sass protocol]. It's designed to be embedded in a host language, which then exposes an API for users to invoke Sass and define custom functions and importers.

[Hugo], a popular static site generator written in Go, requires Embedded Dart Sass to transpile Sass to CSS using Dart Sass. Dart Sass is now the primary implementation of Sass.

Hugo is available in the main bucket, with over 1000 stars.

[Dart Sass]: https://sass-lang.com/dart-sass
[Embedded Sass protocol]: https://github.com/sass/sass-embedded-protocol/blob/master/README.md#readme
[Hugo]: https://gohugo.io/

### PR DESCRIPTION
**Pull request by jmooring**
Closes #9856

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by HUMORCE** [comment]
I think this manifest should be submitted to [main bucket](https://github.com/ScoopInstaller/Main).

related: https://github.com/ScoopInstaller/Main/blob/master/bucket/sass.json

**Comment by jmooring** [comment]
@HUMORCE As a utility app, it seems like a better fit for the extras bucket, but I'm OK either way.

**Comment by jmooring** [comment]
@HUMORCE  

> I think this manifest should be submitted to [main bucket](https://github.com/ScoopInstaller/Main).

I may have made a mistake. Perhaps you can answer this question.

If an app in main has a dependency (`depends` in manifest) on something in extras, and if the user has not added the extras bucket, what will happen?

I apologize this if is documented somewhere that I couldn't find. My local testing is inconclusive.

**Comment by jmooring** [comment]
Sorry for the noise. I tested an app from main, termshark, that depends on extras/wireshark. If the user has not added the extras bucket, the installation of termshark fails.

I will submit a PR to remove from extras, and a PR to create in main.

**Comment by HUMORCE** [comment]
unless actively removes, all users added main and extras buckets by default.

**Pull request merged**
