### PR TITLE
KakaoTalkAdBlock: Add version 2.1.4

### LINKED ISSUE #12883: [Request]: KakaoTalkAdBlock
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [x] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

KakaoTalkAdBlock

### Description

AdBlocker for KakaoTalk Windows client.

### Homepage

https://kakao.xo.dev/
https://github.com/blurfx/KakaoTalkAdBlock

### Download Link(s)

https://github.com/blurfx/KakaoTalkAdBlock/releases/download/2.0.0/KakaoTalkAdBlock_amd64.exe
https://github.com/blurfx/KakaoTalkAdBlock/releases/download/2.0.0/KakaoTalkAdBlock_i386.exe

### Some Indication of Popularity/Repute

521 stars --> https://github.com/blurfx/KakaoTalkAdBlock/stargazers

### PR DESCRIPTION
**Pull request by oxjihun**
Adds `KakaoTalkAdBlock` (2.0.0) to the bucket. 

Closes #12883

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aliesbelik** [comment]
Please add [autoupdate](https://github.com/ScoopInstaller/Scoop/wiki/App-Manifest-Autoupdate#adding-autoupdate-to-a-manifest) section as well.

**Comment by aliesbelik** [comment]
Virustotal reports a lot of problems:
https://www.virustotal.com/gui/file/951e277d65ac26c15437c24f0cd40983690321c104c491791035a420d62f8623

Even if false positive (blurfx/KakaoTalkAdBlock#83, blurfx/KakaoTalkAdBlock#85), guess this could cause problems on installation via scoop, when antivirus blocks installation or quarantines downloaded binaries in case of threat detection.

**Comment by oxjihun** [comment]
I apologize for making a pull request for a possibly malicious app. 

To get things straight, I'd have to admit that I was partially aware of this. When writing the manifest for version 2.0.0, Windows Defender's inhibition was the main reason I couldn't include the 32bit version. There was no problem with 64bit version though. Since the program was regionally well known (at least I thought so), I regarded the 64bit version as safe. Never considered of running VirusTotal. 

And yesterday, when writing the manifest for version 2.1.4, Windows Defender didn't raise any issues for downloading both 32bit and 64bit versions. I vaguely assumed that the false positive got fixed. Therefore, I proceeded to make a second commit. 

Now I come to think of it, for transparency, I must have elaborated any issues upon opening the pull request. As this is my first time contributing to a large project on GitHub, I am still learning how to contribute 'well'. Though I know this is a mere excuse. I deeply apologize for all this inconvenience. 

According to https://github.com/blurfx/KakaoTalkAdBlock/issues/85#issuecomment-2076390482, the dev managed to get the 2.1.4 version binaries removed from the malware detection list. With this, is there any chance that this manifest could be added to the Extras bucket?

Thank you.

**Comment by oxjihun** [comment]
Closed because there haven't been new releases since 2.1.4 which were problematic on VirusTotal.

**Pull request closed without merging**
