### PR TITLE
attribute-changer: Update the manifest.

### PR DESCRIPTION
**Pull request by Zliced13**
Changed the `notes`, `post_install`, `pre_uninstall`, and `autoupdate.hash` sections.

@rasa, if you have any questions feel free to ask.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by HUMORCE** [comment]
Could you shorten the `notes`?

exmaple:

just prompts users run `change-ac-language.ps1 --help` to change language:
```
Useage:
    change-ac-language <language-id>    Change interface language.
        1 = CZECH
        2 = DANISH
        3 = FRENCH
        ...
```

**Comment by Zliced13** [comment]
@HUMORCE sure

**Comment by Zliced13** [comment]
@HUMORCE it's done, the manifest is ready to go.

**Pull request merged**
