### PR TITLE
halloy: Add version 2024.7

### LINKED ISSUE #13037: [Request]: halloy
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

halloy

### Description

Halloy is an open-source IRC client written in Rust, with the iced GUI library.

### Homepage

https://halloy.squidowl.org

### Download Link(s)

https://github.com/squidowl/halloy/releases

### Some Indication of Popularity/Repute

Github: 907 stars, 28 forks

### PR DESCRIPTION
**Pull request by ghost64**
This is a open-source IRC client written in Rust using the iced GUI library.

Closes #13037.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ghost64** [comment]
Created #13037

**Comment by aliesbelik** [comment]
halloy_20240430_040926_1714439366

Running for the first time after installation results in configuration parsing error that seems to be caused by empty config.toml, pre-created in `pre_install` section.
Removing it allows to pass to the simplified onboarding screen that seems to be normal flow.

Looks like manifest needs to be adjusted a bit (see e.g. [extras/qtox](https://github.com/ScoopInstaller/Extras/blob/master/bucket/qtox.json)) to handle this situation.

**Pull request merged**
