### PR TITLE
gephi: Update to version 0.9.3, fix autoupdate

### PR DESCRIPTION
**Pull request by tech189**
Relates to Excavator unable to autoupdate: https://github.com/ScoopInstaller/Extras/runs/5864968342?check_suite_focus=true#step:3:220

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
The `-x64` might mean that it needs an architecture 64bit block now

**Comment by tech189** [comment]
No it looks like it still ships 32-bit and 64-bit binaries. But I need to fix the post_install script as they now bundle the JRE, so no need to edit the conf to point to `JAVA_HOME`

**Comment by tech189** [comment]
Fixed now, I have tested updating from 0.9.2 to 0.9.3 and installing from scratch.

**Pull request merged**
