### PR TITLE
cheat-engine: Undeprecate manifest

### LINKED ISSUE #7414: cheat-engine is removed from this bucket?
Will it be added back or it's not allowed any longer or something?

### PR DESCRIPTION
**Pull request by rashil2000**
Closes #7414

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Stzx** [comment]
Hey, I think we should remove this package, the full installer is no longer available directly on `github` since [Cheat Engine 7.1](https://github.com/cheat-engine/cheat-engine/releases/tag/7.1). The exe in the current file is just the downloader.

**Comment by rashil2000** [comment]
Maybe we can use the URL that the downloader uses? It might be available in the source code.

**Comment by Stzx** [comment]
I don't think it's included in the source code(maybe I'm missing something), and whether extracting the link to use it violates some kind of license, I don't know.

**Comment by rashil2000** [comment]
Can you open an issue in their repo for advice? It would be best to ask them.

**Pull request merged**
