### PR TITLE
gb-studio: Update to version 3.0.2

### LINKED ISSUE #7608: [Request] Update GB Studio to version 3.x and fix autoupdate section
## Package Request

GB Studio version 3.0.2

Package already has a manifest file, but for the reasons it stopped on version 1.2.1. It's probably because they change release artifacts.

@littleli would like to volunteer on the issue. PR in progress.

### Information

**Name:** GB Studio version 3.0.2

**Description:** A quick and easy to use drag and drop retro game creator for your favourite handheld video game system

**Homepage:** [GB Studio](https://www.gbstudio.dev/)

**Download link(s):** [Github releases](https://github.com/chrismaltby/gb-studio/releases)

### PR DESCRIPTION
**Pull request by littleli**
- Manual changes to update to version 3.0.2
- Fixes `autoupdate` section.

Closes #7608

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
/verify

Does the binary take any commandline arguments?

**Comment by littleli** [comment]
> /verify
> 
> Does the binary take any commandline arguments?

Not sure to be honest. But it has a UI, so I expect the major use is through the UI.

gbstudio

**Comment by rashil2000** [comment]
In that case we can remove the bin field

**Comment by littleli** [comment]
> In that case we can remove the bin field

Got it! Done.

**Pull request merged**
