### PR TITLE
virt-viewer: Update to version 11.0-1.0 and add autoupdate

### PR DESCRIPTION
**Pull request by LazyGeniusMan**
Closes #XXXX

Relates to #XXXX

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
You hardcoded the version in URLs in autoupdate

**Comment by rashil2000** [comment]
The URL and hash are still pointing to 10.0-1.0

**Comment by LazyGeniusMan** [comment]
> The URL and hash are still pointing to 10.0-1.0

sorry apparently it's because autoupdate schema is wrong so it's not updating correctly with checkver, fixed

**Pull request merged**
