### PR TITLE
gog-galaxy: Add version 2.0.62.26

### LINKED ISSUE #7124: (Request) add gog-galaxy
PackageIdentifier: gog galaxy
PackageVersion: 2.0
PackageLocale: en-US
Publisher: gog
PackageName: gog-galaxy
License: proprietary
ShortDescription: gog client app
Installers:

Architecture: x64
InstallerType: exe
InstallerUrl: https://webinstallers.gog-statics.com/download/GOG_Galaxy_2.0.exe?payload=osaO9UIQ-Jj0k2sUzLcRpS00TxEHkUyWP9rIr-AWbjONXl8igETiJm36h3lRyDMywYv9JhBmJ6XAgt-xKmIvzaM6srUd7J37ROb3lVZh9rkEOO527VQ59l1oGWnLYXflrkTfTjJmhkwZe92fgxJdi6QXLYSrVnGu6WOZKHoG7tmzOlOcNj1wbNAUENGxA5EIwApq3QpesrQ1lAZC4aj1Ir_zRR0Luc-0jMdge0NPAWSZtUN23nd0P9ztm1Lnb-QwfUcfSMAuv7aooAPhIFIaxzak72fc3ArCPAuH8PJgYnpFGk6qZRdXOiGCUMg8i-eYtsbrjQm8H6uS8y71eoh4uRzr9nK6e4c1cSnOeohF930ll9pAMBNUfdXK9k_Xec4vMikPaDHd6QVM1G6MkpnZdMOqEvJ8zfHRU9qTilbjVsJutyE8rhqAU0o7Vn1Lc2Q2tgRY5Vc28Xq5XtXT4nqvSteUSz3WVO54vuI5ORsX4NqLPS4QAxSVABRXcOjyBoT4DqEJ5OV4of2VS5WMocQidhIaRnVkd5pq0NG3tO_yu_IRv0vAD-EjIfqLk2kvJL5BxQXjd8OO7G1OCs1-rxFOmDCliiiY6xOtiaeQnwt8ypKhQe0DvErb8gU3LG-SHnvzVPfla8REggDBDGa_mqYESWyr5mgQgMgSNaezP7GGmbgbfHi1pyXi4gJTFDyW8hxFJA2zQIYRp8d7BvbQlBaWWScnOecn5py-CJgvBTOKd19wPwzJ8bPWXlXTiap3YX0yF4lmRtGeoAKvnmg.
ManifestType: singleton
ManifestVersion: 1.0.0

### PR DESCRIPTION
**Pull request by brian6932**
Closes #7124

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by jasongodev — COMMENTED** [review]
This should be in some other Scoop bucket, perhaps in Scoop Games: https://github.com/Calinou/scoop-games

**Comment by brian6932** [comment]
@jasongodev incorrect https://github.com/Calinou/scoop-games/blob/master/CONTRIBUTING.md

**Comment by brian6932** [comment]
Yea, that lgtm

**Pull request closed without merging**
