### PR TITLE
Update sumatrapdf.json

### PR DESCRIPTION
**Pull request by wu0lss4j**
bump to 3.5.2 version according to https://www.sumatrapdfreader.org/docs/Version-history

Closes #XXXX

Relates to #XXXX

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by YDX-2147483647** [comment]
I guess this is duplicate of #12057?

**Comment by wu0lss4j** [comment]
> I guess this is a duplicate of #12057?

I'm still learning my way around gihub and I didn't get the notification regarding #12057 and thought my update proposal was deleted for not complying to some rule or standard, dunno. Therefore I created this one carefully checking all the code to see what could be missing. Now I know that the URL was not missing, and the curret proposal #12098 I think is in fact working.

Sorry in advance...

**Comment by wu0lss4j** [comment]
I think the developer changed some protocol or something, because if you enter https://www.sumatrapdfreader.org/dl/rel/3.5.2/SumatraPDF-3.5.2-64.zip into the web browser it will trigger a download operation. If you enter https://www.sumatrapdfreader.org//dl//rel/3.4.6/SumatraPDF-3.4.6-64.zip it will also trigger a download operation, notice the double fwd slash. Finally, this link https://files.sumatrapdfreader.org/file/kjk-files/software/sumatrapdf/rel/3.4.6/SumatraPDF-3.4.6-64.zip when pasted into the browser will yield the error → _files.sumatrapdfreader.org uses an unsupported protocol. ERR_SSL_VERSION_OR_CIPHER_MISMATCH_

But if you place any of those links in the relevant scoop's json file it will yield an error as follows → 
_ERROR Download failed! (Error 22) HTTP response header was bad or unexpected
ERROR https://www.sumatrapdfreader.org/dl/rel/3.5.2/SumatraPDF-3.5.2-64.zip
    referer=https://www.sumatrapdfreader.org/dl/rel/3.5.2/_

I'm stumped. There is a note on this page https://www.sumatrapdfreader.org/download-prev saying: _Note: links are just text to avoid bandwidth charges due to spidering. To download, copy the link and paste into browser's url bar._

**Comment by YDX-2147483647** [comment]
I try your URLs in my terminal with [HTTPie](https://httpie.io/docs/cli), and find that `//` version is redirected to the normal version, which is redirected to `files2.sumatrapdfreader.org`, and your third URL turns into SSLError.

```shell
$ https www.sumatrapdfreader.org//dl//rel/3.5.2/SumatraPDF-3.5.2-64.zip
HTTP/1.1 307 Temporary Redirect
location: /dl/rel/3.5.2/SumatraPDF-3.5.2-64.zip
…

$ https www.sumatrapdfreader.org/dl/rel/3.5.2/SumatraPDF-3.5.2-64.zip
HTTP/1.1 307 Temporary Redirect
location: https://files2.sumatrapdfreader.org/software/sumatrapdf/rel/3.5.2/SumatraPDF-3.5.2-64.zip
…

$ https files2.sumatrapdfreader.org/software/sumatrapdf/rel/3.5.2/SumatraPDF-3.5.2-64.zip
HTTP/1.1 200 OK
Content-Type: application/x-zip-compressed
…
+-----------------------------------------+
| NOTE: binary data not shown in terminal |
+-----------------------------------------+

$ https files.sumatrapdfreader.org/file/kjk-files/software/sumatrapdf/rel/3.4.6/SumatraPDF-3.4.6-64.zip
https: error: SSLError: HTTPSConnectionPool(host='files.sumatrapdfreader.org', port=443): Max retries exceeded with url: /file/kjk-files/software/sumatrapdf/rel/3.4.6/SumatraPDF-3.4.6-64.zip (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1006)'))) while doing a GET request to URL: https://files.sumatrapdfreader.org/file/kjk-files/software/sumatrapdf/rel/3.4.6/SumatraPDF-3.4.6-64.zip
```

**Comment by wu0lss4j** [comment]
Thanks so much for looking into this. Today I saw that scoop already detected the new version 3.5.2 however the script still failed on my machine, when I disabled aria2c then it worked flawlessly. I opened a new issue for this → https://github.com/ScoopInstaller/Extras/issues/12156

Anyhow, TIL of this new utility called httpie, thanks so much!

> I try your URLs in my terminal with [HTTPie](https://httpie.io/docs/cli), and find that `//` version is redirected to the normal version, which is redirected to `files2.sumatrapdfreader.org`, and your third URL turns into SSLError.
> 
> ```shell
> $ https www.sumatrapdfreader.org//dl//rel/3.5.2/SumatraPDF-3.5.2-64.zip
> HTTP/1.1 307 Temporary Redirect
> location: /dl/rel/3.5.2/SumatraPDF-3.5.2-64.zip
> …
> 
> $ https www.sumatrapdfreader.org/dl/rel/3.5.2/SumatraPDF-3.5.2-64.zip
> HTTP/1.1 307 Temporary Redirect
> location: https://files2.sumatrapdfreader.org/software/sumatrapdf/rel/3.5.2/SumatraPDF-3.5.2-64.zip
> …
> 
> $ https files2.sumatrapdfreader.org/software/sumatrapdf/rel/3.5.2/SumatraPDF-3.5.2-64.zip
> HTTP/1.1 200 OK
> Content-Type: application/x-zip-compressed
> …
> +-----------------------------------------+
> | NOTE: binary data not shown in terminal |
> +-----------------------------------------+
> 
> $ https files.sumatrapdfreader.org/file/kjk-files/software/sumatrapdf/rel/3.4.6/SumatraPDF-3.4.6-64.zip
> https: error: SSLError: HTTPSConnectionPool(host='files.sumatrapdfreader.org', port=443): Max retries exceeded with url: /file/kjk-files/software/sumatrapdf/rel/3.4.6/SumatraPDF-3.4.6-64.zip (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1006)'))) while doing a GET request to URL: https://files.sumatrapdfreader.org/file/kjk-files/software/sumatrapdf/rel/3.4.6/SumatraPDF-3.4.6-64.zip
> ```

**Pull request closed without merging**
