### PR TITLE
streamlink: Update to version 3.0.1

### PR DESCRIPTION
**Pull request by book000**
Update [streamlink](https://streamlink.github.io/) to [3.0.1](https://github.com/streamlink/streamlink/releases/tag/3.0.1). (Previously it was [2.0.4](https://github.com/streamlink/streamlink/releases/tag/2.4.0))

Sorry. This pull request is not an existing issue. If I need to create an issue first, close this pull request.

### CODE REVIEW

**Comment by issaclin32** [comment]
`pre_install` needs to be removed.
*StreamLink* still stores its data in `$env:AppData`, but `$dir\$APPDATA` does not exist anymore.
This leads to an error.

**Comment by book000** [comment]
> `pre_install` needs to be removed. _StreamLink_ still stores its data in `$env:AppData`, but `$dir\$APPDATA` does not exist anymore. This leads to an error.

Please forgive my lack of knowledge.

I'm thinking that if I remove `pre_install` completely, it won't be able to handle `uninstall.exe` and ffmpeg, which are installed by Scoop.
May I make the following changes?

```diff
diff --git a/bucket/streamlink.json b/bucket/streamlink.json
index 9423efdf6..86b3f8707 100644
--- a/bucket/streamlink.json
+++ b/bucket/streamlink.json
@@ -13,11 +13,6 @@
     "url": "https://github.com/streamlink/streamlink/releases/download/3.0.1/streamlink-3.0.1.exe#/dl.7z",
     "hash": "e83bacdfe2f7892f7b6c9ef39714dd7f47ff07f64e9cd3a2b6b1a5d45af46e41",
     "pre_install": [
-        "if (!(Test-Path \"$env:APPDATA\\streamlink\\streamlinkrc\")) {",
-        "    info 'Copying default ''streamlinkrc'' to ''%APPDATA%\\streamlink\\streamlinkrc'''",
-        "    ensure \"$env:APPDATA\\streamlink\" | Out-Null",
-        "    Copy-Item \"$dir\\`$APPDATA\\streamlink\\streamlinkrc\" \"$env:APPDATA\\streamlink\\streamlinkrc\"",
-        "}",
         "Remove-Item \"$dir\\`$*\", \"$dir\\ffmpeg\", \"$dir\\uninstall.exe\" -Recurse"
     ],
     "uninstaller": {

```

**Comment by issaclin32** [comment]
> Please forgive my lack of knowledge.

No worries. I am grateful about users make their efforts improving *Scoop*. We just need some testing to prevent errors.

> I'm thinking that if I remove `pre_install` completely, it won't be able to handle `uninstall.exe` and ffmpeg, which are installed by Scoop. May I make the following changes?
> 
> ```diff
> diff --git a/bucket/streamlink.json b/bucket/streamlink.json
> index 9423efdf6..86b3f8707 100644
> --- a/bucket/streamlink.json
> +++ b/bucket/streamlink.json
> @@ -13,11 +13,6 @@
>      "url": "https://github.com/streamlink/streamlink/releases/download/3.0.1/streamlink-3.0.1.exe#/dl.7z",
>      "hash": "e83bacdfe2f7892f7b6c9ef39714dd7f47ff07f64e9cd3a2b6b1a5d45af46e41",
>      "pre_install": [
> -        "if (!(Test-Path \"$env:APPDATA\\streamlink\\streamlinkrc\")) {",
> -        "    info 'Copying default ''streamlinkrc'' to ''%APPDATA%\\streamlink\\streamlinkrc'''",
> -        "    ensure \"$env:APPDATA\\streamlink\" | Out-Null",
> -        "    Copy-Item \"$dir\\`$APPDATA\\streamlink\\streamlinkrc\" \"$env:APPDATA\\streamlink\\streamlinkrc\"",
> -        "}",
>          "Remove-Item \"$dir\\`$*\", \"$dir\\ffmpeg\", \"$dir\\uninstall.exe\" -Recurse"
>      ],
>      "uninstaller": {
> ```

`ffmpeg`, `$PLUGINSDIR` and `uninstall.exe` does not exist anymore.
By the way, I think we should add this:
```
"suggest": {
    "VLC Player": "extras/vlc"
}
```
**suggest** is for something that the program (i.e. *streamlink*) needs. However, some users may already installed it through other means than *Scoop*. Which makes it not proper to use **depends**. 


**DIRECTORY STRUCTURE:**
```
> tree "$Env:SCOOP\apps\streamlink\current"
D:\SCOOP\APPS\STREAMLINK\CURRENT
├─bin
├─pkgs
│  ├─certifi
│  │  └─__pycache__
│  ├─certifi-2021.10.8.dist-info
│  ├─charset_normalizer
│  │  ├─assets
│  │  │  └─__pycache__
│  │  ├─cli
│  │  └─__pycache__
│  ├─charset_normalizer-2.0.7.dist-info
│  ├─Crypto
│  │  ├─Cipher
│  │  │  └─__pycache__
│  │  ├─Hash
│  │  │  └─__pycache__
│  │  ├─IO
│  │  ├─Math
│  │  │  └─__pycache__
│  │  ├─Protocol
│  │  │  └─__pycache__
│  │  ├─PublicKey
│  │  │  └─__pycache__
│  │  ├─Random
│  │  │  └─__pycache__
│  │  ├─SelfTest
│  │  │  ├─Cipher
│  │  │  ├─Hash
│  │  │  ├─IO
│  │  │  ├─Math
│  │  │  ├─Protocol
│  │  │  ├─PublicKey
│  │  │  ├─Random
│  │  │  ├─Signature
│  │  │  └─Util
│  │  ├─Signature
│  │  ├─Util
│  │  │  └─__pycache__
│  │  └─__pycache__
│  ├─idna
│  │  └─__pycache__
│  ├─idna-3.3.dist-info
│  ├─isodate
│  │  ├─tests
│  │  └─__pycache__
│  ├─isodate-0.6.0.dist-info
│  ├─lxml
│  │  ├─html
│  │  ├─includes
│  │  │  ├─libexslt
│  │  │  ├─libxml
│  │  │  └─libxslt
│  │  ├─isoschematron
│  │  │  └─resources
│  │  │      ├─rng
│  │  │      └─xsl
│  │  │          └─iso-schematron-xslt1
│  │  └─__pycache__
│  ├─lxml-4.6.4.dist-info
│  ├─pkg_resources
│  │  ├─extern
│  │  │  └─__pycache__
│  │  ├─tests
│  │  │  └─data
│  │  │      └─my-test-package-source
│  │  ├─_vendor
│  │  │  ├─packaging
│  │  │  │  └─__pycache__
│  │  │  └─__pycache__
│  │  └─__pycache__
│  ├─pycountry
│  │  ├─databases
│  │  ├─locales
│  ├─pycountry-20.7.3.dist-info
│  ├─pycryptodome-3.11.0.dist-info
│  ├─PySocks-1.7.1.dist-info
│  ├─requests
│  │  └─__pycache__
│  ├─requests-2.26.0.dist-info
│  ├─six-1.16.0.dist-info
│  ├─streamlink
│  │  ├─packages
│  │  │  └─__pycache__
│  │  ├─plugin
│  │  │  ├─api
│  │  │  │  └─__pycache__
│  │  │  └─__pycache__
│  │  ├─plugins
│  │  │  └─__pycache__
│  │  ├─stream
│  │  │  └─__pycache__
│  │  ├─utils
│  │  │  └─__pycache__
│  │  └─__pycache__
│  ├─streamlink_cli
│  │  ├─utils
│  │  │  └─__pycache__
│  │  └─__pycache__
│  ├─urllib3
│  │  ├─contrib
│  │  │  ├─_securetransport
│  │  │  └─__pycache__
│  │  ├─packages
│  │  │  ├─backports
│  │  │  ├─ssl_match_hostname
│  │  │  │  └─__pycache__
│  │  │  └─__pycache__
│  │  ├─util
│  │  │  └─__pycache__
│  │  └─__pycache__
│  ├─urllib3-1.26.7.dist-info
│  ├─websocket
│  │  ├─tests
│  │  │  └─data
│  │  └─__pycache__
│  ├─websocket_client-1.2.1.dist-info
│  └─__pycache__
└─Python
```

**Comment by book000** [comment]
Thank you for the concrete and clear explanation.

I removed the `pre_install` and added `VLC Player` to the `suggest`.  
Apply this commit to `scoop install .\bucket\streamlink.json` and performed the directory tree view:

<details>
<summary><code>tree "$Env:SCOOP\apps\streamlink\current"</code></summary>

```
N:\PORTABLE\SCOOP\TOMACHI\APPS\STREAMLINK\CURRENT
├─$APPDATA
│  └─streamlink
├─$PLUGINSDIR
├─bin
├─ffmpeg
├─pkgs
│  ├─certifi
│  ├─certifi-2021.10.8.dist-info
│  ├─charset_normalizer
│  │  ├─assets
│  │  └─cli
│  ├─charset_normalizer-2.0.7.dist-info
│  ├─Crypto
│  │  ├─Cipher
│  │  ├─Hash
│  │  ├─IO
│  │  ├─Math
│  │  ├─Protocol
│  │  ├─PublicKey
│  │  ├─Random
│  │  ├─SelfTest
│  │  │  ├─Cipher
│  │  │  ├─Hash
│  │  │  ├─IO
│  │  │  ├─Math
│  │  │  ├─Protocol
│  │  │  ├─PublicKey
│  │  │  ├─Random
│  │  │  ├─Signature
│  │  │  └─Util
│  │  ├─Signature
│  │  └─Util
│  ├─idna
│  ├─idna-3.3.dist-info
│  ├─isodate
│  │  └─tests
│  ├─isodate-0.6.0.dist-info
│  ├─lxml
│  │  ├─html
│  │  ├─includes
│  │  │  ├─libexslt
│  │  │  ├─libxml
│  │  │  └─libxslt
│  │  └─isoschematron
│  │      └─resources
│  │          ├─rng
│  │          └─xsl
│  │              └─iso-schematron-xslt1
│  ├─lxml-4.6.4.dist-info
│  ├─pkg_resources
│  │  ├─extern
│  │  ├─tests
│  │  │  └─data
│  │  │      └─my-test-package-source
│  │  └─_vendor
│  │      └─packaging
│  ├─pycountry
│  │  ├─databases
│  │  ├─locales
│  │  │  ├─ab
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─ace
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─ach
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─af
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─ak
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─am
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─an
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─ar
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─as
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─ast
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─ay
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─az
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─ba
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─bar
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─be
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─bg
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─bi
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─bn
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─bn_BD
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─bn_IN
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─br
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─bs
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─byn
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─ca
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─ce
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─ch
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─chr
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─ckb
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─crh
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─cs
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─csb
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─cv
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─cy
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─da
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─de
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─dv
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─dz
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─ee
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─el
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─en
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─eo
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─es
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─et
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─eu
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─fa
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─ff
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─fi
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─fo
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─fr
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─frp
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─fur
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─fy
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─ga
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─gez
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─gl
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─gn
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─gu
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─gv
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─ha
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─haw
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─he
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─hi
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─hr
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─ht
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─hu
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─hy
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─ia
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─id
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─io
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─is
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─it
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─iu
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─ja
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─jam
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─ka
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─kab
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─ki
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─kk
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─kl
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─km
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─kn
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─ko
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─kok
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─ku
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─kv
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─kw
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─ky
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─lo
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─lt
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─lv
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─mai
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─mhr
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─mi
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─mk
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─ml
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─mn
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─mo
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─mr
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─ms
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─mt
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─my
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─na
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─nah
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─nb
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─nb_NO
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─ne
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─nl
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─nn
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─nso
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─nv
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─oc
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─or
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─pa
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─pap
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─pi
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─pl
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─ps
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─pt
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─pt_BR
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─ro
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─ru
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─rw
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─sc
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─sd
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─si
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─sk
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─sl
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─so
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─son
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─sq
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─sr
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─sr@latin
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─sv
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─sw
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─ta
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─te
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─tg
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─th
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─ti
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─tig
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─tk
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─tl
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─tr
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─tt
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─tt@iqtelif
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─ug
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─uk
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─ur
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─uz
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─ve
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─vi
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─wa
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─wal
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─wo
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─xh
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─yo
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─zh_CN
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─zh_Hant
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─zh_HK
│  │  │  │  └─LC_MESSAGES
│  │  │  ├─zh_TW
│  │  │  │  └─LC_MESSAGES
│  │  │  └─zu
│  │  │      └─LC_MESSAGES
│  │  └─tests
│  ├─pycountry-20.7.3.dist-info
│  ├─pycryptodome-3.11.0.dist-info
│  ├─PySocks-1.7.1.dist-info
│  ├─requests
│  ├─requests-2.26.0.dist-info
│  ├─six-1.16.0.dist-info
│  ├─streamlink
│  │  ├─packages
│  │  ├─plugin
│  │  │  └─api
│  │  ├─plugins
│  │  ├─stream
│  │  └─utils
│  ├─streamlink_cli
│  │  └─utils
│  ├─urllib3
│  │  ├─contrib
│  │  │  └─_securetransport
│  │  ├─packages
│  │  │  ├─backports
│  │  │  └─ssl_match_hostname
│  │  └─util
│  ├─urllib3-1.26.7.dist-info
│  ├─websocket
│  │  └─tests
│  │      └─data
│  └─websocket_client-1.2.1.dist-info
└─Python
```
</details>

----

> `ffmpeg`, `$PLUGINSDIR` and `uninstall.exe` does not exist anymore.

After running `scoop install .\bucket\streamlink.json`, if you look at `$Env:SCOOP\apps\streamlink\current` in Windows Explorer, I will see `$PLUGINSDIR`, `ffmpeg` and `uninstall.exe`... Is this correct?

image

**Comment by issaclin32** [comment]
Sorry I was wrong. Please forgive me carelessness. :dizzy_face:
I didn't remove this line `Remove-Item \"$dir\\`$*\", \"$dir\\ffmpeg\", \"$dir\\uninstall.exe\" -Recurse` before testing.

`$dir\\$APPDATA` still exists as default config file, but the file name is different now. We can update the `pre_install` block as:

```
    "pre_install": [
        "if (!(Test-Path \"$env:APPDATA\\streamlink\\config\")) {",
        "    info 'Copying default ''config'' to ''%APPDATA%\\streamlink\\config'''",
        "    ensure \"$env:APPDATA\\streamlink\" | Out-Null",
        "    Copy-Item \"$dir\\`$APPDATA\\streamlink\\config\" \"$env:APPDATA\\streamlink\\config\"",
        "}",
        "Remove-Item \"$dir\\`$*\", \"$dir\\ffmpeg\", \"$dir\\uninstall.exe\" -Recurse"
    ],
```

and update `notes` as:
`"notes": "Streamlink settings can be changed in '%APPDATA%\\streamlink\\config'",`

**Comment by book000** [comment]
I have applied the `pre_install` and `notes` you provided! 👍
I could also confirm that the unnecessary files were removed from the directory.

image

Please let me know if there is anything else that needs to fix.

**Review by issaclin32 — APPROVED** [review]

**Pull request merged**
