### PR TITLE
live777 0.3.1

### PR DESCRIPTION
**Pull request by Yin-ZP**
Closes #XXXX

Relates to #XXXX

- [ ] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by HUMORCE** [comment]
- Incomplete manifests
- 1 PR for 1 manifest

**Comment by Yin-ZP** [comment]
> * Incomplete manifests
> * 1 PR for 1 manifest

what content should i add?

**Comment by HUMORCE** [comment]
`checkver`, `autoupdate`, and `architecture.64bit` because you are adding x86_64 programs.

**Comment by Yin-ZP** [comment]
Thanks！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ScoopInstaller/Extras"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月13日(星期六) 晚上9:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ScoopInstaller/Extras] live777 0.3.1 (PR #12601)





 
checkver, autoupdate, and architecture.64bit because you are adding x86_64 programs.

**Comment by HUMORCE** [comment]
These programs are published in the same repository, download them in single manifest are allowed, if they are highly bundled.

**Comment by Yin-ZP** [comment]
> `checkver`, `autoupdate`, and `architecture.64bit` because you are adding x86_64 programs.
how to write checkver?

> `checkver`, `autoupdate`, and `architecture.64bit` because you are adding x86_64 programs.

This means description and chckver didn't pass , or all of the five content didn't pass?
image
Thank you!

**Pull request closed without merging**
