### PR TITLE
Add putty-cac

### PR DESCRIPTION
**Pull request by Dreista**
Add PuTTY CAC with CAPI and PKCS support.

### CODE REVIEW

**Comment by rashil2000** [comment]
Use the tag name instead of `master` in the URLs, otherwise people won't be able to download a previous version.

**Comment by Dreista** [comment]
Nice catch. Fixed!

**Comment by niheaven** [comment]
Please move this PR to https://github.com/ScoopInstaller/Versions

**Comment by Dreista** [comment]
https://github.com/ScoopInstaller/Versions/pull/303

**Pull request closed without merging**
