### PR TITLE
scoop-completion: Add version 0.2.3

### PR DESCRIPTION
**Pull request by alexchapar**
This can be use to enable scoop auto-completion command for PowerShell

### CODE REVIEW

**Comment by alexchapar** [comment]
Hi @Ash258, can you give me some pointers about what I should review ?

**Review by issaclin32 — APPROVED** [review]

**Comment by rashil2000** [comment]
I feel this should be a part of Scoop itself, like we can put this in the `supporting/` folder

**Comment by issaclin32** [comment]
> I feel this should be a part of Scoop itself, like we can put this in the `supporting/` folder

I agree. But we can keep this as a seperate app as a test bed, before eventually implemented in *Scoop*.
(such is the case of `boost`/`Intel tbb`, and c++ standards)

Also, reviewing/merging of *Scoop* core is somewhat pretty slow. Because some members are too busy, and the *Scoop* core really needs some testing before putting it online. That is why I am trying to put something into `UpdateTracker` before integrating into *Scoop*.

**Comment by rashil2000** [comment]
Sure, seems good to me.

Btw scoop-completion hasn't been in active development, but I've been using it for more than a year without any issues.

**Pull request merged**
