### PR TITLE
avisynth: Add version 2.6.1

### LINKED ISSUE #10717: [Request]: AviSynth
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

avisynth

### Description

Non-linear script language for audio/video processing.

### Homepage

http://avisynth.nl/index.php/Main_Page

### Download Link(s)

https://sourceforge.net/projects/avisynth2/files/AviSynth%202.5/

### Some Indication of Popularity/Repute

Software is well-known among TV industry/AV community. It has its own Wikipedia page:
https://en.wikipedia.org/wiki/AviSynth
It has tons of plugins:
https://forum.doom9.org/showthread.php?p=566904#post566904

### PR DESCRIPTION
**Pull request by FlawlessCasual17**
Closes #10717

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by jasongodev — COMMENTED** [review]
Should we do one of the following? Either:

- We place this under the Versions bucket as 2.6.1, then let the current avisynth 3.x to live here in the Extras bucket -OR-
- We name this old version as is 'avisynth', while the new version must have a new manifest using 'avisynthplus' as the name?

**Comment by Zliced13** [comment]
> And, @Zliced13, create separate reg files?

Why would I create separate .reg files when the manifest I made literally does it for you?

**Comment by Zliced13** [comment]
@jasongodev I already have this fixed, see

https://github.com/ScoopInstaller/Extras/pull/10771

**Comment by niheaven** [comment]
So the registry is required for avisynth? If it is, leave it as is.

**Pull request closed without merging**
