### PR TITLE
everything-toolbar: Add version 0.7.4

### LINKED ISSUE #8958: [Request] EverythingToolbar
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [x] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [x] the latest stable version of the program

### Information

**Name:** [name of new package]
EveryToolbar
**Description:** [clear and concise details of what it is]
Everything integration for the Windows taskbar.
**Homepage:** [a URL/link]
https://github.com/stnkl/EverythingToolbar
**Download link(s):** [URL(s)/link(s)]
https://github.com/stnkl/EverythingToolbar/releases/download/0.7.4/EverythingToolbar-0.7.4.msi
**Some indication of popularity/repute:** [GitHub stars/software reviews etc.]
https://github.com/stnkl/EverythingToolbar/stargazers

### PR DESCRIPTION
**Pull request by Zliced13**
Closes #8958
Relates to https://github.com/ScoopInstaller/Nonportable/issues/88

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Zliced13** [comment]
Can anyone test if this works properly? It's in my personal bucket:
```
scoop bucket add MyScoop 'https://github.com/Zliced13/MyScoop'
```
```
scoop install everything-toolbar
```

**Comment by Zliced13** [comment]
It worked for me, did it work for everyone else?

**Comment by Zliced13** [comment]
@yenfeng-shetiko and @ppvnf Could you please test this for me to see if it works correctly for you
```pwsh
scoop bucket add MyScoop 'https://github.com/Zliced13/MyScoop'
```
```
scoop install everything-toolbar
```

**Comment by ppvnf** [comment]
uninstall fails because explorer is not killed

```
C:\Users\Pedro# scoop uninstall everything-toolbar
ERROR 'everything-toolbar' isn't installed correctly.
Uninstalling 'everything-toolbar' (1.0.5).
Running pre_uninstall script...
Exception calling "Create" with "1" argument(s): "At line:3 char:43
+ taskkill /F /IM 'explorer.exe' | Out-Null && Start-Process 'explorer. ...
+                                           ~~
The token '&&' is not a valid statement separator in this version."
At C:\Users\Pedro\scoop\apps\scoop\current\lib\install.ps1:1037 char:9
+         Invoke-Command ([scriptblock]::Create($script -join "`r`n"))
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ParseException

Removing shortcut ~\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps\EverythingToolbar Launcher.lnk
ERROR Couldn't remove '~\scoop\apps\everything-toolbar\1.0.5'; it may be in use.
```

**Comment by Zliced13** [comment]
@ppvnf Try it again I fixed it.

**Comment by ppvnf** [comment]
it is working now!

**Comment by yenfeng-shetiko** [comment]
+1

**Comment by HUMORCE** [comment]
If the program must elevate permissions for installation, I prefer https://github.com/ScoopInstaller/Nonportable/pull/169

**Pull request closed without merging**
