### PR TITLE
sourcegit: Add version 8.21

### LINKED ISSUE #13534: [Request]: SourceGit
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

SourceGit

### Description

Opensource GUI client for git users.

### Homepage

https://github.com/sourcegit-scm/sourcegit

### Download Link(s)

https://github.com/sourcegit-scm/sourcegit/releases/download/v8.19/sourcegit_8.19.win-arm64.zip
https://github.com/sourcegit-scm/sourcegit/releases/download/v8.19/sourcegit_8.19.win-x64.zip

### Some Indication of Popularity/Repute

* Opensource and free
* Supports most git repository operations
* Fast
* Stars Total Downloads

### PR DESCRIPTION
**Pull request by love-linger**
Add sourcegit - Opensource GUI client for git users.

Closes #13534 

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aliesbelik** [comment]
Please fix check errors and add arm64 version as well.

**Comment by love-linger** [comment]
> Please fix check errors and add arm64 version as well.

I've pushed a commit to fix check errors and the arm64 package has been added too.

**Pull request merged**
