### PR TITLE
QQNT: Add version 9.9.7.21484

### PR DESCRIPTION
**Pull request by swhoro**
Relates to #12803

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by b4imetu** [comment]
Relates #11329 #11546 #11554 #12803
As for the naming, I vote for `qq-nt`

**Comment by aliesbelik** [comment]
Please:
- update to the latest version;
- add `32bit`/`arm64` options;
- rename to lowercase.

Looks like [this variant](https://github.com/chawyehsu/dorado/blob/master/bucket/qqnt.json) may be used for reference.

**Comment by swhoro** [comment]
> Please:
> 
> * update to the latest version;
> * add `32bit`/`arm64` options;
> * rename to lowercase.
> 
> Looks like [this variant](https://github.com/chawyehsu/dorado/blob/master/bucket/qqnt.json) may be used for reference.

Consider https://github.com/ScoopInstaller/Extras/pull/14406 is much better than this one, maybe I can close this PR.

**Pull request closed without merging**
