### PR TITLE
scoop-completion: add auto-import scripts

### PR DESCRIPTION
**Pull request by AkariiinMKII**
- Add a function module to modify PS profile
- Auto-import scoop-completion module to PS profile 
- Remove residual folder

Referenced from dorado bucket. I'm not familiar with function modules for PowerShell, edits from old hands would be appreciated. : )

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by issaclin32** [comment]
In official buckets, we tend to leave this **as an option**. Some users may not want `scoop-completion` to be automatically loaded, because they have other modules that may conflict with it.

I would suggest adding `$dir\add-to-profile.ps1`, and `$dir\remove-from-profile.ps1`,
and use something like:
```
"notes": "Run \"$dir\\add-to-profile.ps1\" to import scoop-completion automatically in Powershell",
...
...
...
"pre_uninstall": "&\"$dir\\remove-from-profile.ps1\"",
```

**Comment by AkariiinMKII** [comment]
> In official buckets, we tend to leave this **as an option**. Some users may not want `scoop-completion` to be automatically loaded, because they have other modules that may conflict with it.
> 
> I would suggest adding `scripts\scoop-completion\add-to-profile.ps1` and `scripts\scoop-completion\remove-from-profile.ps1`,
> and use something like:
> ```
> "notes": "Run \"$dir\\add-to-profile.ps1\" to import scoop-completion automatically in Powershell",
> ...
> ...
> "pre_install": [
>     "'add-to-profile.ps1', 'remove-from-profile.ps1' | ForEach-Object {",
>     "  if (Test-Path \"$bucketsdir\\extras\\scripts\\scoop-completion\\$_\") {",
>     "      Copy-Item \"$bucketsdir\\extras\\scripts\\scoop-completion\\$_\" \"$dir\\\"",
>     "  }",
>     "}",
> ]
> ...
> ...
> "pre_uninstall": "&\"$dir\\remove-from-profile.ps1\"",
> ```

In this situation, I recommend running both add and remove script manually, otherwise the add-to-profile script should run each time the module is updated.
As for the function module, it should be compatible with the whole bucket, how about keeping it for common usage?

**Comment by issaclin32** [comment]
Oh. I forgot to add this in `pre_uninstall`.
```
"pre_uninstall": "if ($cmd -eq 'uninstall') { &\"$dir\\remove-from-profile.ps1\" }"
```
I this way, the user will not need to run *add-to-profile script* during updates.

**Comment by AkariiinMKII** [comment]
> Oh. I forgot to add this in `pre_uninstall`.
> ```
> "pre_uninstall": "if ($cmd -eq 'uninstall') { &\"$dir\\remove-from-profile.ps1\" }"
> ```
> I this way, the user will not need to run *add-to-profile script* during updates.

Great 👍 I'll try this way

**Comment by issaclin32** [comment]
> As for the function module, it should be compatible with the whole bucket, how about keeping it for common usage?

I am fine with keeping it for common usage.

**Comment by issaclin32** [comment]
I think we should copy `ModifyPSProfile.psm1` to **$dir** as well.
If there is some update in `ModifyPSProfile.psm1`, this can avoid potential problems in old installations.

**Comment by AkariiinMKII** [comment]
> I think we should copy `ModifyPSProfile.psm1` to **$dir** as well.
> If there is some update in `ModifyPSProfile.psm1`, this can avoid potential problems in old installations.

Placing the module file in scripts directory makes it able to receive hot fix by updating bucket, I think it might be better.

**Comment by issaclin32** [comment]
> Placing the module file in scripts directory makes it able to receive hot fix by updating bucket, I think it might be better.

Okay. Let's leave it this way.

**Review by issaclin32 — APPROVED** [review]

**Pull request merged**
