### PR TITLE
v2rayn: *Major* Update to 6.21

### PR DESCRIPTION
**Pull request by b4imetu**
Closes #XXXX

Relates to #XXXX

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by b4imetu** [comment]
SEE
https://github.com/ScoopInstaller/Versions/pull/907
https://github.com/ScoopInstaller/Versions/commit/bf961e23365072071fee37bf1c18a6af85ef1d3e

**Review by StarsbySea — CHANGES_REQUESTED** [review]
download URL need fix.
图片

**Comment by b4imetu** [comment]
/verify
The author deleted the 7z package…

**Comment by b4imetu** [comment]
/verify
The author deleted the 7z package…

**Review by StarsbySea — APPROVED** [review]

**Pull request merged**
