### PR TITLE
universal-android-debloater: Add version 0.5.1

### LINKED ISSUE #11256: [Request]: universal-android-debloater
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

universal-android-debloater

### Description

A GUI to debloat non-rooted android devices using ADB

### Homepage

https://github.com/0x192/universal-android-debloater

### Download Link(s)

https://github.com/0x192/universal-android-debloater/releases

### Some Indication of Popularity/Repute

9.7k stars, 590 forks

### PR DESCRIPTION
**Pull request by leumasme**
Closes #11256 

- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by leumasme** [comment]
Error log from failed checks:
```
INFO: Checkver

Log of Output:

    universal-android-debloater:  
    The remote server returned an error: (404) Not Found. 
    URL https://api.github.com/repos/0x192/universal-android-debloater/releases/latest is not valid

INFO: Checkver done

INFO: Autoupdate

INFO: Autoupdate done
```
running checkver locally with `...\apps\scoop\current\bin\checkver.ps1 -App universal-android-debloater -Dir .` works fine, so I'm not sure how to reproduce this.  
Maybe it is because the releases on github are marked as prerelease?  
Help wanted.

**Comment by HUMORCE** [comment]
> Maybe it is because the releases on github are marked as prerelease?

Yes

**Review by HUMORCE — APPROVED** [review]

**Comment by leumasme** [comment]
@HUMORCE I don't believe this actually works. You changed the downloaded file name to uad.exe, but didn't change the shortcut file name.
```
S:\
❯ scoop i universal-android-debloater
Installing 'universal-android-debloater' (0.5.1) [64bit] from extras bucket
uad_gui-windows.exe (7,3 MB) [=========================================================================================================================================================================] 100%
Checking hash of uad_gui-windows.exe ... ok.
Linking S:\Apps\Scoop\apps\universal-android-debloater\current => S:\Apps\Scoop\apps\universal-android-debloater\0.5.1
Creating shortcut for Universal Android Debloater (uad_gui-windows.exe) failed: Couldn't find S:\Apps\Scoop\apps\universal-android-debloater\current\uad_gui-windows.exe
'universal-android-debloater' (0.5.1) was installed successfully!
```
so creating the shortcut fails

**Comment by HUMORCE** [comment]
😦 I will fixes it when home

**Comment by HUMORCE** [comment]
@leumasme Done. https://github.com/ScoopInstaller/Extras/commit/f7f7a635e3366ce6049192712847c4286b94fc16

**Pull request merged**
