### PR TITLE
netbeans: Update to version 12.6

### PR DESCRIPTION
**Pull request by agroba**
- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by niheaven** [comment]
- What's the app name?
- Don't merge `master` to `master`, create a new branch
- Fix `checkver` section to `"regex": "Apache NetBeans ([\\d.]+)"`
- Run `.\bin\checkver.ps1 netbeans -f` to update manifest
- Locally install the app to test the manifest
- Don't use raw PR template as your PR message
- Do you REALLY READ [Contributing Cuide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md)?

**Comment by amreus** [comment]
The app is netbeans.

@agroba  It looks like the download page may have changed - a better fix would be to fix the `autoupdate` `url` to point to the correct download page.

You should be able to use:

`https://dlcdn.apache.org/netbeans/netbeans/$version/netbeans-$version-bin.zip`

**Comment by amreus** [comment]
Also it looks like `checkver.regex` needs updated.

**Review by niheaven — APPROVED** [review]

**Pull request merged**
