### PR TITLE
horcrux: Add version 0.2

### LINKED ISSUE #4910: [Request] Add horcrux
https://github.com/jesseduffield/horcrux/releases/
Horcrux is a nice tool to encrypt files that you might lose

### PR DESCRIPTION
**Pull request by shelmor**
https://github.com/jesseduffield/horcrux

- Closes #4910

### CODE REVIEW

**Review by tech189 — APPROVED** [review]
Looks good to me!

**Comment by rashil2000** [comment]
Is this a commandline application? If yes, please shift this PR to Main bucket.

**Comment by shelmor** [comment]
> Is this a commandline application? If yes, please shift this PR to Main bucket.

It is, but I don't think it meets the criteria: 

> a reasonably well-known and widely used developer tool

**Review by rashil2000 — APPROVED** [review]

**Review by issaclin32 — APPROVED** [review]

**Pull request merged**
