### PR TITLE
Notepad3: Update to 5.21.1129.1 & add autoupdate

### LINKED ISSUE #6338: [Request] Update notepad3
Best Notepad replacement there is: https://www.rizonesoft.com/downloads/notepad3/

Current scoop-extras version:  Version: 5.20.722.1
Current version: 5.21.227.1

### PR DESCRIPTION
**Pull request by hu3rror**
Closes #6338

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
Separate PR for each application please

**Comment by hu3rror** [comment]
> Separate PR for each application please

sry 👌

**Pull request merged**
