### PR TITLE
wechat: Update Version 3.9.2.23

### PR DESCRIPTION
**Pull request by b4imetu**
Closes #XXXX

Relates to #XXXX

- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by StarsbySea — APPROVED** [review]
LGTM

**Comment by b4imetu** [comment]
@StarsbySea Thank you for your review
I think you could just Merge this simple but important bug fix

**Comment by StarsbySea** [comment]
Thanks for the feedback, but I don't have write access to this repository. I can only be considered a community level reviewer.

**Comment by b4imetu** [comment]
> Thanks for the feedback, but I don't have write access to this repository. I can only be considered a community level reviewer.
Oh, I get it. I didn't know about that.
But I have a feeling that Scoop's maintainers are not very active these days ^^

**Pull request merged**
