### PR TITLE
beeper: add version 3.51.7

### LINKED ISSUE #7115: [Request] Add beeper
PackageIdentifier: beeper
PackageVersion: 2.1.6
PackageLocale: en-US
Publisher: beeper
PackageName: beeper
License: open source
ShortDescription: messenger wrapper that integrates multiple services
Installers:

Architecture: x64
InstallerType: exe
InstallerUrl: https://download.beeper.com/windows/nsis/x64
ManifestType: singleton
ManifestVersion: 1.0.0

### PR DESCRIPTION
**Pull request by FlawlessCasual17**
Closes #7115

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sitiom** [comment]
- Continued in #17462

**Comment by kris3713** [comment]
Please do not notify me about this if it were to get merged. I have moved away from Windows to Linux (Ultramarine Linux). Good luck with the PR though.

**Pull request closed without merging**
