### PR TITLE
tb-vol-scroll: Add version 4.1.1

### PR DESCRIPTION
**Pull request by KaranKad**
Added tb-vol-scroll application which allows to control volume by scrolling in taskbar area

Closes #XXXX

Relates to #XXXX

- [ ] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
Persist?

**Comment by KaranKad** [comment]
It doesn't create any portable config file

**Comment by rashil2000** [comment]
It does have settings, so it might be storing them somewhere, right

**Comment by KaranKad** [comment]
I think it stores settings it in registry.

**Comment by KaranKad** [comment]
Oh wait found it, it stores settings in `AppData\Local\Dirk_Vingerhoeds\`

**Pull request merged**
