### PR TITLE
ruffle: Add version 2022-09-27

### LINKED ISSUE #9335: [Request] Add Ruffle
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [x] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [x] the latest stable version of the program

### Information

**Name:** ruffle

**Description:** A Flash Player emulator built in the Rust programming language.

**Homepage:** https://ruffle.rs/

**Download link(s):** https://github.com/ruffle-rs/ruffle/releases

**Some indication of popularity/repute:** 10.7k stars, 508 forks, 145 watches on GitHub

### PR DESCRIPTION
**Pull request by samiksome92**
Closes #9335

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by samiksome92** [comment]
I don't understand why checkver and autoupdate fails. Does version have to be in x.y.z format? Currently it is x-y-z

**Comment by KrisSchneider** [comment]
No, the version can be `x-y-z` format, it doesn't have to be in `x.y.z` all the time. That being said, try this URL for your checkver instead of the one you are currently using: https://github.com/ruffle-rs/ruffle/releases

**Comment by KrisSchneider** [comment]
Also, use try using a different regex. Here is a guide on the regex characters, and find out which ones you need to use: https://wikiless.org/wiki/Regular_expression?lang=en#Character_classes

If that does not work, you use a regex generator like this website, 
https://regex-generator.olafneumann.org/

**Comment by samiksome92** [comment]
Fixed url and regex.

**Comment by brian6932** [comment]
https://github.com/ScoopInstaller/Versions/blob/master/bucket/ruffle-nightly.json This kinda does already exist in versions

**Comment by samiksome92** [comment]
@brian6932 Thanks. I was not aware of the Versions bucket. In that case I will close this.

**Pull request closed without merging**
