### PR TITLE
authme: Add version 4.0.3

### LINKED ISSUE #9253: [Request] authme
Package Request Information
Name: Authme

Description: an authenticator app

Homepage: https://authme.levminer.com/#downloads or https://github.com/Levminer/authme

Download link(s): https://github.com/Levminer/authme/releases/download/3.3.4/authme-3.3.4-windows-x64-installer.exe

PS: Github 70 stars

### PR DESCRIPTION
**Pull request by Zliced13**
Closes #9253

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by rasa — CHANGES_REQUESTED** [review]
It appears to be a 64bit only binary, so we'll need to add an architecture tag

**Review by rasa — CHANGES_REQUESTED** [review]
I think it's needed in the autoupdate section as well, but I could be wrong.

**Comment by KrisSchneider** [comment]
@rasa is this good now?

**Comment by ViCrack** [comment]
this app doesn't quite meet the requirements for an app to be added [(100 stars, 50 forks)](https://github.com/ScoopInstaller/Extras/blob/master/.github/ISSUE_TEMPLATE/Package_request.md)

**Comment by KrisSchneider** [comment]
Should I close this pull request?

**Comment by KrisSchneider** [comment]
> this app doesn't quite meet the requirements for an app to be added [(100 stars, 50 forks)](https://github.com/ScoopInstaller/Extras/blob/master/.github/ISSUE_TEMPLATE/Package_request.md)

Yes I know. However, there are alot of people like the requester who love using this app for 2FA.

**Comment by Zliced13** [comment]
Should I close this PR, since the application does not meet extras bucket requirements?

**Comment by Zliced13** [comment]
@rasa should I close this PR?

**Comment by niheaven** [comment]
No, keep it here, and we'll merge it when it becomes popular.

**Comment by Zliced13** [comment]
Hey it's at 100 stars now.

**Comment by niheaven** [comment]
Ready to merge?

**Comment by Zliced13** [comment]
Sure, that manifest is ready to go.

**Review by niheaven — APPROVED** [review]

**Pull request merged**
