### PR TITLE
kopiaui: Fix checkver, update `hash` and `url`, remove `pre_install`

### PR DESCRIPTION
**Pull request by Zliced13**
Relates to https://github.com/ScoopInstaller/Extras/actions/runs/4682555879/jobs/8296555601#step:3:469

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by HUMORCE — APPROVED** [review]

**Comment by Zliced13** [comment]
@HUMORCE could you also approve https://github.com/ScoopInstaller/Main/pull/4662?

**Comment by HUMORCE** [comment]
> could you also approve ScoopInstaller/Main/4662?

Sorry, there is no reason for main bucket and me to update a manifest to a candidate version.

In fact, I mistakenly thought of `kopiaui` as a third-party GUI wrapper, may be rolled back later.

**Comment by Zliced13** [comment]
> Sorry, there is no reason 
> In fact, I mistakenly thought of `kopiaui` as a third-party GUI wrapper, may be rolled back later. I will refer to what other maintainers have to comment about main/4662.

Why would you roll back a change that would help the manifest? Are you out of your mind?

**Comment by HUMORCE** [comment]
> Why would you roll back a change that would help the manifest? 

Because it was due to my mistake when reviewing PR.

> Are you out of your mind?

No, but unstable programs make people lose their minds. just like Windows 11 always has some problems, although they are minor.

---

For me, `main/kopia`, `extras/kopiaui` is still in an early version so I can accept the candidate version, but im just me.

**Pull request merged**
