### PR TITLE
sfsu: Add version 1.1.0

### PR DESCRIPTION
**Pull request by jewlexx**
- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jewlexx** [comment]
/verify Old hash files were in Powershell format not raw hashes

**Comment by niheaven** [comment]
Just remove `sfss.json`? This seems not a `deprecated`.

**Comment by niheaven** [comment]
The `sfss` and `sfsl` always give errors.

image

**Comment by jewlexx** [comment]
@niheaven do you have scoop installed in it's default location? they don't support non-default scoop locations yet.

**Comment by niheaven** [comment]
Hmm, thanks, and non-default location should be taken into consideration IMO.

**Comment by jewlexx** [comment]
@niheaven Yeah I plan to add support in the near future, but in the meantime I will add better error message than that at least.

**Comment by jewlexx** [comment]
> Just remove `sfss.json`? This seems not a `deprecated`.

Removed it altogether now

**Review by niheaven — APPROVED** [review]

**Pull request merged**
