### PR TITLE
KopiaUI: Add version 0.10.1

### PR DESCRIPTION
**Pull request by hu3rror**
- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

Data is stored in `%appdata%/kopia-ui`

### CODE REVIEW

**Review by niheaven — APPROVED** [review]
You may also add kopia in `main` bucket.

**Comment by rashil2000** [comment]
If you plan to add kopia to Main bucket remove the `"bin": "resources\\server\\kopia.exe",` line, otherwise it will conflict.

**Comment by niheaven** [comment]
> If you plan to add kopia to Main bucket remove the `"bin": "resources\\server\\kopia.exe",` line, otherwise it will conflict.

Keep it here if someone wants to install only Kopia UI, IMO. shim overwriting will solve the conflict.

**Comment by rashil2000** [comment]
But why would you need the shim to the server in a GUI app?

**Comment by niheaven** [comment]
It is the client CLI, just packed in the UI. The hashsum is different from the one from cli package, though.

**Comment by hu3rror** [comment]
I just added the CLI version of Kopia in Main.
And do I need to modify the manifest for kopiaUI？

**Pull request merged**
