### PR TITLE
imageglass@9.0.7.1125: Fix manifest for v9

### LINKED ISSUE #12313: imageglass@9.0.7.1125: download via aria2 failed
ERROR Download failed! (Error 3) Resource was not found
ERROR https://github.com/d2phap/ImageGlass/releases/download/9.0.7.1125/ImageGlass_Kobe_9.0.7.1125_x64.zip
    referer=https://github.com/d2phap/ImageGlass/releases/download/9.0.7.1125/
    dir=C:\Users\home\scoop\cache
    out=imageglass#9.0.7.1125#https_github.com_d2phap_ImageGlass_releases_download_9.0.7.1125_ImageGlass_Kobe_9.0.7.1125_x64.zip

ERROR & 'C:\Users\home\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\home\scoop\cache\imageglass.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.4 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=9820 --continue --summary-interval=0 --auto-save-interval=1

### PR DESCRIPTION
**Pull request by ZzzZeta**
https://imageglass.org/news/introducing-the-new-imageglass-version-9-88

Breaking changes

- User config files are now in the JSON format: igconfig.json. ImageGlass 9 cannot import settings from version 8.
- Similarly, theme and language pack also updated to use JSON format. You can download theme packs for version 9 at Download / Theme packs.
- For power users:
  - Version 9 uses Per-user setting model which is different from Per-machine setting of version 8:
    - The app settings are now saved in the %LocalAppData% folder. Refer to Docs / App configuration for more information.
    - The app registry uses HKEY_CURRENT_USER for file type associations and app protocol.
  - igtasks.exe has been removed.
  - All commands in igcmd.exe have been reworked. Visit Docs / Command line utilities for the updated information.
  - To skip the "ImageGlass Quick Setup" dialog, set QuickSetupVersion value to any number greater than 9 in the igconfig.json file.

---

Closes #12313

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by nanangp** [comment]
Should we set autoupdate to false in the new `config.json` during pre_install (like we used to do with the xml)?

**Comment by ZzzZeta** [comment]
> Should we set autoupdate to false in the new `config.json` during pre_install (like we used to do with the xml)?

Yes, it would be a good idea to maintain the original behavior.

**Comment by mcshosho** [comment]
After fresh install of version 9 using this manifest, ImageGlass is not starting
image
Could not load user settings
The user configuration file:
appears to be corrupted or contains an invalid value. Please review the details below to address the issue before proceeding
`System.NullReferenceException: Object reference not set to an instance of an object.
   at ImageGlass.Settings.Config.LoadThemePack(Boolean darkMode, Boolean useFallBackTheme, Boolean throwIfThemeInvalid, Boolean forceUpdateBackground) in D:\_GITHUB\@d2phap\ImageGlass\Source\Components\ImageGlass.Settings\Config.cs:line 1536
   at ImageGlass.Settings.Config.Load() in D:\_GITHUB\@d2phap\ImageGlass\Source\Components\ImageGlass.Settings\Config.cs:line 969
   at ImageGlass.Program.Main() in D:\_GITHUB\@d2phap\ImageGlass\Source\ImageGlass\Program.cs:line 63
   `

**Comment by ZzzZeta** [comment]
> After fresh install of version 9 using this manifest, ImageGlass is not starting image Could not load user settings The user configuration file: appears to be corrupted or contains an invalid value. Please review the details below to address the issue before proceeding `System.NullReferenceException: Object reference not set to an instance of an object. at ImageGlass.Settings.Config.LoadThemePack(Boolean darkMode, Boolean useFallBackTheme, Boolean throwIfThemeInvalid, Boolean forceUpdateBackground) in D:\_GITHUB\@d2phap\ImageGlass\Source\Components\ImageGlass.Settings\Config.cs:line 1536 at ImageGlass.Settings.Config.Load() in D:\_GITHUB\@d2phap\ImageGlass\Source\Components\ImageGlass.Settings\Config.cs:line 969 at ImageGlass.Program.Main() in D:\_GITHUB\@d2phap\ImageGlass\Source\ImageGlass\Program.cs:line 63 `

Could you try `scoop uninstall -p imageglass`? Themes are incompatible.

**Review by HUMORCE — APPROVED** [review]

**Pull request merged**
