### PR TITLE
Thorium: add version 117.0.5938.157

### LINKED ISSUE #12072: [Request]: Thorium
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

Thorium

### Description

Faster fork for chromium

### Homepage

https://thorium.rocks/

### Download Link(s)

https://github.com/Alex313031/Thorium-Win/releases/download/M117.0.5938.157/Thorium_117.0.5938.157.zip

### Some Indication of Popularity/Repute

Pretty known in the FOSS community, 2300 stars on GH

### PR DESCRIPTION
**Pull request by CryoRenegade**
Closes #12072

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by thegamerx1** [comment]
Shouldn't another package be added for avx2 version?

**Comment by CryoRenegade** [comment]
It's already done in the Versions bucket. https://github.com/ScoopInstaller/Versions/pull/1438#issuecomment-1783386643

**Pull request merged**
