### PR TITLE
fix(checkver): use `scoop prefix` to correctly find scoop's path

### PR DESCRIPTION
**Pull request by niheaven**

### CODE REVIEW

**Review by pratikpc — APPROVED** [review]

**Comment by niheaven** [comment]
@pratikpc And there're same fix in `Main` and `Versions`.

Ref: https://github.com/ScoopInstaller/Main/pull/2878, https://github.com/ScoopInstaller/Versions/pull/304

**Comment by pratikpc** [comment]
@niheaven should it be resolve-path (scoop prefix scoop) instead?

The current command gives $env:SCOOP/apps for me

**Comment by niheaven** [comment]
Yes, it is :cry:

I'll make a new PR.

**Comment by pratikpc** [comment]
@niheaven reverted the commit

Sorry

My bad

**Comment by niheaven** [comment]
#7225

**Pull request merged**
