### PR TITLE
86Box: Add version 3.11 (+ roms 3.11 + manager 1.7.4)

### PR DESCRIPTION
**Pull request by kriswilk**
This PR adds the 86Box suite of early x86 system emulation tools. Specifically, it adds three manifests:

- `86box.json` - the 86Box emulator
- `86box-roms.json` - the official collection of required roms
- `86box-manager.json` - the GUI front-end for 86Box

All have been tested locally, including checkver/autoupdate. However, I welcome anyone to double-check.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by kriswilk** [comment]
It should be noted that this code is based on manifests from a scoop bucket by @amorphobia, found [here](https://github.com/amorphobia/siku). Thank you for those!

**Review by HUMORCE — CHANGES_REQUESTED** [review]
Wrong suggestion items.

**Comment by kriswilk** [comment]
> Wrong suggestion items.

Fixed these artifacts from my personal scoop repo. They all now point to the correct manifests.

**Review by HUMORCE — APPROVED** [review]

**Comment by anderlli0053** [comment]
Thanks!

**Pull request merged**
