### PR TITLE
rvgl-launcher: Add version 0.1.22.314a1

### LINKED ISSUE #10298: [Request]: RVGL launcher
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

RVGL Launcher

### Description

RVGL Launcher is a cross-platform installer, launcher and package manager for RVGL. It's currently available on Windows and GNU/Linux for both 32-bit and 64-bit architectures.  Install game and content packs and keep them up-to-date. View list of online events and join them directly. Enable or disable content packs on the fly. Add your own content and repositories.

### Homepage

https://www.revoltworld.net/dl/rvgllauncher/

### Download Link(s)

https://www.revoltworld.net/dl/rvgllauncher/

### Some Indication of Popularity/Repute

It is very popular amongst RVGL players (Re-Volt GL game implementation), the game itself is available to install through Scoop too - `scoop install games/rvgl`

### PR DESCRIPTION
**Pull request by Zliced13**
Closes #10298

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by HUMORCE** [comment]
Please add this manifest to the games bucket instead of extras bucket

**Comment by anderlli0053** [comment]
So...what is going on with this??  I cannot find this in any bucket, let alone in 'games' bucket

**Comment by HUMORCE** [comment]
> So...what is going on with this?? I cannot find this in any bucket, let alone in 'games' bucket

This PR is closed. the contributor did not submit it to other buckets and get merged, you can copy the json file locally and install it.

```
❯ scoop help install
Usage: scoop install <app> [options]

e.g. The usual way to install an app (uses your local 'buckets'):
     scoop install git

To install a different version of the app
(note that this will auto-generate the manifest using current version):
     scoop install gh@2.7.0

To install an app from a manifest at a URL:
     scoop install https://raw.githubusercontent.com/ScoopInstaller/Main/master/bucket/runat.json

To install an app from a manifest on your computer
     scoop install \path\to\app.json
```

**Comment by Zliced13** [comment]
Sorry @anderlli0053, I almost forgot about this, let me fix it.

**Pull request closed without merging**
