### PR TITLE
compatibility-manager: Add version 1.1.2

### PR DESCRIPTION
**Pull request by RavenMacDaddy**
A Windows app for bulk editing compatibility settings.

- [ X ] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by RavenMacDaddy** [comment]
For some reason I'm unable to edit the file to attempt fixing reported failed checks.

**Comment by RavenMacDaddy** [comment]
image

Whitespace error, even though I did copy-paste from a similar manifest directly in GitHub.

**Comment by rashil2000** [comment]
Same as https://github.com/ScoopInstaller/Extras/pull/7590#issuecomment-1000692610

**Pull request merged**
