### PR TITLE
avidemux: add version 2.8.0

### LINKED ISSUE #3691: [Request] Add avidemux
http://fixounet.free.fr/avidemux/download.html
https://sourceforge.net/projects/avidemux/

### LINKED ISSUE #4775: [Request] Add avidemux
Can you please add avidemux?

It can be downloaded from [https://www.fosshub.com/Avidemux.html](https://www.fosshub.com/Avidemux.html).

The actual webpage for the project is [http://fixounet.free.fr/avidemux/download.html](http://fixounet.free.fr/avidemux/download.html), but there the download for windows points to an older version.

Thanks a lot.

### PR DESCRIPTION
**Pull request by tech189**
- Closes #3691 and closes #4775
- Uses GitHub releases for download instead of sourceforge/fosshub, but no hash unfortunately
- CLI added and shortcuts for main program and the Jobs runner

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
Has [this isssue](https://github.com/ScoopInstaller/Extras/issues/3691#issuecomment-601557735) been resolved now?

**Comment by tech189** [comment]
Yes, my manifest solves the issue by downloading a different release. 7-zip can't extract the VC++ release (e.g.  Avidemux_2.8.0.VC++.64bits.exe) but it can extract the win64 version.

**Comment by rashil2000** [comment]
I can't find any link to the GitHub repo on http://fixounet.free.fr/avidemux. Are the two related?

**Comment by tech189** [comment]
I think they are related, if you go to the [news page](http://fixounet.free.fr/avidemux/news.html), there is mention of [szlldm](https://github.com/szlldm) adding features and their GitHub page is linked - they are the second highest contributor to that repo. But yes it's not clearly marked as far as I can tell. I went for it as I've heard sourceforge downloads are hard to maintain and their website has different formatting for every [release](http://fixounet.free.fr/avidemux/download.html) (again hard to maintain) and also it's on HTTP so hashes potentially subject to MITM (I think). Then the fosshub page has downloads but I'm not sure who is building them or where they are coming from - plus the hashes are hard to extract.

**Comment by rashil2000** [comment]
Okay, makes sense to me.

**Pull request merged**
