### PR TITLE
chefdk: Remove autoupdate, update license

### PR DESCRIPTION
**Pull request by tech189**
- Relates to #8290
- See above for details - ChefDK has reached end of life and has been replaced by Chef Workstation
- This PR removes autoupdate because there will be no more versions
- License seems to have changed
- Adds note for users to install Extras/chef-workstation instead

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
Should we deprecate the manifest instead?

**Comment by rashil2000** [comment]
We could just add something like "Chef Workstation supercedes ChefDK" :)

**Comment by tech189** [comment]
Okay, I've moved it to the deprecated folder, will make another PR for the Chef Workstation description.

**Comment by rashil2000** [comment]
You can modify it here itself

**Comment by tech189** [comment]
I may need to open a new PR anyway, this branch is out of date and does not have `chef-workstation.json`

**Comment by rashil2000** [comment]
I've updated it

**Comment by tech189** [comment]
Oh perfect, thanks!

**Pull request merged**
