### PR TITLE
WinTADS: Add version 1.3.4

### PR DESCRIPTION
**Pull request by ctoth**
WinTADS is the standard way for playing TADS text adventure games on Windows.

### CODE REVIEW

**Review by Ash258 — CHANGES_REQUESTED** [review]
- The description does not desribe what the applicaiton it is
- No homepage
- Using powershell aliases in install blocks is not maintainable
- Where did you get the information about license?

**Comment by issaclin32** [comment]
I think this should be in [the Games bucket](https://github.com/Calinou/scoop-games).

**Comment by rashil2000** [comment]
It's a 20 year old release. I have doubts regarding this.

**Comment by rashil2000** [comment]
Please shift this PR to [Games bucket](https://github.com/Calinou/scoop-games).

**Pull request closed without merging**
