### PR TITLE
retdec: Add version 4.0

### PR DESCRIPTION
**Pull request by Dany-coder778**
Added retdec.json in the bucket.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by issaclin32** [comment]
Their repo has 6.7K stars, and it is a pure command-line tool.

I think this can be added to the [Main bucket](https://github.com/ScoopInstaller/Main).

**Comment by issaclin32** [comment]
Please put other apps in seperate PRs.

**Comment by Dany-coder778** [comment]
Excuse me, I'm new to github and i don't know how to use it well.
Earlier, when you asked me to move it to the main bucket I thought it was a comment for the other manteiners.
I've just put other apps in separate PR.

**Comment by Dany-coder778** [comment]
Do I need to open other PRs to put it in the main bucket and close these or can you do it?

**Comment by issaclin32** [comment]
> Do I need to open other PRs to put it in the main bucket and close these or can you do it?

You have to open another PR in the main bucket.
Issues can be transferred between repos, but PRs can not.

**Comment by Dany-coder778** [comment]
Opened https://github.com/ScoopInstaller/Main/pull/3912

**Pull request closed without merging**
