### PR TITLE
cursor: Add version 0.44.9

### LINKED ISSUE #14501: [Request]: Cursor
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

Cursor

### Description

The AI Code Editor

### Homepage

https://www.cursor.com/

### Download Link(s)

https://download.todesktop.com/230313mzl4w4u92/Cursor%20Setup%200.43.5%20-%20Build%20241127pdg4cnbu2-x64.exe

### Some Indication of Popularity/Repute

https://www.cursor.com/
https://github.com/getcursor/cursor/

### PR DESCRIPTION
**Pull request by Vixb1122**
Closes #14501

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aliesbelik** [comment]
I suppose using 3rd party resource to download binaries while official site provides installers is not a good idea for the official bucket.

**Comment by Vixb1122** [comment]
download url come from [winget-pkgs](https://github.com/microsoft/winget-pkgs/blob/1c597eb8e2c250b182d168880b1f02496224bfd8/manifests/a/Anysphere/Cursor/0.43.5/Anysphere.Cursor.installer.yaml#L58)
@aliesbelik

**Comment by aliesbelik** [comment]
> download url come from [winget-pkgs](https://github.com/microsoft/winget-pkgs/blob/1c597eb8e2c250b182d168880b1f02496224bfd8/manifests/a/Anysphere/Cursor/0.43.5/Anysphere.Cursor.installer.yaml#L58)

My fault, sorry.
First seen only links from [Downloads](https://www.cursor.com/downloads) section:
https://downloader.cursor.sh/windows/nsis/x64
https://downloader.cursor.sh/windows/nsis/arm64

Those used in PR come from main/[changelog](https://changelog.cursor.com/) sections.
A bit weird but ok: hashes are the same in both cases.
I guess, that's an argument, not "come from winget-pkgs".

**Comment by Vixb1122** [comment]
> [Your changes do not pass checks.](https://github.com/ScoopInstaller/GithubActions/wiki/Pull-Request-Checks)
> 
> ### cursor
> * [x]  Description
> * [x]  License
> * [x]  Hashes
> * [ ]  Checkver
> * [x]  Autoupdate
> * [x]  Autoupdate Hash Extraction

I do not understand, no any change for checkver. @chawyehsu

**Comment by chawyehsu** [comment]
> I do not understand, no any change for checkver. @chawyehsu

The bot requires the version to be the latest version when testing the checkver.

**Comment by Vixb1122** [comment]
> > I do not understand, no any change for checkver. @chawyehsu
> 
> The bot requires the version to be the latest version when testing the checkver.

Got it, thx!

**Review by chawyehsu — APPROVED** [review]

**Pull request merged**
