### PR TITLE
pure-data: Added version 0.52-1

### PR DESCRIPTION
**Pull request by pomberger**
- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
- The latest release seems to be **0.52-2** - https://puredata.info/downloads/pure-data/releases/0.52-2
- What are the commandline arguments for pd.exe?

**Comment by umlaeute** [comment]
that's definitely a typo on my side (being the one who created the entry on  https://puredata.info/downloads/pure-data/releases/)

the latest release of Pd is `0.52-1` as @pomberger wrote.

~~~sh
pd.com -help
usage: pd [-flags] [file]...

audio configuration flags:
-r <n>           -- specify sample rate
-audioindev ...  -- audio in devices; e.g., "1,3" for first and third
-audiooutdev ... -- audio out devices (same)
-audiodev ...    -- specify input and output together
-audioaddindev   -- add an audio input device by name
-audioaddoutdev  -- add an audio output device by name
-audioadddev     -- add an audio input and output device by name
-inchannels ...  -- audio input channels (by device, like "2" or "16,8")
-outchannels ... -- number of audio out channels (same)
-channels ...    -- specify both input and output channels
-audiobuf <n>    -- specify size of audio buffer in msec
-blocksize <n>   -- specify audio I/O block size in sample frames
-sleepgrain <n>  -- specify number of milliseconds to sleep when idle
-nodac           -- suppress audio output
-noadc           -- suppress audio input
-noaudio         -- suppress audio input and output (-nosound is synonym) 
-callback        -- use callbacks if possible
-nocallback      -- use polling-mode (true by default)
-listdev         -- list audio and MIDI devices
-asio            -- use ASIO audio driver (via Portaudio)
-pa              -- synonym for -asio
-mmio            -- use MMIO audio API (default for Windows)
      (default audio API for this platform:  MMIO)


MIDI configuration flags:
-midiindev ...   -- midi in device list; e.g., "1,3" for first and third
-midioutdev ...  -- midi out device list, same format
-mididev ...     -- specify -midioutdev and -midiindev together
-midiaddindev    -- add a MIDI input device by name
-midiaddoutdev   -- add a MIDI output device by name
-midiadddev      -- add a MIDI input and output device by name
-nomidiin        -- suppress MIDI input
-nomidiout       -- suppress MIDI output
-nomidi          -- suppress MIDI input and output

other flags:
-path <path>     -- add to file search path
-nostdpath       -- don't search standard ("extra") directory
-stdpath         -- search standard directory (true by default)
-helppath <path> -- add to help file search path
-open <file>     -- open file(s) on startup
-lib <file>      -- load object library(s) (omit file extensions)
-font-size <n>      -- specify default font size in points
-font-face <name>   -- specify default font
-font-weight <name> -- specify default font weight (normal or bold)
-verbose         -- extra printout on startup and when searching for files
-noverbose       -- no extra printout
-version         -- don't run Pd; just print out which version it is 
-d <n>           -- specify debug level for inspecting the GUI communication
-loadbang        -- do not suppress all loadbangs (true by default)
-noloadbang      -- suppress all loadbangs
-stderr          -- send printout to standard error instead of GUI
-nostderr        -- send printout to GUI (true by default)
-gui             -- start GUI (true by default)
-nogui           -- suppress starting the GUI
-guiport <n>     -- connect to pre-existing GUI over port <n>
-guicmd "cmd..." -- start alternative GUI program (e.g., remote via ssh)
-send "msg..."   -- send a message at startup, after patches are loaded
-prefs           -- load preferences on startup (true by default)
-noprefs         -- suppress loading preferences on startup
-prefsfile <file>  -- load preferences from a file
-rt or -realtime -- use real-time priority
-nrt             -- don't use real-time priority
-sleep           -- sleep when idle, don't spin (true by default)
-nosleep         -- spin, don't sleep (may lower latency on multi-CPUs)
-schedlib <file> -- plug in external scheduler (omit file extensions)
-extraflags <s>  -- string argument to send schedlib
-batch           -- run off-line as a batch process
-nobatch         -- run interactively (true by default)
-autopatch       -- enable auto-patching to new objects (true by default)
-noautopatch     -- defeat auto-patching
-compatibility <f> -- set back-compatibility to version <f>
~~~

**Comment by rashil2000** [comment]
Okay, thanks for the heads up

**Pull request merged**
