### PR TITLE
uget-portable:Add persistence

### PR DESCRIPTION
**Pull request by ef6**
`share\locale` for storing translated documents

### CODE REVIEW

**Comment by Ash258** [comment]
What do you mean with `translated documents`? I cannot find any reference to capability of translating downloaded documents or anything like thi

**Comment by linsui** [comment]
> The following downloads are for pre-compiled packages that you can use to install uGet. 7z Archive is the main file that includes the uGet application. Locale 7z is the archive that includes the Translations files, if your preferred language is something other than English, you’ll need to download the Locale file.

See https://ugetdm.com/downloads/windows/

**Comment by Ash258** [comment]
Would not make sense to rather download all locales and extract it?

**Comment by ef6** [comment]
Most people whose native language is not English need to extract translation files from the `LOCALE.7Z` to the `share\locale `

If we add it to the persistence, then when people upgrade the small version(look like 2.2.1->2.2.2), there is no need to add translation files.

**Comment by ef6** [comment]
Of course.I assume the translation files are unchanged when uget upgrade a small version.

**Comment by linsui** [comment]
After https://github.com/lukesampson/scoop/pull/3518 is merged we can update the LOCALE.7Z.

**Pull request merged**
