### PR TITLE
Add Jujutsu

### LINKED ISSUE #11878: [Request]: Jujutsu
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

JJ

### Description

A Git-compatible DVCS that is both simple and powerful

### Homepage

https://github.com/martinvonz/jj

### Download Link(s)

https://github.com/martinvonz/jj/releases

### Some Indication of Popularity/Repute

Jujutsu VCS, crafted by Martin von Zweigbergk, is steadily earning its place and reputation within the software development community. A standout affirmation of its growing popularity and reputation lies in its approach to tackling real-world challenges observed in Google's version control system, as well as the interesting developer experience it provides.

### PR DESCRIPTION
**Pull request by shikanime**
Closes #11878

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aliesbelik** [comment]
Duplicates #11679.

**Comment by HUMORCE** [comment]
https://github.com/ScoopInstaller/Main/pull/5327

**Pull request closed without merging**
