### PR TITLE
inkscape, ultravnc, xmind: Change checkver conflicted variable

### PR DESCRIPTION
**Pull request by LazyGeniusMan**
Closes https://github.com/ScoopInstaller/GithubActions/issues/3

Relates to #XXXX

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

Context:
> I think it's from `inkscape` checkver. it's using `$version` variable and the value is 1.1.1

Ok so this is the problem. changed it in dummy repo[^1], and then run the github action[^2], it's working[^3].

[^1]: https://github.com/LazyGeniusMan/Scoop-Test/commit/b249b7ba19186cf9da6a86beb0e79a3848fd54fa
[^2]: https://github.com/LazyGeniusMan/Scoop-Test/actions/runs/1645606185
[^3]: https://github.com/LazyGeniusMan/Scoop-Test/commits/master

### CODE REVIEW

**Comment by rashil2000** [comment]
`$scriptver` is a more explicit name, what do you think?

Also, can you make similar change for xmind.json and ultravnc.json? 

Also for vlc-nightly in Versions bucket.

**Comment by LazyGeniusMan** [comment]
> `$scriptver` is a more explicit name, what do you think?
> 
> Also, can you make similar change for xmind.json and ultravnc.json?
> 
> Also for vlc-nightly in Versions bucket.

sure, gimme sec

**Comment by tech189** [comment]
Oops sorry I wrote that script in the inkscape manifest! I should change it also in vlc-nightly and gimp-dev in Versions.

**Pull request merged**
