### PR TITLE
Eraser: Add version 6.2.0.2993

### LINKED ISSUE #10446: [Request]: Eraser
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

Eraser

### Description

Remove sensitive data from your hard drive by overwriting it several times with carefully selected patterns

### Homepage

https://eraser.heidi.ie/

### Download Link(s)

https://eraser.heidi.ie/download/

### Some Indication of Popularity/Repute

Latest version 6.2.0.2993 downloaded 455524 times.

### PR DESCRIPTION
**Pull request by ath0mas**
Closes #10446

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by HUMORCE — APPROVED** [review]

**Comment by ath0mas** [comment]
@HUMORCE latest changes seem to have broken install
```
Installing 'eraser' (6.2.0.2993) [64bit] from extras bucket
Loading Eraser%206.2.0.2993.exe from cache.
Checking hash of Eraser%206.2.0.2993.exe ... ok.
Extracting dl.7z ... done.
Running pre_install script...
ERROR Exit code was 1603!
Failed to extract files from C:\Users\me\scoop\apps\eraser\6.2.0.2993\_EXTRACTED\Eraser (x64).msi.
Log file:
  ~\scoop\apps\eraser\6.2.0.2993\_EXTRACTED\msi.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=eraser%406.2.0.2993%3a+decompress+error
```

and given `msi.log` file
```
The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2503. The arguments are: , , 
The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2502. The arguments are: , ,
```

**Comment by ath0mas** [comment]
or not, sorry (due to recently breaking my whole scoop install, and now "required" to use `scoop config MSIEXTRACT_USE_LESSMSI true` and lessmsi for msi installs to succeed ...)

**Pull request merged**
