### PR TITLE
Floorp: Add version 11.0.0

### PR DESCRIPTION
**Pull request by H-Tung**
Floorp is a derivative of Mozilla Firefox ESR which emphases on privacy and customizability. It gets 578 stars on [GitHub](https://github.com/floorp-Projects/floorp/) now. This manifest is referenced from the firefox manifest in Extra bucket.

- Floorp is a browser that uses Rapid Release, which updates once every four weeks based on Firefox ESR.
- In addition to customizing Firefox's regular themes, you can switch the browser interface from five designs.
- Floorp layout customization is unlimited. Move the position of the tab bar to the bottom of the window or hide the title bar. Your own Floorp.
- Sidebar that can be placed on both sides
  Are you satisfied with one sidebar? Want to open a website at the sidebar? Floorp has a built-in sidebar that can display web panels and browser management tools for comfortable browsing

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by HUMORCE** [comment]
https://floorp.app/download

It has portable version for windows.

**Comment by H-Tung** [comment]
> It has portable version for windows.

Thanks for reminding. There was no portable version at v10.x.x IIRC. I will update to portable version.

**Comment by quardbreak** [comment]
Hi! Are you still working on it?

**Comment by H-Tung** [comment]
> Hi! Are you still working on it?你好！你还在努力吗？

No, I switched to librewolf+[andreasgrafen/cascade](https://github.com/andreasgrafen/cascade) a few weeks ago.

**Pull request closed without merging**
