### PR TITLE
paint.net-plugin-boltbait: Add version 5.0

### PR DESCRIPTION
**Pull request by NotWearingPants**
Added a very popular paint.net plugin pack by BoltBait (https://boltbait.com/pdn).

The installer is a dotnet executable with the plugins being dll files in its resources.
I used powershell's `[System.Reflection.Assembly]::Load` to get the resource files, and copied the dll files into paint.net's plugin folder.

### CODE REVIEW

**Comment by NotWearingPants** [comment]
@Ash258 can you go over this please?

**Comment by Ash258** [comment]
No thank you.

I really do not like the installer, so someone else will handle this.

**Comment by NotWearingPants** [comment]
Who? I thought you were the only maintainer.
and when? It's been 45 days already :(

**Comment by issaclin32** [comment]
Superseded by #7646

**Pull request closed without merging**
