### PR TITLE
LunarVim@1.3.0: Update install.ps1 hash

### PR DESCRIPTION
**Pull request by toby7002**
LunarVim install.ps1 hash is not correct so I downloaded the `install.ps1` script and hash it manually to get a correct hash  

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aliesbelik** [comment]
Looks like hash is correct but for the version 1.3.0, and urls point to the files from master.
I guess this will cause the issue each time any of files will be updated.

**Comment by aliesbelik** [comment]
In addition to the previous ones.

Added `checkver`, `autoupdate` and versioned urls to the manifest.
Looks like the powershell scripts used in manifest are quite rarely changed but using their master versions along with calculated hashes will cause "hash check failed" issues like this one after each change in the files.

I'm not an active (neo|lunar)vim user so if you see better ways to resolve this let's discuss.

**Comment by toby7002** [comment]
All goods but should we added [git](https://cli.github.com/), [make](https://www.gnu.org/software/make/), [pip](https://pypi.org/project/pip/), [python](https://www.python.org/), [npm](https://npmjs.com/), [node](https://nodejs.org/), [cargo](https://www.rust-lang.org/tools/install) and [ripgrep](https://github.com/BurntSushi/ripgrep)? Because LunarVim requires them 🤔

**Comment by aliesbelik** [comment]
> All good but should we added [git](https://cli.github.com/), [make](https://www.gnu.org/software/make/), [pip](https://pypi.org/project/pip/), [python](https://www.python.org/), [npm](https://npmjs.com/), [node](https://nodejs.org/), [cargo](https://www.rust-lang.org/tools/install) and [ripgrep](https://github.com/BurntSushi/ripgrep)? Because LunarVim requires them 🤔

Oh, there are a lot of them.
I've added `neovim` only as a primer, suppose it could even go to [depends section](https://github.com/ScoopInstaller/Scoop/wiki/App-Manifests#optional-properties):

> depends:
>   Runtime dependencies for the app which will be installed automatically.

If all the other prerequisites aren't absolutely necessary for runtime they could be added to `suggest`:

> suggest:
>   Display a message suggesting optional apps that provide complementary features.

**Pull request closed without merging**
