### PR TITLE
pipp@2.5.9: Fix urls, disable updates

### PR DESCRIPTION
**Pull request by aliesbelik**
Attempt to fix unavailable `pipp` installations download:

- broken update from Excavator log:
> pipp: couldn't match 'Windows Installer \(v([\d.]+)\)' in https://sites.google.com/site/astropipp/downloads
- site and download locations unavailability reported by users: cgarry/ser-player#15, [link](https://www.cloudynights.com/topic/880084-pipp-download-location-seems-unavailable/), [link](https://www.reddit.com/r/AskAstrophotography/comments/14hg05c/the_link_to_download_pipp_isnt_working_anymore/).

Binaries are still available via [Wayback Machine archive](https://web.archive.org/web/20230604160403/https://sites.google.com/site/astropipp/downloads) ([x86](https://web.archive.org/web/20230604160535if_/https://3670d42b-a-62cb3a1a-s-sites.googlegroups.com/site/astropipp/downloads/pipp_install_x86_2.5.9.zip?attachauth=ANoY7crLNAqqt8W8_VKOuFNKAwb-dZnFKIibRiYMzgnIQrJfnuGy0lZdjsSLdjTOkXPpP2zNhoRHG-2fTCFbiIxFFHmORPM2gvVVE8ii4HQuWCEg8hFSsC4pCvOVNxXtxz0NyNkp97KVoETuLSECpTL8nCBkypcWvE93qXEdpYBoxbX-JVhkejbcswOy5hGI5DyEIvjWTEtszzMsUlb6nR2dBeNQ8xV43UFwt6NC52l3pcqFMwfkQqo%3D&attredirects=0&d=1), [x64](https://web.archive.org/web/20230604160513if_/https://3670d42b-a-62cb3a1a-s-sites.googlegroups.com/site/astropipp/downloads/pipp_install_x64_2.5.9.zip?attachauth=ANoY7cqdYBVS5zJC7cDe3vfRpo1UMuG8uqwsEO3H3XSOQs9lsTvdMkjXyFDtFmjblJQVQIDiodyD-n1hBMzwLp3J6YqrQ6NVQcpIi2kjYw03KcUfRMhRY6pXH8Wv0oSbX9ulSYm686MqNwRHvw6E7P9HOe_taIkV7VYAdWLJl7SutLtgDbhRchbozZxTh0GgrAIQc8INM8T4dSLaa5O9vbyxSaZT7DiRYHOrBIjgo2ALCjnfG3gigmY%3D&attredirects=0&d=1)) but
1. links seem to long to be used via scoop;
2. using links from WBM will trigger `hash check failed` each time, same as ScoopInstaller/Extras#12574.

So 
- adding links to mirrored files [on another resource](https://www.rsastro.com/downloads/) instead: same hashes as originals,  virustotal check passed;
_(will be replaced if/after ScoopInstaller/Binary#25 will be merged)_
- disabling updates check ([last release in 2017](https://web.archive.org/web/20230604160403/https://sites.google.com/site/astropipp/downloads)).

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

---

Waiting on https://github.com/ScoopInstaller/Binary/pull/25 to be merged first.

### CODE REVIEW

**Comment by amreus** [comment]
There exists a [ScoopInstaller/Binary](https://github.com/ScoopInstaller/Binary) repo "for binaries that no longer exist" - does this belong in the Binary repo since it appears to be no longer available?

**Comment by aliesbelik** [comment]
> There exists a [ScoopInstaller/Binary](https://github.com/ScoopInstaller/Binary) repo "for binaries that no longer exist" - does this belong in the Binary repo since it appears to be no longer available?

Yes, that's an option. The only point (as for me) is that pipp binaries are larger than most of apps from `Binary` bucket and significantly less popular.

**Comment by aliesbelik** [comment]
Waiting on ScoopInstaller/Binary#25.

**Pull request merged**
