### PR TITLE
czkawka-gui: Update to version 6.1.0

### PR DESCRIPTION
**Pull request by sMtzDczDq**
Updated manifest to reflect for change in upstream url.

- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by naciacia** [comment]
bump

**Review by HUMORCE — CHANGES_REQUESTED** [review]
please remove change of bulk-crap-uninstaller

**Pull request closed without merging**
