### PR TITLE
 pdf-foxit-reader: fix autoupdate url

### PR DESCRIPTION
**Pull request by delassiops**
also change download package to international language version

- [ X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
Please also update the app to latest version

**Comment by rashil2000** [comment]
You have modified the autoupdate URL. So it's better to update the manifest here manually.

**Comment by delassiops** [comment]
manifest updated manually

**Pull request merged**
