### PR TITLE
googlechrome: Fix Google Chrome Auto Update Issue

### LINKED ISSUE #5506: Chrome hasn't updated
I noticed that the latest version of Chrome at the time of writing - 87.0.4280.141 - was released on 2021-01-09 and that the version on Scoop is still at 87.0.4280.88.

Hopefully this isn't complicated to solve.

Thank you in advance.

### LINKED ISSUE #5738: googlechrome-canary@89.0.4349.3: Download via aria2 failed
Download failed! (Error 3) Resource was not found
```
> scoop install googlechrome-canary
Installing 'googlechrome-canary' (89.0.4349.3) [64bit] [extras]
WARN  By installing you accept following license: Freeware (https://www.google.com/chrome/privacy/eula_text.html)
Starting download with aria2 ...
Download: 02/21 12:15:08 [ERROR] CUID#8 - Download aborted. URI=https://dl.google.com/release2/chrome/ALLIpT4Xvtp1or36MSzf1sQ_89.0.4349.3/89Download: Exception: [AbstractCommand.cc:351] errorCode=3 URI=https://dl.google.com/release2/chrome/ALLIpT4Xvtp1or36MSzf1sQ_89.0.4349.3/89.0Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 763048|ERR |       0B/s|C:/Users/<user>/scoop/cache/googlechrome-canary#89.0.4349.3#https_dl.google.com_release2_chrome_ALLIpT4Xvtp1or36MSzf1sQ_89.0.4349.3_89.0.4349.3_chrome_installer.exe_dl.7z
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.

ERROR Download failed! (Error 3) Resource was not found
ERROR https://dl.google.com/release2/chrome/ALLIpT4Xvtp1or36MSzf1sQ_89.0.4349.3/89.0.4349.3_chrome_installer.exe#/dl.7z
    referer=https://dl.google.com/release2/chrome/ALLIpT4Xvtp1or36MSzf1sQ_89.0.4349.3/89.0.4349.3_chrome_installer.exe#/
    dir=C:\Users\<user>\scoop\cache
    out=googlechrome-canary#89.0.4349.3#https_dl.google.com_release2_chrome_ALLIpT4Xvtp1or36MSzf1sQ_89.0.4349.3_89.0.4349.3_chrome_installer.exe_dl.7z

ERROR & 'C:\Users\<user>\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\<user>\scoop\cache\googlechrome-canary.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.1 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=6752 --continue --summary-interval 0
ERROR Download failed! (Error 3) Resource was not found

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=googlechrome-canary%4089.0.4349.3%3a+Download+via+aria2+failed&body=Download+failed!+(Error+3)+Resource+was+not+found
```

### LINKED ISSUE #6203: googlechrome-dev@92.0.4496.3: Download via aria2 failed
Download failed! (Error 3) Resource was not found

______________
ERROR Download failed! (Error 3) Resource was not found
ERROR https://dl.google.com/release2/chrome/d8Q2omnP6nYMhpD42ckr6Q_92.0.4496.3/92.0.4496.3_chrome_installer.exe#/dl.7z
    referer=https://dl.google.com/release2/chrome/d8Q2omnP6nYMhpD42ckr6Q_92.0.4496.3/92.0.4496.3_chrome_installer.exe#/
    dir=C:\Users\Sora\scoop\cache
    out=googlechrome-dev#92.0.4496.3#https_dl.google.com_release2_chrome_d8Q2omnP6nYMhpD42ckr6Q_92.0.4496.3_92.0.4496.3_chrome_installer.exe_dl.7z

ERROR & 'C:\Users\Sora\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\Sora\scoop\cache\googlechrome-dev.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.2 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=3540 --continue --summary-interval 0
ERROR Download failed! (Error 3) Resource was not found

### PR DESCRIPTION
**Pull request by Lutra-Fs**
- Close #5506
- Close #5738
- Close #6203 

Use my fork to replace the broken API provided by @SukkaW. 
The version and installer can be updated correctly now.

### CODE REVIEW

**Comment by Lutra-Fs** [comment]
Note that the original api is still broken with the latest commit.

**Comment by Lutra-Fs** [comment]
Anyone reviews this PR or give me some suggestions?

**Comment by SukkaW** [comment]
Apparently the original API back online and works again.

**Comment by SukkaW** [comment]
Because Travis CI disabled all the build on travis-ci.org while I haven't migrated the CI to GitHub Action/New Travis CI.

But the `CheckChrome` project is already dead. Scoop-extra should use the information from Google directly.

https://github.com/SukkaW/CheckChrome/blob/e600a467366f6760d79afe23634ded97c9b38df6/util/checker.sh#L7-L16

**Comment by Lutra-Fs** [comment]
Hi Sukka, I have already created a PR for that repository to fix the error. The solution should work.

**Comment by Lutra-Fs** [comment]
My fork is dead now.

**Comment by Lutra-Fs** [comment]
Migrate to Github Actions in my fork now.

**Pull request closed without merging**
