### PR TITLE
powertoys: Fix dll hardlinks required since 0.63.0

### LINKED ISSUE #9419: PowerToys 0.63.0 doesn't work properly
## Bug Report

**Package Name:** powertoys

### Current Behaviour

The Settings page doesn't not show. A couple modules won't run properly.

### Expected Behaviour

The Settings page and all modules should run.

### Additional context/output

DLL files are now hardlinked into subfolders after this commit: https://github.com/microsoft/PowerToys/commit/665851300dd0adbbbc338788314dcfbb4a10e50b .

### Possible Solution

Replicate the new hardlink steps in the installer script with simple powershell post-install script.

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 7.2.6

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
{
  "lastupdate": "2022-10-08T11:27:45.6662818+08:00",
  "SCOOP_REPO": "https://github.com/ScoopInstaller/Scoop",
  "SCOOP_BRANCH": "master"
}
```

### PR DESCRIPTION
**Pull request by raycheung**
Closes #9419 

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by niheaven — APPROVED** [review]

**Comment by jaimecbernardo** [comment]
Hi @raycheung ,
Are you the one maintaining this package?
As a heads-up, PowerToys 0.66 will come with new hardlink files, due to .net now being self-contained, so we're shipping the dlls as well.
https://github.com/microsoft/PowerToys/commit/6ac508fb933d0a30e1176baae34981f91e0984cf

These are defined in DotnetRuntimeWPFFiles and DotnetRuntimeFiles in the wxs.
Is there a way to stop scoop from updating to 0.66 until these are changed?

**Comment by sidewinder94** [comment]
@jaimecbernardo To prevent an app from updating: `scoop hold <app>`.

To allow it to update again: `scoop unhold <app>`

**Comment by jaimecbernardo** [comment]
I've opened an issue to remove auto-updating from the PowerToys manifest for the time being, since it can't be updated automatically: https://github.com/ScoopInstaller/Extras/pull/10177

**Comment by jaimecbernardo** [comment]
@sidewinder94 , that would be to fix something locally. The issue is that PowerToys can't really auto-update safely since it doesn't run the installer and the installer as custom actions to create deeplinks. The 0.66 release will break every existing user.

**Pull request merged**
