### PR TITLE
plugdata: Add version 0.8.3

### PR DESCRIPTION
**Pull request by make-42**
- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by make-42** [comment]
Resolves https://github.com/ScoopInstaller/Extras/issues/13313

**Comment by aliesbelik** [comment]
1. Please fix manifest ([log](https://github.com/ScoopInstaller/Extras/actions/runs/8949548959/job/25141807478?pr=13231#step:4:26)).
2. Add 32bit version as well.

**Comment by amreus** [comment]
The `bin` shim entry uses spaces which would be unexpected to a command line user. The user would need to quote the command as in:

```
> "plug data"
```

So maybe use `plugdata`.

In general I am OK with a `bin` shim for gui programs, but if there are no command line options then there is probably no need for one. 

And thank you for contributing!

**Comment by make-42** [comment]
Sure thing! I modified the manifest to conform with your requirements!

**Pull request merged**
