### PR TITLE
powertoys: add note about context menu entries

### LINKED ISSUE #4937: powertoys: Add registry keys for context menu
Hi there. I just want to report that if you install powertoys with scoop, the new module's option "PowerRenamer" doesn't appear in the right click context menu as it should. I think there is something wrong in how scoop manages this installation becouse the standard msi file doesn't have this issue.

### PR DESCRIPTION
**Pull request by JanPokorny**
Closes #4937

### CODE REVIEW

**Comment by TheRandomLabs** [comment]
If you're going to add that note, I would avoid linking directly to the `nonportable` bucket.

**Comment by JanPokorny** [comment]
@TheRandomLabs What's the alternative?

**Comment by TheRandomLabs** [comment]
Ah, just reference it as the `nonportable` bucket, since it's a known bucket.

**Comment by rashil2000** [comment]
@HUMORCE is this still needed, after #7090?

**Comment by HUMORCE** [comment]
i think it's unecessary, many app are missing context menu.

**Comment by rashil2000** [comment]
@JanPokorny I'm closing this for now. Instead of a note, if someone can provide .reg files like [vscode](https://github.com/ScoopInstaller/Extras/tree/master/scripts/vscode) or [notepad++](https://github.com/ScoopInstaller/Extras/tree/master/scripts/notepadplusplus), that will be much better.

**Pull request closed without merging**
