### PR TITLE
whepfrom: Add version 0.3.3

### PR DESCRIPTION
**Pull request by Yin-ZP**
Closes #XXXX

Relates to #XXXX

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by StudentWeis** [comment]
What is the difference between this and #12602

**Comment by Yin-ZP** [comment]
different software.Live777 is a media server,whepfrom is a&nbsp;Protocol Conversion module,from whep to rtp.They work together.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ScoopInstaller/Extras"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月15日(星期一) 中午11:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ScoopInstaller/Extras] whepfrom v0.3.3 (PR #12607)





 
What is the difference between this and #12602

**Comment by Yin-ZP** [comment]
> What is the difference between this and #12602

Later i will push a whipinto module.the same as whepfrom, a Protocol Conversion module,from rtp to whip. Total num 3,live777,whepfrom,whipinto.

**Comment by StudentWeis** [comment]
If these three modules are in the same repository, can they be merged into a whole?

**Comment by Yin-ZP** [comment]
> If these three modules are in the same repository, can they be merged into a whole?
sorry ,thay can work together ,but not necessary, thay can also work dependently.I think whis is easy to update different version

**Pull request merged**
