### PR TITLE
bizhawk: Persist 'NDS' and 'Melon' folders

### PR DESCRIPTION
**Pull request by HUMORCE**
close https://github.com/ScoopInstaller/Extras/issues/7009

### CODE REVIEW

**Comment by pratikpc** [comment]
@HUMORCE  could you share some documentation confirming they are supposed to be persisted and compatible between versions?

**Comment by HUMORCE** [comment]
only work for latest version is well

**Comment by pratikpc** [comment]
@HUMORCE no I mean like for example with WinSCP, translations are separate based on versions and 3.5.1 translation is not assured to be compatible with 3.6

So wanted to verify if we face the same issue here? Like no docs say this issue exists right?

If no docs say this, we can merge it now

**Comment by HUMORCE** [comment]
in the example you mentioned, winscp translations is not managed via scoop.
users need to manage these manually.

**Review by issaclin32 — APPROVED** [review]

**Pull request merged**
