### PR TITLE
openlens: Fix `hash`

### LINKED ISSUE #9817: [Bug]: Openlens failed hash check
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

openlens

### Expected/Current Behaviour

I tried to install the latest version of Openlens, the download finishes but the hashes are different. This was intended to be fixed with #9807.  

### Steps to Reproduce

```console
scoop install openlens
Installing 'openlens' (6.2.1) [64bit] from extras bucket
OpenLens-6.2.1.exe (118,5 MB) [===============================================================================] 100%
Checking hash of OpenLens-6.2.1.exe ... ERROR Hash check failed!
App:         extras/openlens
URL:         https://github.com/MuhammedKalkan/OpenLens/releases/download/v6.2.1/OpenLens-6.2.1.exe#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    aa0d1052c17b1f8e604a67db6cb81ea2087a83b6bf8edfe49f28f9ef7d7bb3fd
Actual:      faa4c49187ebebd9ae646e3c3c90b43fb7e0cc36372d390d5cd5ab3e88437281

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=openlens%406.2.1%3a+hash+check+failed
```

### Possible Solution

A possible solution would be to fix the autoupdate manifest. I don't know why there is a different hash.

### Scoop and Buckets Version

```console
scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
30cd350ab (HEAD -> master, origin/master, origin/HEAD) yubioath: Update to version 6.0.0 (#9816)

'main' bucket:
6de3c2f5c (HEAD -> master, origin/master, origin/HEAD) kapp: Update to version 0.54.0
```

### Scoop Config

```console
last_update         scoop_repo                              scoop_branch
-----------         ----------                              ------------
22.11.2022 14:19:45 https://github.com/ScoopInstaller/Scoop master
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Additional Softwares

None.

### PR DESCRIPTION
**Pull request by Zliced13**
Closes #9817

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by HUMORCE** [comment]
hash updated again.

**Comment by niheaven** [comment]
Hmm, sorry I haven't notice this and fixed the hash by https://github.com/ScoopInstaller/Extras/commit/6364cb2a850c67c86d78c63e419b45a54d06c31f 🤣

**Pull request merged**
