### PR TITLE
supermium: Add version 122.0.6261.85

### LINKED ISSUE #12721: [Request]: Supermium
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

supermium

### Description

Chromium fork for Windows XP/2003 and up

### Homepage

https://github.com/win32ss/supermium

### Download Link(s)

https://github.com/win32ss/supermium/releases

### Some Indication of Popularity/Repute

https://github.com/win32ss/supermium

455 stars and 17 forks

### PR DESCRIPTION
**Pull request by bt4ibwem8**
Closes #12721 

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bt4ibwem8** [comment]
does anybody know how to fix it?

**Comment by bt4ibwem8** [comment]
@aliesbelik
hi, thanks for this fix. By the way, why github was not used as the source of the installation file and for updates as well?

**Comment by aliesbelik** [comment]
> @aliesbelik hi, thanks for this fix. By the way, why github was not used as the source of the installation file and for updates as well?

Github is completely ok, both for binaries download and for updates tracking, but if you try to update using your initial version of manifest, you'll get in this case tag name (e.g. `122-r4`) instead of the full version we actually need (e.g. `122.0.6261.85`), because of [default checkver behaviour](https://github.com/ScoopInstaller/Scoop/wiki/App-Manifest-Autoupdate#special-cases) for Github releases, if no custom regex is provided.

I guess if you have enough enthusiasm to continue to tune the manifest you could try to parse
https://api.github.com/repositories/638089306/releases/latest
with custom regex/jsonpath to get both full version name and tag or download url (required for autoupdate).
But in this case please test your updates locally (scripts are available in `/bin` dir).

**Pull request merged**
