### PR TITLE
languagetool: update to windows desktop version 1.0.10

### PR DESCRIPTION
**Pull request by AyoungDukie**
Update version to 1.0.10

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by AyoungDukie** [comment]
Apologies for the clutter; I noticed that the Latest.yml file you referenced seemed to be providing a SHA512 hash, and figured it would be best to base on that. I was mistaken, and now everything is working with that fixed. Thank you for looking at this!

**Review by StarsbySea — APPROVED** [review]

**Review by HUMORCE — APPROVED** [review]

**Pull request merged**
