### PR TITLE
sonic-visualiser: Add version 4.5.2

### LINKED ISSUE #12284: [Request]: Sonic Visualiser 4.5.2
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

Sonic Visualiser

### Description

Visualisation, analysis, and annotation of music audio recordings.

### Homepage

https://github.com/sonic-visualiser/sonic-visualiser

### Download Link(s)

https://github.com/sonic-visualiser/sonic-visualiser/releases/tag/sv_v4.5.2

### Some Indication of Popularity/Repute

https://online.ucpress.edu/jams/article/74/3/701/119252/Sonic-Visualiser-Visualisation-Analysis-and + GitHub traffic etc

Hi there,

I have already created a manifest for Sonic Visualiser (here: https://github.com/ScoopInstaller/Extras/commit/a92d2713d92ad460f3f59766a10ac9d1a253bc12) and was about to open a PR before reading that I had to do a package request first. Sonic Visualiser is a great and open-source tool I have used for many years now to analyse encoded data within audio files.

Hopefully this can make it to the extras branch! Thanks.

### PR DESCRIPTION
**Pull request by obfuscated-loop**
This PR adds a manifest file for Sonic Visualiser.

Closes #12284

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by obfuscated-loop** [comment]
I'm a bit confused as to what I'm doing wrong here 😆

**Comment by obfuscated-loop** [comment]
@assiless Legend! Working fine now... I still think it might be worth making the default behaviour of the GitHub `checkver` to look for the version number wherever its location in the release name.

**Review by HUMORCE — CHANGES_REQUESTED** [review]
Missing shortcuts creation.

**Comment by obfuscated-loop** [comment]
@HUMORCE I was under the impression that the `shortcuts` key was optional as it says in the contributing guide. I currently do not have a Windows install to test this; I'd appreciate if you or somebody else could implement it. Cheers.

**Comment by aliesbelik** [comment]
@obfuscated-loop, @HUMORCE, for your review.

**Comment by obfuscated-loop** [comment]
@aliesbelik Thank you! LGTM :+1:  but I can't submit a review as PR author.

**Pull request merged**
