### PR TITLE
winmtr-live: Add version 1.1

### PR DESCRIPTION
**Pull request by brian6932**
fork of a fork, even has a cli bin

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by HUMORCE** [comment]
create a new manifest instead of overwriting it with variants/forks.

**Comment by brian6932** [comment]
It does keep the same features 🤔
But sure no prob

**Pull request merged**
