### PR TITLE
Update adwcleaner.json: v8.3.1

### PR DESCRIPTION
**Pull request by RavenMacDaddy**
Updates version and corresponding hash to 8.3.1.

### CODE REVIEW

**Comment by rashil2000** [comment]
The PR validation failed. The download link isn't working for me either.

**Comment by RavenMacDaddy** [comment]
Maybe they changed to an appended version to the exe file with this version which makes it fail?

I just assumed #adwcleaner.exe in the URL meant scoop renamed the output.

**Comment by rashil2000** [comment]
> I just assumed #adwcleaner.exe in the URL meant scoop renamed the output.

You are right. The actual link is https://download.toolslib.net/download/direct/1/latest?channel=release which doesn't work.

**Comment by RavenMacDaddy** [comment]
Huh? Works for me both on my desktop and my phone where I'm typing this message.

**Comment by rashil2000** [comment]
Maybe it's a region thing. @HUMORCE can you check once?

**Comment by HUMORCE** [comment]
```
PS C:\Users\HUMOR\Downloads> Get-FileHash .\adwcleaner_8.3.1.exe

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          9607332EBA1668B5223B4112D9120A220BDB60E1A01F79C106168C7C9DE73841       C:\Users\HUMOR\Downloads\adwcleaner_8.3.1.exe
```

**Pull request merged**
