### PR TITLE
everything-powertoys: Add version 0.82.0

### PR DESCRIPTION
**Pull request by lin-ycv**
- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

/verify

### CODE REVIEW

**Comment by lin-ycv** [comment]
package request https://github.com/ScoopInstaller/Extras/issues/12916

**Comment by lin-ycv** [comment]
@aliesbelik is there anything else that I need to do to push the approval along?

**Review by Yohe-Am — APPROVED** [review]
I'm not a pwsh pro but this looks good to me.

**Pull request merged**
