### PR TITLE
status: Update to version 0.8.1-2356ac. Fix `url`, `hash`, installer type, and add `checkver`.

### LINKED ISSUE #9272: status@190516-062034-d94424: download via aria2 failed
#### Scoop Configuration

```json
{
    "lastUpdate":  "2022-09-20T19:26:53.3389578+02:00",
    "SCOOP_REPO":  "https://github.com/ScoopInstaller/Scoop",
    "SCOOP_BRANCH":  "master"
}
```

ERROR Download failed! (Error 3) Resource was not found
ERROR https://status-im.ams3.cdn.digitaloceanspaces.com/StatusIm-190516-062034-d94424-release.exe#/dl.7z
    referer=https://status-im.ams3.cdn.digitaloceanspaces.com/StatusIm-190516-062034-d94424-release.exe#/
    dir=C:\Users\Admin\scoop\cache
    out=status#190516-062034-d94424#https_status-im.ams3.cdn.digitaloceanspaces.com_StatusIm-190516-062034-d94424-release.exe_dl.7z

ERROR & 'C:\Users\Admin\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\Admin\scoop\cache\status.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=2948 --continue --summary-interval=0 --auto-save-interval=1

### PR DESCRIPTION
**Pull request by Zliced13**
Closes #9272

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by chawyehsu** [comment]
Seems the version on their website is outdated compared to its repo, https://github.com/status-im/status-desktop/releases. Should we use their GitHub releases?

**Comment by Zliced13** [comment]
The version released on GitHub is unusable, like I literally cannot open the file. The **Status.exe** process quits after 5 seconds from being opened.

This does not happen at all with the version released on their website.

**Comment by Zliced13** [comment]
Relates to https://github.com/status-im/status-desktop/issues/7906

**Comment by Zliced13** [comment]
For the Scoop app manifest file, I will have to remove autoupdate and checkver temporarily until the Status devs can patch this bug for Windows.

**Comment by Zliced13** [comment]
@chawyehsu The manifest should be good now, the **Status Dev Team** fixed the bug that was persistent on Windows 10+ that was causing it to no launch at all, even with Administrator privileges.

**Comment by Zliced13** [comment]
@chawyehsu I believe this manifest is good for the official **extras** bucket now.

**Comment by Zliced13** [comment]
Wait, let me fix this. Don't merge yet.

**Comment by Zliced13** [comment]
@HUMORCE, it's ready.

**Pull request merged**
