### PR TITLE
yarr: Add version 2.4

### LINKED ISSUE #13055: [Request]: Yarr
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

yarr

### Description

yarr (yet another rss reader) is a web-based feed aggregator

### Homepage

https://github.com/nkanaev/yarr

### Download Link(s)

https://github.com/nkanaev/yarr/releases/download/v2.4/yarr-v2.4-windows64.zip

### Some Indication of Popularity/Repute

2.6K stars on github.

### PR DESCRIPTION
**Pull request by amreus**
Adding https://github.com/nkanaev/yarr feed reader.

Closes #13055 

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by qwertyhjklxyz** [comment]
add environment variables to make the data portable.
```
"env_set": {
    "YARR_DB": "$dir\\data\\storage.db",
    "YARR_LOGFILE": "$dir\\data\\yarr.log"
},
"persist": "data"
```

**Comment by amreus** [comment]
> add environment variables to make the data portable.
> 
> ```
> "env_set": {
>     "YARR_DB": "$dir\\data\\storage.db",
>     "YARR_LOGFILE": "$dir\\data\\yarr.log"
> },
> "persist": "data"
> ```

Yes that is good - I did not see these variables documented anywhere, and had to search through the source code.  I will add a command line shim also since these are options that can be set via command line.
Thanks.

**Comment by qwertyhjklxyz** [comment]
> Why persist a log file?

As you said, when yarr.exe is shimmed, it no longer prints anything.
But it works fine when the scoop shim is configured as scoopcs.

**Comment by amreus** [comment]
> But it works fine when the scoop shim is configured as scoopcs.

I am not familiar with `scoopcs`. I can find no manifest in Main or Extras with the term. 

I do see a reference in `core.ps1` but that doesn't explain too much. There is apparently different shims that can be specified? How to use it? Thanks.

**Comment by qwertyhjklxyz** [comment]
This needs to be configured manually by the user.
```
scoop config shim scoopcs
```


I think it's better to persist the log file, because opening it from shortcut doesn't pop up the terminal output logs.

**Pull request merged**
