### PR TITLE
shadowsocksr-windows: Add version 6.0.1

### PR DESCRIPTION
**Pull request by pessoalzy**
Similar to [shadowsocksr-csharp](https://github.com/ScoopInstaller/Extras/blob/master/bucket/shadowsocksr-csharp.json), more actively maintained by HMBSbige.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
Rename this to `shadowsocksr-hmbsbige`

**Comment by pessoalzy** [comment]
Renamed.

**Comment by rashil2000** [comment]
What's the difference between these 3?

**Comment by pessoalzy** [comment]
The first one is used in the manifest and requiring .NET Desktop Runtime has been installed. While the others contain runtime.

**Comment by rashil2000** [comment]
The individual 32 and 64bit ones are better as they do not require any dependencies.

**Comment by rashil2000** [comment]
Can you post the output of `.\bin\checkver shadowsocksr-hmbsbige -f`?

**Pull request merged**
