### PR TITLE
MagicaVoxel@0.99.6: Fix URL

### LINKED ISSUE #4964: magicavoxel@0.99.6: Download failed
Installing 'magicavoxel' (0.99.6) [64bit]
The remote server returned an error: (404) Not Found.
URL https://github.com/ephtracy/ephtracy.github.io/releases/download/0.99.6/MagicaVoxel-0.99.6-win64.zip is not valid

The correct file name is "MagicaVoxel-0.99.6<strong>.2</strong>-win64.zip".

### LINKED ISSUE #5290: MagicaVoxel version doesn't match
Hello,

When I tried to install *MagicaVoxel*, I got a 404 not found exception.

I went on and looked at both *MagicaVoxel* and [scoop json definition](https://github.com/lukesampson/scoop-extras/blob/master/bucket/MagicaVoxel.json).

Version is listed as **0.99.6** but the binaries are on version **0.99.6.2**. That **.2** revision causes a mismatch between versions.

I don't know if there's any easy way to fix this, seeing that the version in the path and the version in the binaries aren't the same anymore in that release.

`https://github.com/ephtracy/ephtracy.github.io/releases/download/$version/MagicaVoxel-$version-win64.zip` won't work right now, as `$version` should be once 0.99.6 and once 0.99.6.2

I could do a pull request to update properly set it at the moment but I fear that it would break again with next version. 

Anyone has already seen that case and knows how to properly handle this?

### PR DESCRIPTION
**Pull request by Uinelj**
- Closes #4964
- Closes #5290

new version of 0.99.6 changed download paths.
the commit contains updated download path and corresponding hashes.

### CODE REVIEW

**Review by Ash258 — CHANGES_REQUESTED** [review]
Did you try to install it using these files?

I cannot execute it using this build

**Comment by Uinelj** [comment]
Hello,

I've tried to install it and successfully did so, using `scoop install MagicaVoxel.json` (verified today too)
I however tried on a amd64 architecture only.

**Comment by Ash258** [comment]
It do not work with any version on my end. It got terminated immediately and log following to event viewer:

```log
Faulting application name: MagicaVoxel.exe, version: 0.0.0.0, time stamp: 0x5f6ff557
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00000000
Faulting process id: 0xa6c
Faulting application start time: 0x01d6b218f74a65a9
Faulting application path: C:\Users\vagrant\scoop\apps\A\current\MagicaVoxel.exe
Faulting module path: unknown
Report Id: 8bd07a14-d738-4a74-a7f0-77a3ea6c6622
Faulting package full name: 
```

A

**Comment by MunsterPlop** [comment]
I see this hasn't had any feedback in a while.
The problem is that magicavoxel's repo has tags with no build version whereas the downloadable archives do.
Unless they change it, the recipe should probably use a different way to get the proper archive name.

**Comment by pratikpc** [comment]
@Uinelj I think a fix for the same was added and this file has conflicts

If the issue is not yet resolved, can you create a new PR for the same

**Pull request closed without merging**
