### PR TITLE
cherrytree: Update to version 0.99.44.0

### LINKED ISSUE #5145: Cherrytree autoupdate broken
Cherytree for Windows is now 64-bit only, rather than 32-bit only, so checkver can't find the link or hash. Both are still listed on their [homepage](https://www.giuspen.com/cherrytree/#downl).

Right now, Cherrytree is at version 0.39.4 while the latest is 0.99.20.

### PR DESCRIPTION
**Pull request by shaqo88**
- Closes #5145

### CODE REVIEW

**Review by Ash258 — CHANGES_REQUESTED** [review]
Configuration files were changed. Persisting needs to be reconfigured and migrated

**Comment by shaqo88** [comment]
> Configuration files were changed. Persisting needs to be reconfigured and migrated

Can you explain what I need to do?

**Comment by shaqo88** [comment]
Can anyone help with this?

> Configuration files were changed. Persisting needs to be reconfigured and migrated

**Comment by issaclin32** [comment]
I updated the manifest myself, because the PR has not been active in a while.

**Comment by rashil2000** [comment]
I think the `*_portable.7z` does have a portable config. See: 

image

**Comment by issaclin32** [comment]
> I think the `*_portable.7z` does have a portable config. See:
> 
> image

Thanks. It looks like if we put `config.cfg` in `$dir`, then `$LocalAppData` will not be used.
Sorry I didn't check carefully.

**Review by rashil2000 — APPROVED** [review]

**Comment by rashil2000** [comment]
No worries :)

**Pull request merged**
