### PR TITLE
uniextract2: prevent warning window pop-up from happening

### PR DESCRIPTION
**Pull request by Zliced13**
Fixes this issue when the user runs the command for the first time:
image_7

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ViCrack** [comment]
I think the warning is necessary,   Warn user before executing malicious files for extraction.

**Comment by KrisSchneider** [comment]
https://github.com/ScoopInstaller/Extras/pull/9344#issuecomment-1259452722
> I think the warning is necessary, Warn user before executing malicious files for extraction.

Should I create a .ps1 script that allows users to disable the warning message if they want to?

**Comment by ViCrack** [comment]
> Should I create a .ps1 script that allows users to disable the warning message if they want to?

Maybe you can make a issue to their repo([UniExtract2](https://github.com/Bioruebe/UniExtract2)) to fix `/silent` parameter?

**Comment by KrisSchneider** [comment]
Alright, the disable-warning.ps1 script is made and done. Now anyone can disable it if they want to.

**Pull request closed without merging**
