### PR TITLE
komf: add version 0.26.0

### LINKED ISSUE #8997: [Request] Komf
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [ ] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [x] the latest stable version of the program

### Information

**Name:** komf

**Description:**  Komga metadata fetcher 

**Homepage:** https://github.com/Snd-R/komf

**Download link(s):** https://github.com/Snd-R/komf/releases

**Some indication of popularity/repute:**
[Readme Card](https://github.com/Snd-R/komf)

### Notes
This is an app to fetch metadata for Komga. It's a 3rd party app but it's quite popular to be used with Komga, even Komga's official discord server have dedicated channel for this app. But right now the stats did not fulfill the requirement of 100 stars and 50 forks. Should I wait till it reach the requirement to add the app in this repo? or a companion app for popular app is excluded in the popularity requirement?

### PR DESCRIPTION
**Pull request by Zliced13**
Closes #8997

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by KrisSchneider** [comment]
@issaclin32 I believe there is a bug with the **github-actions** bot, it thinks my checkver is incorrect.

**Review by HUMORCE — APPROVED** [review]
Tested.

**Comment by Zliced13** [comment]
Wait let me update this.

**Comment by HUMORCE** [comment]
> Wait let me update this.

I have actually compiled it

**Review by HUMORCE — APPROVED** [review]

**Comment by Zliced13** [comment]
You accidentally removed the description.

**Pull request merged**
