### PR TITLE
Wonderpen: Add version 2.0.5

### PR DESCRIPTION
**Pull request by hu3rror**
- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

I wonder if there's a better regular expression in `autoupdate` 🤔

No persist file.

### CODE REVIEW

**Comment by niheaven** [comment]
```json
{
    "homepage": "https://www.atominn.com/en/wonderpen",
    "description": "Professional writing app with a focused and fluid writing experience.",
    "version": "2.0.5",
    "license": {
        "identifier": "Proprietary",
        "url": "https://www.atominn.com/term/privacy"
    },
    "architecture": {
        "64bit": {
            "url": "https://file.atominn.net/WonderPen/2.0/WonderPen_win_installer_x64_2.0.5(6174).exe#/dl.7z",
            "hash": "196538e7338d3d674b99351ad105855d0a5316d88b9c4ac3b0f5d06569ada3a4",
            "installer": {
                "script": [
                    "Expand-7ZipArchive \"$dir\\`$PLUGINSDIR\\app-64.7z\" \"$dir\" -Removal",
                    "Remove-Item \"$dir\\`$PLUGINSDIR\", \"$dir\\Uninstall*\" -Force -Recurse"
                ]
            }
        },
        "32bit": {
            "url": "https://file.atominn.net/WonderPen/2.0/WonderPen_win_installer_ia32_2.0.5(6174).exe#/dl.7z",
            "hash": "3e8e386c3ffa2b8cf4d48c99b3f4c829e72370ba29826ade29fe30682b4bad69",
            "installer": {
                "script": [
                    "Expand-7ZipArchive \"$dir\\`$PLUGINSDIR\\app-32.7z\" \"$dir\" -Removal",
                    "Remove-Item \"$dir\\`$PLUGINSDIR\", \"$dir\\Uninstall*\" -Force -Recurse"
                ]
            }
        }
    },
    "shortcuts": [
        [
            "WonderPen.exe",
            "WonderPen"
        ]
    ],
    "checkver": {
        "url": "https://www.atominn.com/wonderpen/download/all",
        "regex": "([\\d.]+)\\((?<build>[\\d]+)\\)"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://file.atominn.net/WonderPen/$majorVersion.$minorVersion/WonderPen_win_installer_x64_$version($matchBuild).exe#/dl.7z"
            },
            "32bit": {
                "url": "https://file.atominn.net/WonderPen/$majorVersion.$minorVersion/WonderPen_win_installer_ia32_$version($matchBuild).exe#/dl.7z"
            }
        }
    }
}
```

**Comment by hu3rror** [comment]
> ```json
> {
>     "homepage": "https://www.atominn.com/en/wonderpen",
>     "description": "Professional writing app with a focused and fluid writing experience.",
>     "version": "2.0.5",
>     "license": {
>         "identifier": "Proprietary",
>         "url": "https://www.atominn.com/term/privacy"
>     },
>     "architecture": {
>         "64bit": {
>             "url": "https://file.atominn.net/WonderPen/2.0/WonderPen_win_installer_x64_2.0.5(6174).exe#/dl.7z",
>             "hash": "196538e7338d3d674b99351ad105855d0a5316d88b9c4ac3b0f5d06569ada3a4",
>             "installer": {
>                 "script": [
>                     "Expand-7ZipArchive \"$dir\\`$PLUGINSDIR\\app-64.7z\" \"$dir\" -Removal",
>                     "Remove-Item \"$dir\\`$PLUGINSDIR\", \"$dir\\Uninstall*\" -Force -Recurse"
>                 ]
>             }
>         },
>         "32bit": {
>             "url": "https://file.atominn.net/WonderPen/2.0/WonderPen_win_installer_ia32_2.0.5(6174).exe#/dl.7z",
>             "hash": "3e8e386c3ffa2b8cf4d48c99b3f4c829e72370ba29826ade29fe30682b4bad69",
>             "installer": {
>                 "script": [
>                     "Expand-7ZipArchive \"$dir\\`$PLUGINSDIR\\app-32.7z\" \"$dir\" -Removal",
>                     "Remove-Item \"$dir\\`$PLUGINSDIR\", \"$dir\\Uninstall*\" -Force -Recurse"
>                 ]
>             }
>         }
>     },
>     "shortcuts": [
>         [
>             "WonderPen.exe",
>             "WonderPen"
>         ]
>     ],
>     "checkver": {
>         "url": "https://www.atominn.com/wonderpen/download/all",
>         "regex": "([\\d.]+)\\((?<build>[\\d]+)\\)"
>     },
>     "autoupdate": {
>         "architecture": {
>             "64bit": {
>                 "url": "https://file.atominn.net/WonderPen/$majorVersion.$minorVersion/WonderPen_win_installer_x64_$version($matchBuild).exe#/dl.7z"
>             },
>             "32bit": {
>                 "url": "https://file.atominn.net/WonderPen/$majorVersion.$minorVersion/WonderPen_win_installer_ia32_$version($matchBuild).exe#/dl.7z"
>             }
>         }
>     }
> }
> ```

Thank you. I have also planned to split the 64-bit and 32-bit architecture, but considering the official 2-in-1 version, I don't know if the author will still be retained in the future. So far, your manifest is better👍

**Comment by niheaven** [comment]
> Thank you. I have also planned to split the 64-bit and 32-bit architecture, but considering the official 2-in-1 version, I don't know if the author will still be retained in the future. So far, your manifest is better👍There are some variables that I don't know until now. Thank you again

Since no one needs both arch imo, the separate installers are better until the author doesn't provide them, then we should fix the manifest.

**Review by niheaven — APPROVED** [review]

**Pull request merged**
