### PR TITLE
lazy-posh-git: Add version 0.2.0

### PR DESCRIPTION
**Pull request by goto1134**
Adds lazy-posh-git version 0.1.0

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by HUMORCE** [comment]
Maybe we should switch to gh releases? both of checkver and download url.

**Comment by goto1134** [comment]
I looked at posh-git package and used the same approach. If there is a reason for switching the source, surely I could do it!

**Comment by HUMORCE** [comment]
> If there is a reason for switching the source

- Avoid downloading from a fixed-location CDN
- High level version check

**Comment by goto1134** [comment]
@HUMORCE, that sounds reasonable to me! Thank you for the suggestions. Should we fix posh-git too?

**Review by HUMORCE — APPROVED** [review]

**Comment by HUMORCE** [comment]
> Should we fix posh-git too?

of course, if you have time.

```
❯ scoop search posh-git
Results from local buckets...

Name             Version    Source   Binaries
----             -------    ------   --------
posh-git         1.1.0      extras
posh-git-beta    1.1.0      versions
posh-git-nightly 4b746d6e48 versions
```

**Comment by goto1134** [comment]
Unfortunately, posh-git releases are not published on github

**Pull request merged**
