### PR TITLE
Add automatic version check for chrome series

### PR DESCRIPTION
**Pull request by Lutra-Fs**
Same with #6070 with the repos update. As when I update the branch with the newest main branch, some files are wrongly recognized as edited by Github. See #7096  for disscussion

### CODE REVIEW

**Comment by issaclin32** [comment]
@Lutra-Fs Sorry for the long wait. I changed the url to https://github.com/ScoopInstaller/UpdateTracker, and re-structured the code to:
(1) Remove components that are not required by *Scoop* to update the package.
(2) Provide extensibility for other packages.

Waiting for opinions from other maintainers.

**Review by rasa — APPROVED** [review]

**Review by rasa — APPROVED** [review]
Looks great, but I haven't tested it.

**Comment by rashil2000** [comment]
The PR Handler failed midway? Other than that looks good to me.

**Pull request merged**
