### PR TITLE
affine: Add version 0.13.1

### LINKED ISSUE #11706: [Request]: AFFiNE
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

AFFiNE

### Description

A privacy-focussed, local-first, open-source, and ready-to-use alternative for Notion & Miro.

### Homepage

https://affine.pro/

### Download Link(s)

https://github.com/toeverything/AFFiNE/releases/download/v0.7.1/affine-stable-windows-x64.zip

### Some Indication of Popularity/Repute

20.7k github stars.

### PR DESCRIPTION
**Pull request by chawyehsu**
Closes #11706

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aliuq** [comment]
I tried it with `v0.11.2`, when opend this app, it will be auto update download package at `~/AppData/Local/AFFiNE`.

**Comment by aliesbelik** [comment]
@chawyehsu, could you please update manifest to the actual version and state, if still interested in adding to Extras.
Thanks anyway.

**Comment by aliesbelik** [comment]
Relates to toeverything/AFFiNE#5247.

**Pull request merged**
