### PR TITLE
Ungoogled-chromium-portable: Update to version 89.0.4389.114

### PR DESCRIPTION
**Pull request by ikenichiro**
Autoupdate has been also modified and updated.
This app is basically the portable version for ungoogled-chromium, so it will temporary provide an alternative workaround for #5479.

### CODE REVIEW

**Comment by pratikpc** [comment]
Closing in favour of https://github.com/ScoopInstaller/Extras/pull/7282

**Comment by ikenichiro** [comment]
Sorry I couldn't come around to fix after proposing this PR

**Comment by pratikpc** [comment]
@ikenichiro no worries.

You can always help us fix another issue if you find them.

For example, not all Chromium packages are still at their latest versions.

**Comment by ikenichiro** [comment]
@pratikpc
My initial motivation of this PR was from #5479  but with the ungoogled-chromium-portable working, ( #7282 ) I don't have enough motivation to provide fixes to the original ungoogled-chromium.
I know that the package ungoogled-chromium is outdated (as you said, not all Chromium packages are their latest) and I think the repository needs to be changed to Eloston/ungoogled-chromium and download binaries from, https://ungoogled-software.github.io/ungoogled-chromium-binaries/
But as I reported in the issues #5479 , some kind of work around may still be needed to be done for chrome.exe to work in the "current" directory.

**Pull request closed without merging**
