### PR TITLE
space: Add version 0.1.2

### PR DESCRIPTION
**Pull request by emilevr**
Adds a new manifest for the space CLI, which is yet another disk space usage tool, written in Rust (for fun and learning).

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by amreus** [comment]
Nice app.  This is ready to merge please. 

@pureby @StudentWeis @kriswilk @wickles @zsuatem @octaviordz  @aliesbelik

**Comment by aliesbelik** [comment]
@StudentWeis Wonder if there are any objective reasons to remove `autoupdate.hash` from manifest? As I can see hash files are regularly provided along with binaries across the releases.

**Comment by StudentWeis** [comment]
Sorry about it, it's my mistake.

**Comment by StudentWeis** [comment]
> @StudentWeis Wonder if there are any objective reasons to remove `autoupdate.hash` from manifest? As I can see hash files are regularly provided along with binaries across the releases.

Sorry about it, it's my mistake.

**Pull request merged**
