### PR TITLE
watchman: Add version 2022.05.16.00

### PR DESCRIPTION
**Pull request by ClassicDarkChocolate**
[watchman](https://facebook.github.io/watchman/) is a file watching service by Facebook.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rashil2000** [comment]
This is a CLI package, right? If yes then migrate this PR to Main bucket

**Comment by ClassicDarkChocolate** [comment]
> This is a CLI package, right? If yes then migrate this PR to Main bucket

According to official site:

> Watchman is considered to be in beta status for Windows but has a reasonably sized group of users depending on it already, and we expect to remove the beta label in the coming months.

Does package with beta version pass criteria for main bucket?

**Comment by rashil2000** [comment]
I think it is okay to add this particular package to Main

**Pull request closed without merging**
