### PR TITLE
iptvnator: Add version 0.15.1

### LINKED ISSUE #13467: [Request]: Iptvnator
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

iptvnator

### Description

Cross-platform IPTV player with multiple features, such as support of m3u and m3u8 playlists, favorites, TV guide, TV archive/catchup and more.

### Homepage

https://github.com/4gray/iptvnator

### Download Link(s)

https://github.com/4gray/iptvnator/releases/download/v0.15.1/IPTVnator-Setup-0.15.1.exe

### Some Indication of Popularity/Repute

popular app for watching TV with 2k github stars and 300 forks

### PR DESCRIPTION
**Pull request by bt4ibwem8**
Closes #13467

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bt4ibwem8** [comment]
Did i create PR correctly? The bot does not want to run after **/verify**

**Comment by aliesbelik** [comment]
Please follow the standard order of fields in the json file, as per [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md#for-scoop-buckets).

**Comment by bt4ibwem8** [comment]
@aliesbelik corrected, hopefully now is everything correct

**Pull request merged**
