### PR TITLE
foxit-pdf-reader: update autoupdate url, update to version 12.1.0.15250

### PR DESCRIPTION
**Pull request by delassiops**
- [X ] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

/Verify

### CODE REVIEW

**Comment by HUMORCE** [comment]
Please make changes to `foxit-reader` as well.

**Comment by delassiops** [comment]
> Please make changes to `foxit-reader` as well.

Foxit-reader is a old bucket, my advice to delete it,

What you thinks ?

**Comment by HUMORCE** [comment]
> Foxit-reader is a old bucket, my advice to delete it,

> Will be removed after scoop supports manifest alias feature. https://github.com/ScoopInstaller/Extras/pull/9633#issue-1433411847

**Pull request merged**
