### PR TITLE
renamer: Fix license

### PR DESCRIPTION
**Pull request by HUMORCE**
close https://github.com/ScoopInstaller/Extras/issues/7189

### CODE REVIEW

**Comment by rashil2000** [comment]
Can you push an empty commit to rerun the AppVeyor CI?

**Review by rasa — COMMENTED** [review]
Should’t this be
`CC-BY-NC-ND-3.0|Shareware`
per https://www.den4b.com/license

**Comment by HUMORCE** [comment]
@rasa according to the license page, then no changes are required

@rashil2000 still fails

**Review by rasa — APPROVED** [review]

**Comment by rashil2000** [comment]
I think you need to rebase with master then

**Comment by HUMORCE** [comment]
https://github.com/ScoopInstaller/Extras/issues/7546

**Comment by rashil2000** [comment]
Okay, let's merge and see

**Pull request merged**
