### PR TITLE
Wonderpen: Update to 2.0.8

### PR DESCRIPTION
**Pull request by hu3rror**
- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

The official 32-bit separate installation package is cancelled by the developer and now updated to a two-in-one installation package.

Also the url for checkver has been updated.

### CODE REVIEW

**Comment by issaclin32** [comment]
Since 64-bit and 32-bit now downloads the same file, you can move `url` and `hash` out of the `architecture` block. (it looks cleaner, and easier to maintain)

```
    "url": "https://www.tominlab.com/to/get-file/cdn?file=WonderPen/2.0/WonderPen_win_installer_2.0.8(6212).exe#/dl.7z",
    "hash": "701e883ae4e1f6038caf6fac7d31988bf7e551d2fa81ab0ed495093d1f55fd39",
    "architecture": {
        "64bit": {
            "installer": {
                "script": [
                    "Expand-7ZipArchive \"$dir\\`$PLUGINSDIR\\app-64.7z\" \"$dir\" -Removal",
                    "Remove-Item \"$dir\\`$PLUGINSDIR\", \"$dir\\Uninstall*\" -Force -Recurse"
                ]
            }
        },
        "32bit": {
        .........
```

```
    "autoupdate": {
        "url": "https://www.tominlab.com/to/get-file/cdn?file=WonderPen/$majorVersion.$minorVersion/WonderPen_win_installer_$version($matchBuild).exe#/dl.7z"
    }
```

**Comment by tech189** [comment]
Here's the output of the /verify check:
```
INFO: Starting bucket/wonderpen.json checks

Manifest: C:\Users\runneradmin\AppData\Local\Temp\forked_repository\bucket\wonderpen.json

INFO: Hashes

OperationStopped: C:\Users\runneradmin\SCOOP\apps\scoop\current\lib\install.ps1:138
Line |
 138 |          throw $e
     |          ~~~~~~~~
     | The remote server returned an error: (404) Not Found.
```
I am able to access the file myself.

**Comment by hu3rror** [comment]
> Here's the output of the /verify check:
> 
> ```
> INFO: Starting bucket/wonderpen.json checks
> 
> Manifest: C:\Users\runneradmin\AppData\Local\Temp\forked_repository\bucket\wonderpen.json
> 
> INFO: Hashes
> 
> OperationStopped: C:\Users\runneradmin\SCOOP\apps\scoop\current\lib\install.ps1:138
> Line |
>  138 |          throw $e
>      |          ~~~~~~~~
>      | The remote server returned an error: (404) Not Found.
> ```
> 
> I am able to access the file myself.

Thanks for the info. The url has been re-corrected and the hash value has been changed too.

**Pull request merged**
