### PR TITLE
search-deflector: Add version 1.3.2

### PR DESCRIPTION
**Pull request by chawyehsu**

### CODE REVIEW

**Comment by rasa** [comment]
Virustotal's score is [4/72](https://www.virustotal.com/gui/file/c84e52e04d2361b7a659a2e9eb3e0c5557a24443ee12c741ef698a2dc5eafd49/detection).  Should we worry?

**Comment by chawyehsu** [comment]
IDK, ref https://github.com/spikespaz/search-deflector/issues/53#issuecomment-540267340

**Comment by spikespaz** [comment]
Review the code, see that it is safe. Compile it yourself, see the same results on VirusTotal as the binaries that I distribute. If you know what is going wrong with the program to warrant such high false-positive rates, please let me know because this concerns me especially.

**Comment by karlkras** [comment]
so this utility is still not considered "safe" on windows 10 ?

**Comment by spikespaz** [comment]
@karlkras It has been considered "safe", but the free version does trigger antivirus false-positives. The package with the compiled executables and resource files has been vetted and approved for distribution by Microsoft.

https://www.microsoft.com/store/productId/9P8ZJJ80RZ2K

**Comment by karlkras** [comment]
> @karlkras It has been considered "safe", but the free version does trigger antivirus false-positives. The package with the compiled executables and resource files has been vetted and approved for distribution by Microsoft.
> 
> https://www.microsoft.com/store/productId/9P8ZJJ80RZ2K

Oh, and I have to pay for it... great, Microsoft has to get theirs either way.

**Comment by spikespaz** [comment]
@karlkras The money goes to me to support development and it is a free program. Look at my GitHub page before you trash it.

**Comment by karlkras** [comment]
> @karlkras The money goes to me to support development and it is a free program. Look at my GitHub page before you trash it.

Oh, sincere apologies. I assumed Microsoft royalties.

**Comment by rashil2000** [comment]
Doesn't `"innounp": true` automatically add innosetup as dependency? We can remove the `depends` field.

**Review by issaclin32 — APPROVED** [review]

**Comment by spikespaz** [comment]
@issaclin32 It is up to you, however I would recommend reverting this merge. My project has been nonfunctional on newer versions of Windows for some time now, because Microsoft keeps changing the way Windows Search handles browser redirects. I am actively working on v2.0.0 and suggest that we wait to include this project in any public repositories.

Thanks.

**Comment by rashil2000** [comment]
Can you tell in which exact versions Deflector still works? We can put that in the notes section. I say this because Scoop still supports PCs back to Windows 7.

**Comment by issaclin32** [comment]
> Can you tell in which exact versions Deflector still works? We can put that in the notes section. I say this because Scoop still supports PCs back to Windows 7.

I think we can keep this app in the bucket, as long as we can inform the users in the `notes` section. Also it will reduce the effort later (when ver2.0 is released) because the packages can be updated automatically.

**Pull request merged**
